# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from open5e.models.creature_action_attack import CreatureActionAttack
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatureAction(BaseModel):
    """
    Much of the logic included in the GameContentSerializer is intended to support manipulating data returned by the serializer via query parameters.
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=100)] = Field(description="Name of the item.")
    desc: Optional[StrictStr] = Field(default=None, description="Description of the game content item. Markdown.")
    attacks: List[CreatureActionAttack]
    action_type: Optional[StrictStr] = Field(default=None, description="The type of action used.  * `ACTION` - Action * `REACTION` - Reaction * `BONUS_ACTION` - Bonus Action * `LEGENDARY_ACTION` - Legendary Action * `LAIR_ACTION` - Lair Action")
    order_in_statblock: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)]] = Field(default=None, description="The position in the list of features that a feature appears in its source statblock")
    legendary_action_cost: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)]] = Field(default=None, description="null if not legendary, else, the number of legendary actions this costs.")
    limited_to_form: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Description of form-based conditions for this action.")
    usage_limits: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["name", "desc", "attacks", "action_type", "order_in_statblock", "legendary_action_cost", "limited_to_form", "usage_limits"]

    @field_validator('action_type')
    def action_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTION', 'REACTION', 'BONUS_ACTION', 'LEGENDARY_ACTION', 'LAIR_ACTION', '']):
            raise ValueError("must be one of enum values ('ACTION', 'REACTION', 'BONUS_ACTION', 'LEGENDARY_ACTION', 'LAIR_ACTION', '')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatureAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "attacks",
            "usage_limits",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attacks (list)
        _items = []
        if self.attacks:
            for _item_attacks in self.attacks:
                if _item_attacks:
                    _items.append(_item_attacks.to_dict())
            _dict['attacks'] = _items
        # set to None if action_type (nullable) is None
        # and model_fields_set contains the field
        if self.action_type is None and "action_type" in self.model_fields_set:
            _dict['action_type'] = None

        # set to None if order_in_statblock (nullable) is None
        # and model_fields_set contains the field
        if self.order_in_statblock is None and "order_in_statblock" in self.model_fields_set:
            _dict['order_in_statblock'] = None

        # set to None if legendary_action_cost (nullable) is None
        # and model_fields_set contains the field
        if self.legendary_action_cost is None and "legendary_action_cost" in self.model_fields_set:
            _dict['legendary_action_cost'] = None

        # set to None if limited_to_form (nullable) is None
        # and model_fields_set contains the field
        if self.limited_to_form is None and "limited_to_form" in self.model_fields_set:
            _dict['limited_to_form'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatureAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "desc": obj.get("desc"),
            "attacks": [CreatureActionAttack.from_dict(_item) for _item in obj["attacks"]] if obj.get("attacks") is not None else None,
            "action_type": obj.get("action_type"),
            "order_in_statblock": obj.get("order_in_statblock"),
            "legendary_action_cost": obj.get("legendary_action_cost"),
            "limited_to_form": obj.get("limited_to_form"),
            "usage_limits": obj.get("usage_limits")
        })
        return _obj


