# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from open5e.models.condition_summary import ConditionSummary
from open5e.models.damage_type_summary import DamageTypeSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatureResistancesAndImmunities(BaseModel):
    """
    This serializer formats a Creature's damage modifier as a single obj
    """ # noqa: E501
    damage_immunities_display: StrictStr
    damage_immunities: List[DamageTypeSummary]
    damage_resistances_display: StrictStr
    damage_resistances: List[DamageTypeSummary]
    damage_vulnerabilities_display: StrictStr
    damage_vulnerabilities: List[DamageTypeSummary]
    condition_immunities_display: StrictStr
    condition_immunities: List[ConditionSummary]
    __properties: ClassVar[List[str]] = ["damage_immunities_display", "damage_immunities", "damage_resistances_display", "damage_resistances", "damage_vulnerabilities_display", "damage_vulnerabilities", "condition_immunities_display", "condition_immunities"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatureResistancesAndImmunities from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in damage_immunities (list)
        _items = []
        if self.damage_immunities:
            for _item_damage_immunities in self.damage_immunities:
                if _item_damage_immunities:
                    _items.append(_item_damage_immunities.to_dict())
            _dict['damage_immunities'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in damage_resistances (list)
        _items = []
        if self.damage_resistances:
            for _item_damage_resistances in self.damage_resistances:
                if _item_damage_resistances:
                    _items.append(_item_damage_resistances.to_dict())
            _dict['damage_resistances'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in damage_vulnerabilities (list)
        _items = []
        if self.damage_vulnerabilities:
            for _item_damage_vulnerabilities in self.damage_vulnerabilities:
                if _item_damage_vulnerabilities:
                    _items.append(_item_damage_vulnerabilities.to_dict())
            _dict['damage_vulnerabilities'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in condition_immunities (list)
        _items = []
        if self.condition_immunities:
            for _item_condition_immunities in self.condition_immunities:
                if _item_condition_immunities:
                    _items.append(_item_condition_immunities.to_dict())
            _dict['condition_immunities'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatureResistancesAndImmunities from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "damage_immunities_display": obj.get("damage_immunities_display"),
            "damage_immunities": [DamageTypeSummary.from_dict(_item) for _item in obj["damage_immunities"]] if obj.get("damage_immunities") is not None else None,
            "damage_resistances_display": obj.get("damage_resistances_display"),
            "damage_resistances": [DamageTypeSummary.from_dict(_item) for _item in obj["damage_resistances"]] if obj.get("damage_resistances") is not None else None,
            "damage_vulnerabilities_display": obj.get("damage_vulnerabilities_display"),
            "damage_vulnerabilities": [DamageTypeSummary.from_dict(_item) for _item in obj["damage_vulnerabilities"]] if obj.get("damage_vulnerabilities") is not None else None,
            "condition_immunities_display": obj.get("condition_immunities_display"),
            "condition_immunities": [ConditionSummary.from_dict(_item) for _item in obj["condition_immunities"]] if obj.get("condition_immunities") is not None else None
        })
        return _obj


