# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from open5e.models.game_system_summary import GameSystemSummary
from open5e.models.publisher_summary import PublisherSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DocumentSummary(BaseModel):
    """
    A slimmer DocumentSerializer, designed to serialize Documents FKs on other serializers. Not intended to be used directly with in a ModelViewset.
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=100)] = Field(description="Name of the item.")
    key: Annotated[str, Field(strict=True, max_length=100)] = Field(description="Unique key for the Document.")
    type: Optional[StrictStr] = Field(default=None, description="Whether this Document is a published data source, or general resources  * `SOURCE` - Source * `MISC` - Miscellaneous")
    display_name: StrictStr
    publisher: PublisherSummary
    gamesystem: GameSystemSummary
    permalink: Annotated[str, Field(strict=True, max_length=200)] = Field(description="Link to the document.")
    __properties: ClassVar[List[str]] = ["name", "key", "type", "display_name", "publisher", "gamesystem", "permalink"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SOURCE', 'MISC']):
            raise ValueError("must be one of enum values ('SOURCE', 'MISC')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "display_name",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of publisher
        if self.publisher:
            _dict['publisher'] = self.publisher.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gamesystem
        if self.gamesystem:
            _dict['gamesystem'] = self.gamesystem.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "key": obj.get("key"),
            "type": obj.get("type"),
            "display_name": obj.get("display_name"),
            "publisher": PublisherSummary.from_dict(obj["publisher"]) if obj.get("publisher") is not None else None,
            "gamesystem": GameSystemSummary.from_dict(obj["gamesystem"]) if obj.get("gamesystem") is not None else None,
            "permalink": obj.get("permalink")
        })
        return _obj


