# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from open5e.models.character_class_summary import CharacterClassSummary
from open5e.models.cross_references import CrossReferences
from open5e.models.document_summary import DocumentSummary
from open5e.models.spell_casting_option import SpellCastingOption
from open5e.models.spell_school_summary import SpellSchoolSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Spell(BaseModel):
    """
    Much of the logic included in the GameContentSerializer is intended to support manipulating data returned by the serializer via query parameters.
    """ # noqa: E501
    key: StrictStr = Field(description="Unique key for the Item.")
    document: DocumentSummary
    casting_options: List[SpellCastingOption]
    school: SpellSchoolSummary
    classes: List[CharacterClassSummary]
    range_unit: StrictStr
    shape_size_unit: StrictStr
    name: Annotated[str, Field(strict=True, max_length=100)] = Field(description="Name of the item.")
    desc: Optional[StrictStr] = Field(default=None, description="Description of the game content item. Markdown.")
    level: Annotated[int, Field(le=9, strict=True, ge=0)] = Field(description="Integer representing the default slot level required by the spell.")
    higher_level: Optional[StrictStr] = Field(default=None, description="Description of casting the spell at a different level.")
    target_type: Optional[StrictStr] = Field(default=None, description="Spell target type key.  * `creature` - Creature * `object` - Object * `point` - Point * `area` - Area")
    range_text: StrictStr = Field(description="Spell target range.")
    range: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(default=None, description="Used to measure distance.")
    ritual: Optional[StrictBool] = Field(default=None, description="Whether or not the spell can be cast as a ritual.")
    casting_time: StrictStr = Field(description="Casting time key, such as 'action'  * `reaction` - Reaction * `bonus-action` - 1 Bonus Action * `action` - 1 Action * `turn` - 1 Turn * `round` - 1 Round * `1minute` - 1 Minute * `5minutes` - 5 Minutes * `10minutes` - 10 Minutes * `1hour` - 1 Hour * `4hours` - 4 Hours * `7hours` - 7 Hours * `8hours` - 8 Hours * `9hours` - 9 Hours * `12hours` - 12 Hours * `24hours` - 24 Hours * `1week` - 1 Week")
    reaction_condition: Optional[StrictStr] = Field(default=None, description="The conditions describing when a reaction spell can be cast")
    verbal: Optional[StrictBool] = Field(default=None, description="Whether or not casting the spell requires a verbal component.")
    somatic: Optional[StrictBool] = Field(default=None, description="Whether or not casting the spell requires a verbal component.")
    material: Optional[StrictBool] = Field(default=None, description="Whether or not casting the spell requires a verbal component.")
    material_specified: Optional[StrictStr] = Field(default=None, description="Description of the material specified for the spell.")
    material_cost: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Number representing the cost of the materials of the spell.")
    material_consumed: Optional[StrictBool] = Field(default=None, description="Whether or the material component is consumed during the casting.")
    target_count: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(default=None, description="Integer representing the count of targets.")
    saving_throw_ability: Optional[StrictStr] = Field(default=None, description="Given the spell requires a saving throw, which ability is targeted. Empty string if no saving throw.")
    attack_roll: Optional[StrictBool] = Field(default=None, description="Whether or not the spell effect requires an attack roll.")
    damage_roll: Optional[StrictStr] = Field(default=None, description="The damage roll for the field in dice notation. Empty string if no roll.")
    damage_types: Optional[Any] = Field(default=None, description="The types of damage done by the spell in a list.")
    duration: StrictStr = Field(description="Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"  * `instantaneous` - instantaneous * `instantaneous or special` - instantaneous or special * `1 turn` - 1 turn * `1 round` - 1 round * `concentration + 1 round` - concentration + 1 round * `2 rounds` - 2 rounds * `3 rounds` - 3 rounds * `4 rounds` - 4 rounds * `1d4+2 rounds` - 1d4+2 rounds * `5 rounds` - 5 rounds * `6 rounds` - 6 rounds * `10 rounds` - 10 rounds * `up to 1 minute` - up to 1 minute * `1 minute` - 1 minute * `1 minute, or until expended` - 1 minute, or until expended * `1 minute, until expended` - 1 minute, until expended * `5 minutes` - 5 minutes * `10 minutes` - 10 minutes * `1 minute or 1 hour` - 1 minute or 1 hour * `up to 1 hour` - up to 1 hour * `1 hour` - 1 hour * `1 hour or until triggered` - 1 hour or until triggered * `2 hours` - 2 hours * `3 hours` - 3 hours * `1d10 hours` - 1d10 hours * `6 hours` - 6 hours * `2-12 hours` - 2-12 hours * `up to 8 hours` - up to 8 hours * `8 hours` - 8 hours * `1 hour/caster level` - 1 hour/caster level * `10 hours` - 10 hours * `12 hours` - 12 hours * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw * `24 hours` - 24 hours * `1 day` - 1 day * `3 days` - 3 days * `5 days` - 5 days * `7 days` - 7 days * `10 days` - 10 days * `13 days` - 13 days * `30 days` - 30 days * `1 year` - 1 year * `special` - special * `until dispelled or destroyed` - until dispelled or destroyed * `until destroyed` - until destroyed * `until dispelled` - until dispelled * `until cured or dispelled` - until cured or dispelled * `until dispelled or triggered` - until dispelled or triggered * `permanent until discharged` - permanent until discharged * `permanent; one generation` - permanent; one generation * `permanent` - permanent")
    shape_type: Optional[StrictStr] = Field(default=None, description="The shape of the area of effect.  * `cone` - Cone * `cube` - Cube * `cylinder` - Cylinder * `line` - Line * `sphere` - sphere")
    shape_size: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(default=None, description="Used to measure distance.")
    concentration: Optional[StrictBool] = Field(default=None, description="Whether the effect requires concentration to be maintained.")
    crossreferences: CrossReferences
    __properties: ClassVar[List[str]] = ["key", "document", "casting_options", "school", "classes", "range_unit", "shape_size_unit", "name", "desc", "level", "higher_level", "target_type", "range_text", "range", "ritual", "casting_time", "reaction_condition", "verbal", "somatic", "material", "material_specified", "material_cost", "material_consumed", "target_count", "saving_throw_ability", "attack_roll", "damage_roll", "damage_types", "duration", "shape_type", "shape_size", "concentration", "crossreferences"]

    @field_validator('target_type')
    def target_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['creature', 'object', 'point', 'area', '']):
            raise ValueError("must be one of enum values ('creature', 'object', 'point', 'area', '')")
        return value

    @field_validator('casting_time')
    def casting_time_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['reaction', 'bonus-action', 'action', 'turn', 'round', '1minute', '5minutes', '10minutes', '1hour', '4hours', '7hours', '8hours', '9hours', '12hours', '24hours', '1week']):
            raise ValueError("must be one of enum values ('reaction', 'bonus-action', 'action', 'turn', 'round', '1minute', '5minutes', '10minutes', '1hour', '4hours', '7hours', '8hours', '9hours', '12hours', '24hours', '1week')")
        return value

    @field_validator('material_cost')
    def material_cost_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^-?\d{0,8}(?:\.\d{0,2})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,8}(?:\.\d{0,2})?$/")
        return value

    @field_validator('duration')
    def duration_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['instantaneous', 'instantaneous or special', '1 turn', '1 round', 'concentration + 1 round', '2 rounds', '3 rounds', '4 rounds', '1d4+2 rounds', '5 rounds', '6 rounds', '10 rounds', 'up to 1 minute', '1 minute', '1 minute, or until expended', '1 minute, until expended', '5 minutes', '10 minutes', '1 minute or 1 hour', 'up to 1 hour', '1 hour', '1 hour or until triggered', '2 hours', '3 hours', '1d10 hours', '6 hours', '2-12 hours', 'up to 8 hours', '8 hours', '1 hour/caster level', '10 hours', '12 hours', '24 hours or until the target attempts a third death saving throw', '24 hours', '1 day', '3 days', '5 days', '7 days', '10 days', '13 days', '30 days', '1 year', 'special', 'until dispelled or destroyed', 'until destroyed', 'until dispelled', 'until cured or dispelled', 'until dispelled or triggered', 'permanent until discharged', 'permanent; one generation', 'permanent']):
            raise ValueError("must be one of enum values ('instantaneous', 'instantaneous or special', '1 turn', '1 round', 'concentration + 1 round', '2 rounds', '3 rounds', '4 rounds', '1d4+2 rounds', '5 rounds', '6 rounds', '10 rounds', 'up to 1 minute', '1 minute', '1 minute, or until expended', '1 minute, until expended', '5 minutes', '10 minutes', '1 minute or 1 hour', 'up to 1 hour', '1 hour', '1 hour or until triggered', '2 hours', '3 hours', '1d10 hours', '6 hours', '2-12 hours', 'up to 8 hours', '8 hours', '1 hour/caster level', '10 hours', '12 hours', '24 hours or until the target attempts a third death saving throw', '24 hours', '1 day', '3 days', '5 days', '7 days', '10 days', '13 days', '30 days', '1 year', 'special', 'until dispelled or destroyed', 'until destroyed', 'until dispelled', 'until cured or dispelled', 'until dispelled or triggered', 'permanent until discharged', 'permanent; one generation', 'permanent')")
        return value

    @field_validator('shape_type')
    def shape_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['cone', 'cube', 'cylinder', 'line', 'sphere', '']):
            raise ValueError("must be one of enum values ('cone', 'cube', 'cylinder', 'line', 'sphere', '')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Spell from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "key",
            "range_unit",
            "shape_size_unit",
            "crossreferences",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of document
        if self.document:
            _dict['document'] = self.document.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in casting_options (list)
        _items = []
        if self.casting_options:
            for _item_casting_options in self.casting_options:
                if _item_casting_options:
                    _items.append(_item_casting_options.to_dict())
            _dict['casting_options'] = _items
        # override the default output from pydantic by calling `to_dict()` of school
        if self.school:
            _dict['school'] = self.school.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in classes (list)
        _items = []
        if self.classes:
            for _item_classes in self.classes:
                if _item_classes:
                    _items.append(_item_classes.to_dict())
            _dict['classes'] = _items
        # override the default output from pydantic by calling `to_dict()` of crossreferences
        if self.crossreferences:
            _dict['crossreferences'] = self.crossreferences.to_dict()
        # set to None if target_type (nullable) is None
        # and model_fields_set contains the field
        if self.target_type is None and "target_type" in self.model_fields_set:
            _dict['target_type'] = None

        # set to None if range (nullable) is None
        # and model_fields_set contains the field
        if self.range is None and "range" in self.model_fields_set:
            _dict['range'] = None

        # set to None if reaction_condition (nullable) is None
        # and model_fields_set contains the field
        if self.reaction_condition is None and "reaction_condition" in self.model_fields_set:
            _dict['reaction_condition'] = None

        # set to None if material_cost (nullable) is None
        # and model_fields_set contains the field
        if self.material_cost is None and "material_cost" in self.model_fields_set:
            _dict['material_cost'] = None

        # set to None if target_count (nullable) is None
        # and model_fields_set contains the field
        if self.target_count is None and "target_count" in self.model_fields_set:
            _dict['target_count'] = None

        # set to None if damage_types (nullable) is None
        # and model_fields_set contains the field
        if self.damage_types is None and "damage_types" in self.model_fields_set:
            _dict['damage_types'] = None

        # set to None if shape_type (nullable) is None
        # and model_fields_set contains the field
        if self.shape_type is None and "shape_type" in self.model_fields_set:
            _dict['shape_type'] = None

        # set to None if shape_size (nullable) is None
        # and model_fields_set contains the field
        if self.shape_size is None and "shape_size" in self.model_fields_set:
            _dict['shape_size'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Spell from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "document": DocumentSummary.from_dict(obj["document"]) if obj.get("document") is not None else None,
            "casting_options": [SpellCastingOption.from_dict(_item) for _item in obj["casting_options"]] if obj.get("casting_options") is not None else None,
            "school": SpellSchoolSummary.from_dict(obj["school"]) if obj.get("school") is not None else None,
            "classes": [CharacterClassSummary.from_dict(_item) for _item in obj["classes"]] if obj.get("classes") is not None else None,
            "range_unit": obj.get("range_unit"),
            "shape_size_unit": obj.get("shape_size_unit"),
            "name": obj.get("name"),
            "desc": obj.get("desc"),
            "level": obj.get("level"),
            "higher_level": obj.get("higher_level"),
            "target_type": obj.get("target_type"),
            "range_text": obj.get("range_text"),
            "range": obj.get("range"),
            "ritual": obj.get("ritual"),
            "casting_time": obj.get("casting_time"),
            "reaction_condition": obj.get("reaction_condition"),
            "verbal": obj.get("verbal"),
            "somatic": obj.get("somatic"),
            "material": obj.get("material"),
            "material_specified": obj.get("material_specified"),
            "material_cost": obj.get("material_cost"),
            "material_consumed": obj.get("material_consumed"),
            "target_count": obj.get("target_count"),
            "saving_throw_ability": obj.get("saving_throw_ability"),
            "attack_roll": obj.get("attack_roll"),
            "damage_roll": obj.get("damage_roll"),
            "damage_types": obj.get("damage_types"),
            "duration": obj.get("duration"),
            "shape_type": obj.get("shape_type"),
            "shape_size": obj.get("shape_size"),
            "concentration": obj.get("concentration"),
            "crossreferences": CrossReferences.from_dict(obj["crossreferences"]) if obj.get("crossreferences") is not None else None
        })
        return _obj


