"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from open5e.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from ._crossreferencelink import CrossReferenceLink, CrossReferenceLinkTypedDict
    from .abilitysummary import AbilitySummary, AbilitySummaryTypedDict
    from .characterclass import (
        CasterType,
        CharacterClass,
        CharacterClassCrossreferences,
        CharacterClassCrossreferencesTypedDict,
        CharacterClassTypedDict,
        HitDice,
        HitPoints,
        HitPointsTypedDict,
    )
    from .characterclasssummary import (
        CharacterClassSummary,
        CharacterClassSummaryTypedDict,
    )
    from .classes_listop import ClassesListRequest, ClassesListRequestTypedDict
    from .classes_retrieveop import (
        ClassesRetrieveRequest,
        ClassesRetrieveRequestTypedDict,
    )
    from .classfeature import ClassFeature, ClassFeatureTypedDict, FeatureType
    from .classfeatureprefetch import (
        ClassFeaturePrefetch,
        ClassFeaturePrefetchTypedDict,
    )
    from .conditionsummary import ConditionSummary, ConditionSummaryTypedDict
    from .creature import (
        AbilityScores,
        AbilityScoresTypedDict,
        Creature,
        CreatureCrossreferences,
        CreatureCrossreferencesTypedDict,
        CreatureTypedDict,
        Modifiers,
        ModifiersTypedDict,
        SavingThrows,
        SavingThrowsAll,
        SavingThrowsAllTypedDict,
        SavingThrowsTypedDict,
        SkillBonuses,
        SkillBonusesAll,
        SkillBonusesAllTypedDict,
        SkillBonusesTypedDict,
        Speed,
        SpeedAll,
        SpeedAllTypedDict,
        SpeedTypedDict,
    )
    from .creatureaction import ActionType, CreatureAction, CreatureActionTypedDict
    from .creatureactionattack import (
        AttackType,
        CreatureActionAttack,
        CreatureActionAttackTypedDict,
        DamageDieType,
        ExtraDamageDieType,
    )
    from .creaturelanguage import CreatureLanguage, CreatureLanguageTypedDict
    from .creatureresistancesandimmunities import (
        CreatureResistancesAndImmunities,
        CreatureResistancesAndImmunitiesTypedDict,
    )
    from .creatures_listop import CreaturesListRequest, CreaturesListRequestTypedDict
    from .creatures_retrieveop import (
        CreaturesRetrieveRequest,
        CreaturesRetrieveRequestTypedDict,
    )
    from .creaturetrait import CreatureTrait, CreatureTraitTypedDict
    from .creaturetypesummary import CreatureTypeSummary, CreatureTypeSummaryTypedDict
    from .damagetypesummary import DamageTypeSummary, DamageTypeSummaryTypedDict
    from .documentsummary import (
        DocumentSummary,
        DocumentSummaryType,
        DocumentSummaryTypedDict,
    )
    from .environmentsummary import EnvironmentSummary, EnvironmentSummaryTypedDict
    from .gamesystemsummary import GameSystemSummary, GameSystemSummaryTypedDict
    from .imagesummary import ImageSummary, ImageSummaryTypedDict
    from .languagesummary import LanguageSummary, LanguageSummaryTypedDict
    from .paginatedcharacterclasslist import (
        PaginatedCharacterClassList,
        PaginatedCharacterClassListTypedDict,
    )
    from .paginatedcreaturelist import (
        PaginatedCreatureList,
        PaginatedCreatureListTypedDict,
    )
    from .paginatedspelllist import PaginatedSpellList, PaginatedSpellListTypedDict
    from .publishersummary import PublisherSummary, PublisherSummaryTypedDict
    from .sizesummary import SizeSummary, SizeSummaryTypedDict
    from .spell import (
        CastingTime,
        Duration,
        ShapeType,
        Spell,
        SpellCrossreferences,
        SpellCrossreferencesTypedDict,
        SpellTypedDict,
        TargetType,
    )
    from .spellcastingoption import (
        SpellCastingOption,
        SpellCastingOptionType,
        SpellCastingOptionTypedDict,
    )
    from .spells_listop import (
        SpellsListCastingTime,
        SpellsListDuration,
        SpellsListRequest,
        SpellsListRequestTypedDict,
    )
    from .spells_retrieveop import SpellsRetrieveRequest, SpellsRetrieveRequestTypedDict
    from .spellschoolsummary import SpellSchoolSummary, SpellSchoolSummaryTypedDict

__all__ = [
    "AbilityScores",
    "AbilityScoresTypedDict",
    "AbilitySummary",
    "AbilitySummaryTypedDict",
    "ActionType",
    "AttackType",
    "CasterType",
    "CastingTime",
    "CharacterClass",
    "CharacterClassCrossreferences",
    "CharacterClassCrossreferencesTypedDict",
    "CharacterClassSummary",
    "CharacterClassSummaryTypedDict",
    "CharacterClassTypedDict",
    "ClassFeature",
    "ClassFeaturePrefetch",
    "ClassFeaturePrefetchTypedDict",
    "ClassFeatureTypedDict",
    "ClassesListRequest",
    "ClassesListRequestTypedDict",
    "ClassesRetrieveRequest",
    "ClassesRetrieveRequestTypedDict",
    "ConditionSummary",
    "ConditionSummaryTypedDict",
    "Creature",
    "CreatureAction",
    "CreatureActionAttack",
    "CreatureActionAttackTypedDict",
    "CreatureActionTypedDict",
    "CreatureCrossreferences",
    "CreatureCrossreferencesTypedDict",
    "CreatureLanguage",
    "CreatureLanguageTypedDict",
    "CreatureResistancesAndImmunities",
    "CreatureResistancesAndImmunitiesTypedDict",
    "CreatureTrait",
    "CreatureTraitTypedDict",
    "CreatureTypeSummary",
    "CreatureTypeSummaryTypedDict",
    "CreatureTypedDict",
    "CreaturesListRequest",
    "CreaturesListRequestTypedDict",
    "CreaturesRetrieveRequest",
    "CreaturesRetrieveRequestTypedDict",
    "CrossReferenceLink",
    "CrossReferenceLinkTypedDict",
    "DamageDieType",
    "DamageTypeSummary",
    "DamageTypeSummaryTypedDict",
    "DocumentSummary",
    "DocumentSummaryType",
    "DocumentSummaryTypedDict",
    "Duration",
    "EnvironmentSummary",
    "EnvironmentSummaryTypedDict",
    "ExtraDamageDieType",
    "FeatureType",
    "GameSystemSummary",
    "GameSystemSummaryTypedDict",
    "HitDice",
    "HitPoints",
    "HitPointsTypedDict",
    "ImageSummary",
    "ImageSummaryTypedDict",
    "LanguageSummary",
    "LanguageSummaryTypedDict",
    "Modifiers",
    "ModifiersTypedDict",
    "PaginatedCharacterClassList",
    "PaginatedCharacterClassListTypedDict",
    "PaginatedCreatureList",
    "PaginatedCreatureListTypedDict",
    "PaginatedSpellList",
    "PaginatedSpellListTypedDict",
    "PublisherSummary",
    "PublisherSummaryTypedDict",
    "SavingThrows",
    "SavingThrowsAll",
    "SavingThrowsAllTypedDict",
    "SavingThrowsTypedDict",
    "ShapeType",
    "SizeSummary",
    "SizeSummaryTypedDict",
    "SkillBonuses",
    "SkillBonusesAll",
    "SkillBonusesAllTypedDict",
    "SkillBonusesTypedDict",
    "Speed",
    "SpeedAll",
    "SpeedAllTypedDict",
    "SpeedTypedDict",
    "Spell",
    "SpellCastingOption",
    "SpellCastingOptionType",
    "SpellCastingOptionTypedDict",
    "SpellCrossreferences",
    "SpellCrossreferencesTypedDict",
    "SpellSchoolSummary",
    "SpellSchoolSummaryTypedDict",
    "SpellTypedDict",
    "SpellsListCastingTime",
    "SpellsListDuration",
    "SpellsListRequest",
    "SpellsListRequestTypedDict",
    "SpellsRetrieveRequest",
    "SpellsRetrieveRequestTypedDict",
    "TargetType",
]

_dynamic_imports: dict[str, str] = {
    "CrossReferenceLink": "._crossreferencelink",
    "CrossReferenceLinkTypedDict": "._crossreferencelink",
    "AbilitySummary": ".abilitysummary",
    "AbilitySummaryTypedDict": ".abilitysummary",
    "CasterType": ".characterclass",
    "CharacterClass": ".characterclass",
    "CharacterClassCrossreferences": ".characterclass",
    "CharacterClassCrossreferencesTypedDict": ".characterclass",
    "CharacterClassTypedDict": ".characterclass",
    "HitDice": ".characterclass",
    "HitPoints": ".characterclass",
    "HitPointsTypedDict": ".characterclass",
    "CharacterClassSummary": ".characterclasssummary",
    "CharacterClassSummaryTypedDict": ".characterclasssummary",
    "ClassesListRequest": ".classes_listop",
    "ClassesListRequestTypedDict": ".classes_listop",
    "ClassesRetrieveRequest": ".classes_retrieveop",
    "ClassesRetrieveRequestTypedDict": ".classes_retrieveop",
    "ClassFeature": ".classfeature",
    "ClassFeatureTypedDict": ".classfeature",
    "FeatureType": ".classfeature",
    "ClassFeaturePrefetch": ".classfeatureprefetch",
    "ClassFeaturePrefetchTypedDict": ".classfeatureprefetch",
    "ConditionSummary": ".conditionsummary",
    "ConditionSummaryTypedDict": ".conditionsummary",
    "AbilityScores": ".creature",
    "AbilityScoresTypedDict": ".creature",
    "Creature": ".creature",
    "CreatureCrossreferences": ".creature",
    "CreatureCrossreferencesTypedDict": ".creature",
    "CreatureTypedDict": ".creature",
    "Modifiers": ".creature",
    "ModifiersTypedDict": ".creature",
    "SavingThrows": ".creature",
    "SavingThrowsAll": ".creature",
    "SavingThrowsAllTypedDict": ".creature",
    "SavingThrowsTypedDict": ".creature",
    "SkillBonuses": ".creature",
    "SkillBonusesAll": ".creature",
    "SkillBonusesAllTypedDict": ".creature",
    "SkillBonusesTypedDict": ".creature",
    "Speed": ".creature",
    "SpeedAll": ".creature",
    "SpeedAllTypedDict": ".creature",
    "SpeedTypedDict": ".creature",
    "ActionType": ".creatureaction",
    "CreatureAction": ".creatureaction",
    "CreatureActionTypedDict": ".creatureaction",
    "AttackType": ".creatureactionattack",
    "CreatureActionAttack": ".creatureactionattack",
    "CreatureActionAttackTypedDict": ".creatureactionattack",
    "DamageDieType": ".creatureactionattack",
    "ExtraDamageDieType": ".creatureactionattack",
    "CreatureLanguage": ".creaturelanguage",
    "CreatureLanguageTypedDict": ".creaturelanguage",
    "CreatureResistancesAndImmunities": ".creatureresistancesandimmunities",
    "CreatureResistancesAndImmunitiesTypedDict": ".creatureresistancesandimmunities",
    "CreaturesListRequest": ".creatures_listop",
    "CreaturesListRequestTypedDict": ".creatures_listop",
    "CreaturesRetrieveRequest": ".creatures_retrieveop",
    "CreaturesRetrieveRequestTypedDict": ".creatures_retrieveop",
    "CreatureTrait": ".creaturetrait",
    "CreatureTraitTypedDict": ".creaturetrait",
    "CreatureTypeSummary": ".creaturetypesummary",
    "CreatureTypeSummaryTypedDict": ".creaturetypesummary",
    "DamageTypeSummary": ".damagetypesummary",
    "DamageTypeSummaryTypedDict": ".damagetypesummary",
    "DocumentSummary": ".documentsummary",
    "DocumentSummaryType": ".documentsummary",
    "DocumentSummaryTypedDict": ".documentsummary",
    "EnvironmentSummary": ".environmentsummary",
    "EnvironmentSummaryTypedDict": ".environmentsummary",
    "GameSystemSummary": ".gamesystemsummary",
    "GameSystemSummaryTypedDict": ".gamesystemsummary",
    "ImageSummary": ".imagesummary",
    "ImageSummaryTypedDict": ".imagesummary",
    "LanguageSummary": ".languagesummary",
    "LanguageSummaryTypedDict": ".languagesummary",
    "PaginatedCharacterClassList": ".paginatedcharacterclasslist",
    "PaginatedCharacterClassListTypedDict": ".paginatedcharacterclasslist",
    "PaginatedCreatureList": ".paginatedcreaturelist",
    "PaginatedCreatureListTypedDict": ".paginatedcreaturelist",
    "PaginatedSpellList": ".paginatedspelllist",
    "PaginatedSpellListTypedDict": ".paginatedspelllist",
    "PublisherSummary": ".publishersummary",
    "PublisherSummaryTypedDict": ".publishersummary",
    "SizeSummary": ".sizesummary",
    "SizeSummaryTypedDict": ".sizesummary",
    "CastingTime": ".spell",
    "Duration": ".spell",
    "ShapeType": ".spell",
    "Spell": ".spell",
    "SpellCrossreferences": ".spell",
    "SpellCrossreferencesTypedDict": ".spell",
    "SpellTypedDict": ".spell",
    "TargetType": ".spell",
    "SpellCastingOption": ".spellcastingoption",
    "SpellCastingOptionType": ".spellcastingoption",
    "SpellCastingOptionTypedDict": ".spellcastingoption",
    "SpellsListCastingTime": ".spells_listop",
    "SpellsListDuration": ".spells_listop",
    "SpellsListRequest": ".spells_listop",
    "SpellsListRequestTypedDict": ".spells_listop",
    "SpellsRetrieveRequest": ".spells_retrieveop",
    "SpellsRetrieveRequestTypedDict": ".spells_retrieveop",
    "SpellSchoolSummary": ".spellschoolsummary",
    "SpellSchoolSummaryTypedDict": ".spellschoolsummary",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
