"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import BaseModel
from typing_extensions import TypedDict


class CrossReferenceLinkTypedDict(TypedDict):
    r"""One link in crossreferences.to; defines API shape and serialization."""

    anchor: str
    url: str


class CrossReferenceLink(BaseModel):
    r"""One link in crossreferences.to; defines API shape and serialization."""

    anchor: str

    url: str
