"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import BaseModel
from typing_extensions import TypedDict


class CharacterClassSummaryTypedDict(TypedDict):
    r"""A slimmer CharacterClassSerializer, designed to serialize Class FKs on
    other serializers. ie. The `subclass_of` field on the
    CharacterClassSerializer serializer. Not intended to be used directly in a
    ModelViewset.
    """

    name: str
    r"""Name of the item."""
    key: str
    r"""Unique key for the Item."""


class CharacterClassSummary(BaseModel):
    r"""A slimmer CharacterClassSerializer, designed to serialize Class FKs on
    other serializers. ie. The `subclass_of` field on the
    CharacterClassSerializer serializer. Not intended to be used directly in a
    ModelViewset.
    """

    name: str
    r"""Name of the item."""

    key: str
    r"""Unique key for the Item."""
