"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ._crossreferencelink import CrossReferenceLink, CrossReferenceLinkTypedDict
from .abilitysummary import AbilitySummary, AbilitySummaryTypedDict
from .characterclasssummary import CharacterClassSummary, CharacterClassSummaryTypedDict
from .classfeature import ClassFeature, ClassFeatureTypedDict
from .documentsummary import DocumentSummary, DocumentSummaryTypedDict
from open5e.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


class HitPointsTypedDict(TypedDict):
    hit_dice: int
    hit_dice_name: str
    hit_points_at_1st_level: int
    hit_points_at_higher_levels: int


class HitPoints(BaseModel):
    hit_dice: int

    hit_dice_name: str

    hit_points_at_1st_level: int

    hit_points_at_higher_levels: int


HitDice = Union[
    Literal[
        "D3",
        "D4",
        "D6",
        "D8",
        "D10",
        "D12",
        "D20",
        "d3",
        "d4",
        "d6",
        "d8",
        "d10",
        "d12",
        "d20",
        "",
    ],
    UnrecognizedStr,
]
r"""Dice notation hit dice option.

* `D3` - d3
* `D4` - d4
* `D6` - d6
* `D8` - d8
* `D10` - d10
* `D12` - d12
* `D20` - d20
* `d3` - d3
* `d4` - d4
* `d6` - d6
* `d8` - d8
* `d10` - d10
* `d12` - d12
* `d20` - d20
"""


CasterType = Union[
    Literal[
        "FULL",
        "HALF",
        "PACT",
        "NONE",
        "",
    ],
    UnrecognizedStr,
]
r"""Type of caster. Options are full, half, none.

* `FULL` - Full
* `HALF` - Half
* `PACT` - Pact
* `NONE` - None
"""


class CharacterClassCrossreferencesTypedDict(TypedDict):
    to: List[CrossReferenceLinkTypedDict]


class CharacterClassCrossreferences(BaseModel):
    to: List[CrossReferenceLink]


class CharacterClassTypedDict(TypedDict):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    key: str
    r"""Unique key for the Item."""
    features: List[ClassFeatureTypedDict]
    hit_points: HitPointsTypedDict
    document: DocumentSummaryTypedDict
    r"""A slimmer DocumentSerializer, designed to serialize Documents FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """
    saving_throws: List[AbilitySummaryTypedDict]
    subclass_of: CharacterClassSummaryTypedDict
    r"""A slimmer CharacterClassSerializer, designed to serialize Class FKs on
    other serializers. ie. The `subclass_of` field on the
    CharacterClassSerializer serializer. Not intended to be used directly in a
    ModelViewset.
    """
    name: str
    r"""Name of the item."""
    primary_abilities: List[str]
    r"""Primary abilities for thie class"""
    crossreferences: CharacterClassCrossreferencesTypedDict
    desc: NotRequired[str]
    r"""Description of the game content item. Markdown."""
    hit_dice: NotRequired[Nullable[HitDice]]
    r"""Dice notation hit dice option.

    * `D3` - d3
    * `D4` - d4
    * `D6` - d6
    * `D8` - d8
    * `D10` - d10
    * `D12` - d12
    * `D20` - d20
    * `d3` - d3
    * `d4` - d4
    * `d6` - d6
    * `d8` - d8
    * `d10` - d10
    * `d12` - d12
    * `d20` - d20
    """
    caster_type: NotRequired[Nullable[CasterType]]
    r"""Type of caster. Options are full, half, none.

    * `FULL` - Full
    * `HALF` - Half
    * `PACT` - Pact
    * `NONE` - None
    """


class CharacterClass(BaseModel):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    key: str
    r"""Unique key for the Item."""

    features: List[ClassFeature]

    hit_points: HitPoints

    document: DocumentSummary
    r"""A slimmer DocumentSerializer, designed to serialize Documents FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """

    saving_throws: List[AbilitySummary]

    subclass_of: CharacterClassSummary
    r"""A slimmer CharacterClassSerializer, designed to serialize Class FKs on
    other serializers. ie. The `subclass_of` field on the
    CharacterClassSerializer serializer. Not intended to be used directly in a
    ModelViewset.
    """

    name: str
    r"""Name of the item."""

    primary_abilities: List[str]
    r"""Primary abilities for thie class"""

    crossreferences: CharacterClassCrossreferences

    desc: Optional[str] = None
    r"""Description of the game content item. Markdown."""

    hit_dice: OptionalNullable[HitDice] = UNSET
    r"""Dice notation hit dice option.

    * `D3` - d3
    * `D4` - d4
    * `D6` - d6
    * `D8` - d8
    * `D10` - d10
    * `D12` - d12
    * `D20` - d20
    * `d3` - d3
    * `d4` - d4
    * `d6` - d6
    * `d8` - d8
    * `d10` - d10
    * `d12` - d12
    * `d20` - d20
    """

    caster_type: OptionalNullable[CasterType] = UNSET
    r"""Type of caster. Options are full, half, none.

    * `FULL` - Full
    * `HALF` - Half
    * `PACT` - Pact
    * `NONE` - None
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["desc", "hit_dice", "caster_type"])
        nullable_fields = set(["hit_dice", "caster_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
