"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .classfeatureprefetch import ClassFeaturePrefetch, ClassFeaturePrefetchTypedDict
from open5e.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


FeatureType = Union[
    Literal[
        "CORE_TRAITS_TABLE",
        "CLASS_LEVEL_FEATURE",
        "CLASS_FEATURE_OPTION_LIST",
        "CLASS_TABLE_DATA",
        "PROFICIENCIES",
        "PROFICIENCY_BONUS",
        "STARTING_EQUIPMENT",
        "SPELL_SLOTS",
    ],
    UnrecognizedStr,
]
r"""The type that best represents this Class Feature

* `CORE_TRAITS_TABLE` - CORE_TRAITS_TABLE
* `CLASS_LEVEL_FEATURE` - CLASS_LEVEL_FEATURE
* `CLASS_FEATURE_OPTION_LIST` - CLASS_FEATURE_OPTION_LIST
* `CLASS_TABLE_DATA` - CLASS_TABLE_DATA
* `PROFICIENCIES` - PROFICIENCIES
* `PROFICIENCY_BONUS` - PROFICIENCY_BONUS
* `STARTING_EQUIPMENT` - STARTING_EQUIPMENT
* `SPELL_SLOTS` - SPELL_SLOTS
"""


class ClassFeatureTypedDict(TypedDict):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    key: str
    r"""Unique key for the Item."""
    name: str
    r"""Name of the item."""
    feature_items: List[ClassFeaturePrefetchTypedDict]
    desc: NotRequired[str]
    r"""Description of the game content item. Markdown."""
    feature_type: NotRequired[FeatureType]
    r"""The type that best represents this Class Feature

    * `CORE_TRAITS_TABLE` - CORE_TRAITS_TABLE
    * `CLASS_LEVEL_FEATURE` - CLASS_LEVEL_FEATURE
    * `CLASS_FEATURE_OPTION_LIST` - CLASS_FEATURE_OPTION_LIST
    * `CLASS_TABLE_DATA` - CLASS_TABLE_DATA
    * `PROFICIENCIES` - PROFICIENCIES
    * `PROFICIENCY_BONUS` - PROFICIENCY_BONUS
    * `STARTING_EQUIPMENT` - STARTING_EQUIPMENT
    * `SPELL_SLOTS` - SPELL_SLOTS
    """


class ClassFeature(BaseModel):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    key: str
    r"""Unique key for the Item."""

    name: str
    r"""Name of the item."""

    feature_items: List[ClassFeaturePrefetch]

    desc: Optional[str] = None
    r"""Description of the game content item. Markdown."""

    feature_type: Optional[FeatureType] = None
    r"""The type that best represents this Class Feature

    * `CORE_TRAITS_TABLE` - CORE_TRAITS_TABLE
    * `CLASS_LEVEL_FEATURE` - CLASS_LEVEL_FEATURE
    * `CLASS_FEATURE_OPTION_LIST` - CLASS_FEATURE_OPTION_LIST
    * `CLASS_TABLE_DATA` - CLASS_TABLE_DATA
    * `PROFICIENCIES` - PROFICIENCIES
    * `PROFICIENCY_BONUS` - PROFICIENCY_BONUS
    * `STARTING_EQUIPMENT` - STARTING_EQUIPMENT
    * `SPELL_SLOTS` - SPELL_SLOTS
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["desc", "feature_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
