"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import BaseModel
from open5e.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class ClassesRetrieveRequestTypedDict(TypedDict):
    key: str


class ClassesRetrieveRequest(BaseModel):
    key: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
