"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import BaseModel
from typing_extensions import TypedDict


class ConditionSummaryTypedDict(TypedDict):
    r"""A slimmer ConditionSerializer, designed to serialize Condition FKs on
    other serializers. ie. The `condition_immunities` field on the Creature
    serializer. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""
    key: str
    r"""Unique key for the Item."""


class ConditionSummary(BaseModel):
    r"""A slimmer ConditionSerializer, designed to serialize Condition FKs on
    other serializers. ie. The `condition_immunities` field on the Creature
    serializer. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""

    key: str
    r"""Unique key for the Item."""
