"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creatureactionattack import CreatureActionAttack, CreatureActionAttackTypedDict
from open5e.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


ActionType = Union[
    Literal[
        "ACTION",
        "REACTION",
        "BONUS_ACTION",
        "LEGENDARY_ACTION",
        "LAIR_ACTION",
        "",
    ],
    UnrecognizedStr,
]
r"""The type of action used.

* `ACTION` - Action
* `REACTION` - Reaction
* `BONUS_ACTION` - Bonus Action
* `LEGENDARY_ACTION` - Legendary Action
* `LAIR_ACTION` - Lair Action
"""


class CreatureActionTypedDict(TypedDict):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    name: str
    r"""Name of the item."""
    attacks: List[CreatureActionAttackTypedDict]
    usage_limits: Dict[str, Any]
    desc: NotRequired[str]
    r"""Description of the game content item. Markdown."""
    action_type: NotRequired[Nullable[ActionType]]
    r"""The type of action used.

    * `ACTION` - Action
    * `REACTION` - Reaction
    * `BONUS_ACTION` - Bonus Action
    * `LEGENDARY_ACTION` - Legendary Action
    * `LAIR_ACTION` - Lair Action
    """
    order_in_statblock: NotRequired[Nullable[int]]
    r"""The position in the list of features that a feature appears in its source statblock"""
    legendary_action_cost: NotRequired[Nullable[int]]
    r"""null if not legendary, else, the number of legendary actions this costs."""
    limited_to_form: NotRequired[Nullable[str]]
    r"""Description of form-based conditions for this action."""


class CreatureAction(BaseModel):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    name: str
    r"""Name of the item."""

    attacks: List[CreatureActionAttack]

    usage_limits: Dict[str, Any]

    desc: Optional[str] = None
    r"""Description of the game content item. Markdown."""

    action_type: OptionalNullable[ActionType] = UNSET
    r"""The type of action used.

    * `ACTION` - Action
    * `REACTION` - Reaction
    * `BONUS_ACTION` - Bonus Action
    * `LEGENDARY_ACTION` - Legendary Action
    * `LAIR_ACTION` - Lair Action
    """

    order_in_statblock: OptionalNullable[int] = UNSET
    r"""The position in the list of features that a feature appears in its source statblock"""

    legendary_action_cost: OptionalNullable[int] = UNSET
    r"""null if not legendary, else, the number of legendary actions this costs."""

    limited_to_form: OptionalNullable[str] = UNSET
    r"""Description of form-based conditions for this action."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "desc",
                "action_type",
                "order_in_statblock",
                "legendary_action_cost",
                "limited_to_form",
            ]
        )
        nullable_fields = set(
            [
                "action_type",
                "order_in_statblock",
                "legendary_action_cost",
                "limited_to_form",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
