"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .languagesummary import LanguageSummary, LanguageSummaryTypedDict
from open5e.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CreatureLanguageTypedDict(TypedDict):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    as_string: str
    data: List[LanguageSummaryTypedDict]


class CreatureLanguage(BaseModel):
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    as_string: str

    data: List[LanguageSummary]
