"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ._crossreferencelink import CrossReferenceLink, CrossReferenceLinkTypedDict
from .creatureaction import CreatureAction, CreatureActionTypedDict
from .creaturelanguage import CreatureLanguage, CreatureLanguageTypedDict
from .creatureresistancesandimmunities import (
    CreatureResistancesAndImmunities,
    CreatureResistancesAndImmunitiesTypedDict,
)
from .creaturetrait import CreatureTrait, CreatureTraitTypedDict
from .creaturetypesummary import CreatureTypeSummary, CreatureTypeSummaryTypedDict
from .documentsummary import DocumentSummary, DocumentSummaryTypedDict
from .environmentsummary import EnvironmentSummary, EnvironmentSummaryTypedDict
from .imagesummary import ImageSummary, ImageSummaryTypedDict
from .sizesummary import SizeSummary, SizeSummaryTypedDict
from open5e.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SpeedTypedDict(TypedDict):
    walk: str
    fly: str
    swim: str
    climb: str
    burrow: str
    hover: bool


class Speed(BaseModel):
    walk: str

    fly: str

    swim: str

    climb: str

    burrow: str

    hover: bool


class SpeedAllTypedDict(TypedDict):
    unit: str
    walk: int
    crawl: int
    hover: bool
    fly: Nullable[int]
    burrow: Nullable[int]
    climb: Nullable[int]
    swim: Nullable[int]


class SpeedAll(BaseModel):
    unit: str

    walk: int

    crawl: int

    hover: bool

    fly: Nullable[int]

    burrow: Nullable[int]

    climb: Nullable[int]

    swim: Nullable[int]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class AbilityScoresTypedDict(TypedDict):
    strength: int
    dexterity: int
    constitution: int
    intelligence: int
    wisdom: int
    charisma: int


class AbilityScores(BaseModel):
    strength: int

    dexterity: int

    constitution: int

    intelligence: int

    wisdom: int

    charisma: int


class ModifiersTypedDict(TypedDict):
    strength: int
    dexterity: int
    constitution: int
    intelligence: int
    wisdom: int
    charisma: int


class Modifiers(BaseModel):
    strength: int

    dexterity: int

    constitution: int

    intelligence: int

    wisdom: int

    charisma: int


class SavingThrowsTypedDict(TypedDict):
    strength: int
    dexterity: int
    constitution: int
    intelligence: int
    wisdom: int
    charisma: int


class SavingThrows(BaseModel):
    strength: int

    dexterity: int

    constitution: int

    intelligence: int

    wisdom: int

    charisma: int


class SavingThrowsAllTypedDict(TypedDict):
    strength: int
    dexterity: int
    constitution: int
    intelligence: int
    wisdom: int
    charisma: int


class SavingThrowsAll(BaseModel):
    strength: int

    dexterity: int

    constitution: int

    intelligence: int

    wisdom: int

    charisma: int


class SkillBonusesTypedDict(TypedDict):
    acrobatics: int
    animal_handling: int
    arcana: int
    athletics: int
    deception: int
    history: int
    insight: int
    intimidation: int
    investigation: int
    medicine: int
    nature: int
    perception: int
    performance: int
    persuasion: int
    religion: int
    sleight_of_hand: int
    stealth: int
    survival: int


class SkillBonuses(BaseModel):
    acrobatics: int

    animal_handling: int

    arcana: int

    athletics: int

    deception: int

    history: int

    insight: int

    intimidation: int

    investigation: int

    medicine: int

    nature: int

    perception: int

    performance: int

    persuasion: int

    religion: int

    sleight_of_hand: int

    stealth: int

    survival: int


class SkillBonusesAllTypedDict(TypedDict):
    acrobatics: int
    animal_handling: int
    arcana: int
    athletics: int
    deception: int
    history: int
    insight: int
    intimidation: int
    investigation: int
    medicine: int
    nature: int
    perception: int
    performance: int
    persuasion: int
    religion: int
    sleight_of_hand: int
    stealth: int
    survival: int


class SkillBonusesAll(BaseModel):
    acrobatics: int

    animal_handling: int

    arcana: int

    athletics: int

    deception: int

    history: int

    insight: int

    intimidation: int

    investigation: int

    medicine: int

    nature: int

    perception: int

    performance: int

    persuasion: int

    religion: int

    sleight_of_hand: int

    stealth: int

    survival: int


class CreatureCrossreferencesTypedDict(TypedDict):
    to: List[CrossReferenceLinkTypedDict]


class CreatureCrossreferences(BaseModel):
    to: List[CrossReferenceLink]


class CreatureTypedDict(TypedDict):
    r"""The serializer for the Creature object."""

    key: str
    r"""Unique key for the Item."""
    name: str
    r"""Name of the item."""
    document: DocumentSummaryTypedDict
    r"""A slimmer DocumentSerializer, designed to serialize Documents FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """
    type: CreatureTypeSummaryTypedDict
    r"""A slimmer CreatureTypeSerializer, designed to serialize CreatureType FKs on
    other serializers . Not intended to be used directly with in a ModelViewset.
    """
    size: SizeSummaryTypedDict
    r"""A slimmer SizeSerializer, designed to serialize Size FKs on other
    serializers. ie. The `size` field on the CreatureSerializer. Not intended
    to be used directly in a ModelViewset.
    """
    challenge_rating: float
    r"""Challenge Rating field as a decimal number."""
    speed: SpeedTypedDict
    speed_all: SpeedAllTypedDict
    category: str
    r"""What category this creature belongs to."""
    alignment: str
    r"""The creature's allowed alignments."""
    languages: CreatureLanguageTypedDict
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """
    experience_points: int
    ability_scores: AbilityScoresTypedDict
    modifiers: ModifiersTypedDict
    initiative_bonus: int
    saving_throws: SavingThrowsTypedDict
    saving_throws_all: SavingThrowsAllTypedDict
    skill_bonuses: SkillBonusesTypedDict
    skill_bonuses_all: SkillBonusesAllTypedDict
    resistances_and_immunities: CreatureResistancesAndImmunitiesTypedDict
    r"""This serializer formats a Creature's damage modifier as a single obj"""
    actions: List[CreatureActionTypedDict]
    traits: List[CreatureTraitTypedDict]
    creaturesets: List[str]
    environments: List[EnvironmentSummaryTypedDict]
    illustration: ImageSummaryTypedDict
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """
    crossreferences: CreatureCrossreferencesTypedDict
    proficiency_bonus: NotRequired[Nullable[int]]
    r"""The Creauture's Proficiency Bonus"""
    subcategory: NotRequired[Nullable[str]]
    r"""What subcategory this creature belongs to."""
    armor_class: NotRequired[int]
    r"""Integer representing the armor class of the object."""
    armor_detail: NotRequired[Nullable[str]]
    r"""Represents parathetical text that follows an objects AC"""
    hit_points: NotRequired[int]
    r"""Integer representing the hit points of the object."""
    hit_dice: NotRequired[Nullable[str]]
    r"""Dice string representing a way to calculate hit points."""
    passive_perception: NotRequired[int]
    r"""Integer representing the passive perception ability."""
    normal_sight_range: NotRequired[Nullable[int]]
    r"""Used to measure distance."""
    darkvision_range: NotRequired[Nullable[int]]
    r"""Used to measure distance."""
    blindsight_range: NotRequired[Nullable[int]]
    r"""Used to measure distance."""
    tremorsense_range: NotRequired[Nullable[int]]
    r"""Used to measure distance."""
    truesight_range: NotRequired[Nullable[int]]
    r"""Used to measure distance."""


class Creature(BaseModel):
    r"""The serializer for the Creature object."""

    key: str
    r"""Unique key for the Item."""

    name: str
    r"""Name of the item."""

    document: DocumentSummary
    r"""A slimmer DocumentSerializer, designed to serialize Documents FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """

    type: CreatureTypeSummary
    r"""A slimmer CreatureTypeSerializer, designed to serialize CreatureType FKs on
    other serializers . Not intended to be used directly with in a ModelViewset.
    """

    size: SizeSummary
    r"""A slimmer SizeSerializer, designed to serialize Size FKs on other
    serializers. ie. The `size` field on the CreatureSerializer. Not intended
    to be used directly in a ModelViewset.
    """

    challenge_rating: float
    r"""Challenge Rating field as a decimal number."""

    speed: Speed

    speed_all: SpeedAll

    category: str
    r"""What category this creature belongs to."""

    alignment: str
    r"""The creature's allowed alignments."""

    languages: CreatureLanguage
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    experience_points: int

    ability_scores: AbilityScores

    modifiers: Modifiers

    initiative_bonus: int

    saving_throws: SavingThrows

    saving_throws_all: SavingThrowsAll

    skill_bonuses: SkillBonuses

    skill_bonuses_all: SkillBonusesAll

    resistances_and_immunities: CreatureResistancesAndImmunities
    r"""This serializer formats a Creature's damage modifier as a single obj"""

    actions: List[CreatureAction]

    traits: List[CreatureTrait]

    creaturesets: List[str]

    environments: List[EnvironmentSummary]

    illustration: ImageSummary
    r"""Much of the logic included in the GameContentSerializer is intended to
    support manipulating data returned by the serializer via query parameters.
    """

    crossreferences: CreatureCrossreferences

    proficiency_bonus: OptionalNullable[int] = UNSET
    r"""The Creauture's Proficiency Bonus"""

    subcategory: OptionalNullable[str] = UNSET
    r"""What subcategory this creature belongs to."""

    armor_class: Optional[int] = None
    r"""Integer representing the armor class of the object."""

    armor_detail: OptionalNullable[str] = UNSET
    r"""Represents parathetical text that follows an objects AC"""

    hit_points: Optional[int] = None
    r"""Integer representing the hit points of the object."""

    hit_dice: OptionalNullable[str] = UNSET
    r"""Dice string representing a way to calculate hit points."""

    passive_perception: Optional[int] = None
    r"""Integer representing the passive perception ability."""

    normal_sight_range: OptionalNullable[int] = UNSET
    r"""Used to measure distance."""

    darkvision_range: OptionalNullable[int] = UNSET
    r"""Used to measure distance."""

    blindsight_range: OptionalNullable[int] = UNSET
    r"""Used to measure distance."""

    tremorsense_range: OptionalNullable[int] = UNSET
    r"""Used to measure distance."""

    truesight_range: OptionalNullable[int] = UNSET
    r"""Used to measure distance."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "proficiency_bonus",
                "subcategory",
                "armor_class",
                "armor_detail",
                "hit_points",
                "hit_dice",
                "passive_perception",
                "normal_sight_range",
                "darkvision_range",
                "blindsight_range",
                "tremorsense_range",
                "truesight_range",
            ]
        )
        nullable_fields = set(
            [
                "proficiency_bonus",
                "subcategory",
                "armor_detail",
                "hit_dice",
                "normal_sight_range",
                "darkvision_range",
                "blindsight_range",
                "tremorsense_range",
                "truesight_range",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
