"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import BaseModel
from typing_extensions import TypedDict


class DamageTypeSummaryTypedDict(TypedDict):
    r"""A slimmer DamageTypeSerializer, designed to serialize DamageType FKs on
    other serializers. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""
    key: str
    r"""Unique key for the Item."""


class DamageTypeSummary(BaseModel):
    r"""A slimmer DamageTypeSerializer, designed to serialize DamageType FKs on
    other serializers. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""

    key: str
    r"""Unique key for the Item."""
