"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gamesystemsummary import GameSystemSummary, GameSystemSummaryTypedDict
from .publishersummary import PublisherSummary, PublisherSummaryTypedDict
from open5e.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


DocumentSummaryType = Union[
    Literal[
        "SOURCE",
        "MISC",
    ],
    UnrecognizedStr,
]
r"""Whether this Document is a published data source, or general resources

* `SOURCE` - Source
* `MISC` - Miscellaneous
"""


class DocumentSummaryTypedDict(TypedDict):
    r"""A slimmer DocumentSerializer, designed to serialize Documents FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""
    key: str
    r"""Unique key for the Document."""
    display_name: str
    publisher: PublisherSummaryTypedDict
    r"""A slimmer PublisherSerializer, designed to serialize Publisher FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """
    gamesystem: GameSystemSummaryTypedDict
    r"""A slimmer GameSystemSerializer, designed to serialize GameSystem FKs on
    other serializers. Not intended to be used directly with in a ModelViewset.
    """
    permalink: str
    r"""Link to the document."""
    type: NotRequired[DocumentSummaryType]
    r"""Whether this Document is a published data source, or general resources

    * `SOURCE` - Source
    * `MISC` - Miscellaneous
    """


class DocumentSummary(BaseModel):
    r"""A slimmer DocumentSerializer, designed to serialize Documents FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""

    key: str
    r"""Unique key for the Document."""

    display_name: str

    publisher: PublisherSummary
    r"""A slimmer PublisherSerializer, designed to serialize Publisher FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """

    gamesystem: GameSystemSummary
    r"""A slimmer GameSystemSerializer, designed to serialize GameSystem FKs on
    other serializers. Not intended to be used directly with in a ModelViewset.
    """

    permalink: str
    r"""Link to the document."""

    type: Optional[DocumentSummaryType] = None
    r"""Whether this Document is a published data source, or general resources

    * `SOURCE` - Source
    * `MISC` - Miscellaneous
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
