"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import BaseModel
from typing_extensions import TypedDict


class PublisherSummaryTypedDict(TypedDict):
    r"""A slimmer PublisherSerializer, designed to serialize Publisher FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""
    key: str
    r"""Unique key for the publishing organization."""


class PublisherSummary(BaseModel):
    r"""A slimmer PublisherSerializer, designed to serialize Publisher FKs on other
    serializers. Not intended to be used directly with in a ModelViewset.
    """

    name: str
    r"""Name of the item."""

    key: str
    r"""Unique key for the publishing organization."""
