"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import BaseModel, UNSET_SENTINEL
from open5e.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


SpellsListDuration = Literal[
    "1 day",
    "1 hour",
    "1 hour or until triggered",
    "1 hour/caster level",
    "1 minute",
    "1 minute or 1 hour",
    "1 minute, or until expended",
    "1 minute, until expended",
    "1 round",
    "1 turn",
    "1 year",
    "10 days",
    "10 hours",
    "10 minutes",
    "10 rounds",
    "12 hours",
    "13 days",
    "1d10 hours",
    "1d4+2 rounds",
    "2 hours",
    "2 rounds",
    "2-12 hours",
    "24 hours",
    "24 hours or until the target attempts a third death saving throw",
    "3 days",
    "3 hours",
    "3 rounds",
    "30 days",
    "4 rounds",
    "5 days",
    "5 minutes",
    "5 rounds",
    "6 hours",
    "6 rounds",
    "7 days",
    "8 hours",
    "concentration + 1 round",
    "instantaneous",
    "instantaneous or special",
    "permanent",
    "permanent until discharged",
    "permanent; one generation",
    "special",
    "until cured or dispelled",
    "until destroyed",
    "until dispelled",
    "until dispelled or destroyed",
    "until dispelled or triggered",
    "up to 1 hour",
    "up to 1 minute",
    "up to 8 hours",
]
r"""Description of the duration of the effect such as \"instantaneous\" or \"1 minute\" 

* `instantaneous` - instantaneous
* `instantaneous or special` - instantaneous or special
* `1 turn` - 1 turn
* `1 round` - 1 round
* `concentration + 1 round` - concentration + 1 round
* `2 rounds` - 2 rounds
* `3 rounds` - 3 rounds
* `4 rounds` - 4 rounds
* `1d4+2 rounds` - 1d4+2 rounds
* `5 rounds` - 5 rounds
* `6 rounds` - 6 rounds
* `10 rounds` - 10 rounds
* `up to 1 minute` - up to 1 minute
* `1 minute` - 1 minute
* `1 minute, or until expended` - 1 minute, or until expended
* `1 minute, until expended` - 1 minute, until expended
* `1 minute` - 1 minute
* `5 minutes` - 5 minutes
* `10 minutes` - 10 minutes
* `1 minute or 1 hour` - 1 minute or 1 hour
* `up to 1 hour` - up to 1 hour
* `1 hour` - 1 hour
* `1 hour or until triggered` - 1 hour or until triggered
* `2 hours` - 2 hours
* `3 hours` - 3 hours
* `1d10 hours` - 1d10 hours
* `6 hours` - 6 hours
* `2-12 hours` - 2-12 hours
* `up to 8 hours` - up to 8 hours
* `8 hours` - 8 hours
* `1 hour/caster level` - 1 hour/caster level
* `10 hours` - 10 hours
* `12 hours` - 12 hours
* `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw
* `24 hours` - 24 hours
* `1 day` - 1 day
* `3 days` - 3 days
* `5 days` - 5 days
* `7 days` - 7 days
* `10 days` - 10 days
* `13 days` - 13 days
* `30 days` - 30 days
* `1 year` - 1 year
* `special` - special
* `until dispelled or destroyed` - until dispelled or destroyed
* `until destroyed` - until destroyed
* `until dispelled` - until dispelled
* `until cured or dispelled` - until cured or dispelled
* `until dispelled or triggered` - until dispelled or triggered
* `permanent until discharged` - permanent until discharged
* `permanent; one generation` - permanent; one generation
* `permanent` - permanent
"""


SpellsListCastingTime = Literal[
    "10minutes",
    "12hours",
    "1hour",
    "1minute",
    "1week",
    "24hours",
    "4hours",
    "5minutes",
    "7hours",
    "8hours",
    "9hours",
    "action",
    "bonus-action",
    "reaction",
    "round",
    "turn",
]
r"""Casting time key, such as 'action'

* `reaction` - Reaction
* `bonus-action` - 1 Bonus Action
* `action` - 1 Action
* `turn` - 1 Turn
* `round` - 1 Round
* `1minute` - 1 Minute
* `5minutes` - 5 Minutes
* `10minutes` - 10 Minutes
* `1hour` - 1 Hour
* `4hours` - 4 Hours
* `7hours` - 7 Hours
* `8hours` - 8 Hours
* `9hours` - 9 Hours
* `12hours` - 12 Hours
* `24hours` - 24 Hours
* `1week` - 1 Week
"""


class SpellsListRequestTypedDict(TypedDict):
    key_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    key_iexact: NotRequired[str]
    key: NotRequired[str]
    name_iexact: NotRequired[str]
    name: NotRequired[str]
    name_contains: NotRequired[str]
    name_icontains: NotRequired[str]
    document_key_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    document_key_iexact: NotRequired[str]
    document_key: NotRequired[str]
    document_gamesystem_key_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    document_gamesystem_key_iexact: NotRequired[str]
    document_gamesystem_key: NotRequired[str]
    classes_key_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    classes_key_iexact: NotRequired[str]
    classes_key: NotRequired[str]
    classes_name_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    level: NotRequired[int]
    level_range: NotRequired[List[int]]
    r"""Multiple values may be separated by commas."""
    level_gt: NotRequired[int]
    level_gte: NotRequired[int]
    level_lt: NotRequired[int]
    level_lte: NotRequired[int]
    range: NotRequired[int]
    range_range: NotRequired[List[int]]
    r"""Multiple values may be separated by commas."""
    range_gt: NotRequired[int]
    range_gte: NotRequired[int]
    range_lt: NotRequired[int]
    range_lte: NotRequired[int]
    school_key: NotRequired[str]
    school_name_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    school_name_iexact: NotRequired[str]
    school_name: NotRequired[str]
    duration_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    duration_iexact: NotRequired[str]
    duration: NotRequired[SpellsListDuration]
    r"""Description of the duration of the effect such as \"instantaneous\" or \"1 minute\" 

    * `instantaneous` - instantaneous
    * `instantaneous or special` - instantaneous or special
    * `1 turn` - 1 turn
    * `1 round` - 1 round
    * `concentration + 1 round` - concentration + 1 round
    * `2 rounds` - 2 rounds
    * `3 rounds` - 3 rounds
    * `4 rounds` - 4 rounds
    * `1d4+2 rounds` - 1d4+2 rounds
    * `5 rounds` - 5 rounds
    * `6 rounds` - 6 rounds
    * `10 rounds` - 10 rounds
    * `up to 1 minute` - up to 1 minute
    * `1 minute` - 1 minute
    * `1 minute, or until expended` - 1 minute, or until expended
    * `1 minute, until expended` - 1 minute, until expended
    * `1 minute` - 1 minute
    * `5 minutes` - 5 minutes
    * `10 minutes` - 10 minutes
    * `1 minute or 1 hour` - 1 minute or 1 hour
    * `up to 1 hour` - up to 1 hour
    * `1 hour` - 1 hour
    * `1 hour or until triggered` - 1 hour or until triggered
    * `2 hours` - 2 hours
    * `3 hours` - 3 hours
    * `1d10 hours` - 1d10 hours
    * `6 hours` - 6 hours
    * `2-12 hours` - 2-12 hours
    * `up to 8 hours` - up to 8 hours
    * `8 hours` - 8 hours
    * `1 hour/caster level` - 1 hour/caster level
    * `10 hours` - 10 hours
    * `12 hours` - 12 hours
    * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw
    * `24 hours` - 24 hours
    * `1 day` - 1 day
    * `3 days` - 3 days
    * `5 days` - 5 days
    * `7 days` - 7 days
    * `10 days` - 10 days
    * `13 days` - 13 days
    * `30 days` - 30 days
    * `1 year` - 1 year
    * `special` - special
    * `until dispelled or destroyed` - until dispelled or destroyed
    * `until destroyed` - until destroyed
    * `until dispelled` - until dispelled
    * `until cured or dispelled` - until cured or dispelled
    * `until dispelled or triggered` - until dispelled or triggered
    * `permanent until discharged` - permanent until discharged
    * `permanent; one generation` - permanent; one generation
    * `permanent` - permanent
    """
    concentration: NotRequired[bool]
    verbal: NotRequired[bool]
    somatic: NotRequired[bool]
    material: NotRequired[bool]
    material_consumed: NotRequired[bool]
    casting_time_in: NotRequired[List[str]]
    r"""Multiple values may be separated by commas."""
    casting_time_iexact: NotRequired[str]
    casting_time: NotRequired[SpellsListCastingTime]
    r"""Casting time key, such as 'action'

    * `reaction` - Reaction
    * `bonus-action` - 1 Bonus Action
    * `action` - 1 Action
    * `turn` - 1 Turn
    * `round` - 1 Round
    * `1minute` - 1 Minute
    * `5minutes` - 5 Minutes
    * `10minutes` - 10 Minutes
    * `1hour` - 1 Hour
    * `4hours` - 4 Hours
    * `7hours` - 7 Hours
    * `8hours` - 8 Hours
    * `9hours` - 9 Hours
    * `12hours` - 12 Hours
    * `24hours` - 24 Hours
    * `1week` - 1 Week
    """
    ordering: NotRequired[str]
    r"""Which field to use when ordering the results."""
    search: NotRequired[str]
    r"""A search term."""
    page: NotRequired[int]
    r"""A page number within the paginated result set."""
    limit: NotRequired[int]
    r"""Number of results to return per page."""


class SpellsListRequest(BaseModel):
    key_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="key__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    key_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="key__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    key: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    name_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="name__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    name: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    name_contains: Annotated[
        Optional[str],
        pydantic.Field(alias="name__contains"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    name_icontains: Annotated[
        Optional[str],
        pydantic.Field(alias="name__icontains"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    document_key_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="document__key__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    document_key_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="document__key__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    document_key: Annotated[
        Optional[str],
        pydantic.Field(alias="document__key"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    document_gamesystem_key_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="document__gamesystem__key__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    document_gamesystem_key_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="document__gamesystem__key__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    document_gamesystem_key: Annotated[
        Optional[str],
        pydantic.Field(alias="document__gamesystem__key"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    classes_key_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="classes__key__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    classes_key_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="classes__key__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    classes_key: Annotated[
        Optional[str],
        pydantic.Field(alias="classes__key"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    classes_name_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="classes__name__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    level: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    level_range: Annotated[
        Optional[List[int]],
        pydantic.Field(alias="level__range"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    level_gt: Annotated[
        Optional[int],
        pydantic.Field(alias="level__gt"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    level_gte: Annotated[
        Optional[int],
        pydantic.Field(alias="level__gte"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    level_lt: Annotated[
        Optional[int],
        pydantic.Field(alias="level__lt"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    level_lte: Annotated[
        Optional[int],
        pydantic.Field(alias="level__lte"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    range: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    range_range: Annotated[
        Optional[List[int]],
        pydantic.Field(alias="range__range"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    range_gt: Annotated[
        Optional[int],
        pydantic.Field(alias="range__gt"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    range_gte: Annotated[
        Optional[int],
        pydantic.Field(alias="range__gte"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    range_lt: Annotated[
        Optional[int],
        pydantic.Field(alias="range__lt"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    range_lte: Annotated[
        Optional[int],
        pydantic.Field(alias="range__lte"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    school_key: Annotated[
        Optional[str],
        pydantic.Field(alias="school__key"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    school_name_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="school__name__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    school_name_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="school__name__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    school_name: Annotated[
        Optional[str],
        pydantic.Field(alias="school__name"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    duration_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="duration__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    duration_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="duration__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    duration: Annotated[
        Optional[SpellsListDuration],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Description of the duration of the effect such as \"instantaneous\" or \"1 minute\" 

    * `instantaneous` - instantaneous
    * `instantaneous or special` - instantaneous or special
    * `1 turn` - 1 turn
    * `1 round` - 1 round
    * `concentration + 1 round` - concentration + 1 round
    * `2 rounds` - 2 rounds
    * `3 rounds` - 3 rounds
    * `4 rounds` - 4 rounds
    * `1d4+2 rounds` - 1d4+2 rounds
    * `5 rounds` - 5 rounds
    * `6 rounds` - 6 rounds
    * `10 rounds` - 10 rounds
    * `up to 1 minute` - up to 1 minute
    * `1 minute` - 1 minute
    * `1 minute, or until expended` - 1 minute, or until expended
    * `1 minute, until expended` - 1 minute, until expended
    * `1 minute` - 1 minute
    * `5 minutes` - 5 minutes
    * `10 minutes` - 10 minutes
    * `1 minute or 1 hour` - 1 minute or 1 hour
    * `up to 1 hour` - up to 1 hour
    * `1 hour` - 1 hour
    * `1 hour or until triggered` - 1 hour or until triggered
    * `2 hours` - 2 hours
    * `3 hours` - 3 hours
    * `1d10 hours` - 1d10 hours
    * `6 hours` - 6 hours
    * `2-12 hours` - 2-12 hours
    * `up to 8 hours` - up to 8 hours
    * `8 hours` - 8 hours
    * `1 hour/caster level` - 1 hour/caster level
    * `10 hours` - 10 hours
    * `12 hours` - 12 hours
    * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw
    * `24 hours` - 24 hours
    * `1 day` - 1 day
    * `3 days` - 3 days
    * `5 days` - 5 days
    * `7 days` - 7 days
    * `10 days` - 10 days
    * `13 days` - 13 days
    * `30 days` - 30 days
    * `1 year` - 1 year
    * `special` - special
    * `until dispelled or destroyed` - until dispelled or destroyed
    * `until destroyed` - until destroyed
    * `until dispelled` - until dispelled
    * `until cured or dispelled` - until cured or dispelled
    * `until dispelled or triggered` - until dispelled or triggered
    * `permanent until discharged` - permanent until discharged
    * `permanent; one generation` - permanent; one generation
    * `permanent` - permanent
    """

    concentration: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    verbal: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    somatic: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    material: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    material_consumed: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    casting_time_in: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="casting_time__in"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Multiple values may be separated by commas."""

    casting_time_iexact: Annotated[
        Optional[str],
        pydantic.Field(alias="casting_time__iexact"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    casting_time: Annotated[
        Optional[SpellsListCastingTime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Casting time key, such as 'action'

    * `reaction` - Reaction
    * `bonus-action` - 1 Bonus Action
    * `action` - 1 Action
    * `turn` - 1 Turn
    * `round` - 1 Round
    * `1minute` - 1 Minute
    * `5minutes` - 5 Minutes
    * `10minutes` - 10 Minutes
    * `1hour` - 1 Hour
    * `4hours` - 4 Hours
    * `7hours` - 7 Hours
    * `8hours` - 8 Hours
    * `9hours` - 9 Hours
    * `12hours` - 12 Hours
    * `24hours` - 24 Hours
    * `1week` - 1 Week
    """

    ordering: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Which field to use when ordering the results."""

    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A search term."""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A page number within the paginated result set."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Number of results to return per page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "key__in",
                "key__iexact",
                "key",
                "name__iexact",
                "name",
                "name__contains",
                "name__icontains",
                "document__key__in",
                "document__key__iexact",
                "document__key",
                "document__gamesystem__key__in",
                "document__gamesystem__key__iexact",
                "document__gamesystem__key",
                "classes__key__in",
                "classes__key__iexact",
                "classes__key",
                "classes__name__in",
                "level",
                "level__range",
                "level__gt",
                "level__gte",
                "level__lt",
                "level__lte",
                "range",
                "range__range",
                "range__gt",
                "range__gte",
                "range__lt",
                "range__lte",
                "school__key",
                "school__name__in",
                "school__name__iexact",
                "school__name",
                "duration__in",
                "duration__iexact",
                "duration",
                "concentration",
                "verbal",
                "somatic",
                "material",
                "material_consumed",
                "casting_time__in",
                "casting_time__iexact",
                "casting_time",
                "ordering",
                "search",
                "page",
                "limit",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
