"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from open5e.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import NotRequired, TypedDict


SpellCastingOptionType = Union[
    Literal[
        "default",
        "ritual",
        "player_level_1",
        "player_level_2",
        "player_level_3",
        "player_level_4",
        "player_level_5",
        "player_level_6",
        "player_level_7",
        "player_level_8",
        "player_level_9",
        "player_level_10",
        "player_level_11",
        "player_level_12",
        "player_level_13",
        "player_level_14",
        "player_level_15",
        "player_level_16",
        "player_level_17",
        "player_level_18",
        "player_level_19",
        "player_level_20",
        "slot_level_1",
        "slot_level_2",
        "slot_level_3",
        "slot_level_4",
        "slot_level_5",
        "slot_level_6",
        "slot_level_7",
        "slot_level_8",
        "slot_level_9",
    ],
    UnrecognizedStr,
]
r"""* `default` - Default
* `ritual` - Ritual
* `player_level_1` - Player Level 1
* `player_level_2` - Player Level 2
* `player_level_3` - Player Level 3
* `player_level_4` - Player Level 4
* `player_level_5` - Player Level 5
* `player_level_6` - Player Level 6
* `player_level_7` - Player Level 7
* `player_level_8` - Player Level 8
* `player_level_9` - Player Level 9
* `player_level_10` - Player Level 10
* `player_level_11` - Player Level 11
* `player_level_12` - Player Level 12
* `player_level_13` - Player Level 13
* `player_level_14` - Player Level 14
* `player_level_15` - Player Level 15
* `player_level_16` - Player Level 16
* `player_level_17` - Player Level 17
* `player_level_18` - Player Level 18
* `player_level_19` - Player Level 19
* `player_level_20` - Player Level 20
* `slot_level_1` - Spell Slot Level 1
* `slot_level_2` - Spell SlotLevel 2
* `slot_level_3` - Spell Slot Level 3
* `slot_level_4` - Spell Slot Level 4
* `slot_level_5` - Spell Slot Level 5
* `slot_level_6` - Spell Slot Level 6
* `slot_level_7` - Spell Slot Level 7
* `slot_level_8` - Spell Slot Level 8
* `slot_level_9` - Spell Slot Level 9
"""


class SpellCastingOptionTypedDict(TypedDict):
    type: SpellCastingOptionType
    r"""* `default` - Default
    * `ritual` - Ritual
    * `player_level_1` - Player Level 1
    * `player_level_2` - Player Level 2
    * `player_level_3` - Player Level 3
    * `player_level_4` - Player Level 4
    * `player_level_5` - Player Level 5
    * `player_level_6` - Player Level 6
    * `player_level_7` - Player Level 7
    * `player_level_8` - Player Level 8
    * `player_level_9` - Player Level 9
    * `player_level_10` - Player Level 10
    * `player_level_11` - Player Level 11
    * `player_level_12` - Player Level 12
    * `player_level_13` - Player Level 13
    * `player_level_14` - Player Level 14
    * `player_level_15` - Player Level 15
    * `player_level_16` - Player Level 16
    * `player_level_17` - Player Level 17
    * `player_level_18` - Player Level 18
    * `player_level_19` - Player Level 19
    * `player_level_20` - Player Level 20
    * `slot_level_1` - Spell Slot Level 1
    * `slot_level_2` - Spell SlotLevel 2
    * `slot_level_3` - Spell Slot Level 3
    * `slot_level_4` - Spell Slot Level 4
    * `slot_level_5` - Spell Slot Level 5
    * `slot_level_6` - Spell Slot Level 6
    * `slot_level_7` - Spell Slot Level 7
    * `slot_level_8` - Spell Slot Level 8
    * `slot_level_9` - Spell Slot Level 9
    """
    damage_roll: NotRequired[Nullable[str]]
    r"""The damage roll for the field in dice notation. Empty string if no roll."""
    target_count: NotRequired[Nullable[int]]
    r"""Integer representing the count of targets."""
    duration: NotRequired[Nullable[str]]
    r"""Description of the duration of the effect such as \"instantaneous\" or \"Up to 1 minute\" """
    range: NotRequired[Nullable[str]]
    r"""Description of the range of the spell."""
    concentration: NotRequired[Nullable[bool]]
    r"""Whether the effect requires concentration to be maintained."""
    shape_size: NotRequired[Nullable[int]]
    r"""Used to measure distance."""
    desc: NotRequired[Nullable[str]]
    r"""Description of complex casting option effects that cannot be captured in other fields."""


class SpellCastingOption(BaseModel):
    type: SpellCastingOptionType
    r"""* `default` - Default
    * `ritual` - Ritual
    * `player_level_1` - Player Level 1
    * `player_level_2` - Player Level 2
    * `player_level_3` - Player Level 3
    * `player_level_4` - Player Level 4
    * `player_level_5` - Player Level 5
    * `player_level_6` - Player Level 6
    * `player_level_7` - Player Level 7
    * `player_level_8` - Player Level 8
    * `player_level_9` - Player Level 9
    * `player_level_10` - Player Level 10
    * `player_level_11` - Player Level 11
    * `player_level_12` - Player Level 12
    * `player_level_13` - Player Level 13
    * `player_level_14` - Player Level 14
    * `player_level_15` - Player Level 15
    * `player_level_16` - Player Level 16
    * `player_level_17` - Player Level 17
    * `player_level_18` - Player Level 18
    * `player_level_19` - Player Level 19
    * `player_level_20` - Player Level 20
    * `slot_level_1` - Spell Slot Level 1
    * `slot_level_2` - Spell SlotLevel 2
    * `slot_level_3` - Spell Slot Level 3
    * `slot_level_4` - Spell Slot Level 4
    * `slot_level_5` - Spell Slot Level 5
    * `slot_level_6` - Spell Slot Level 6
    * `slot_level_7` - Spell Slot Level 7
    * `slot_level_8` - Spell Slot Level 8
    * `slot_level_9` - Spell Slot Level 9
    """

    damage_roll: OptionalNullable[str] = UNSET
    r"""The damage roll for the field in dice notation. Empty string if no roll."""

    target_count: OptionalNullable[int] = UNSET
    r"""Integer representing the count of targets."""

    duration: OptionalNullable[str] = UNSET
    r"""Description of the duration of the effect such as \"instantaneous\" or \"Up to 1 minute\" """

    range: OptionalNullable[str] = UNSET
    r"""Description of the range of the spell."""

    concentration: OptionalNullable[bool] = UNSET
    r"""Whether the effect requires concentration to be maintained."""

    shape_size: OptionalNullable[int] = UNSET
    r"""Used to measure distance."""

    desc: OptionalNullable[str] = UNSET
    r"""Description of complex casting option effects that cannot be captured in other fields."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "damage_roll",
                "target_count",
                "duration",
                "range",
                "concentration",
                "shape_size",
                "desc",
            ]
        )
        nullable_fields = set(
            [
                "damage_roll",
                "target_count",
                "duration",
                "range",
                "concentration",
                "shape_size",
                "desc",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
