"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from open5e import errors, models, utils
from open5e._hooks import HookContext
from open5e.types import OptionalNullable, UNSET
from open5e.utils.unmarshal_json_response import unmarshal_json_response
from typing import Iterable, List, Mapping, Optional


class Creatures(BaseSDK):
    def list(
        self,
        *,
        key_in: Optional[Iterable[str]] = None,
        key_iexact: Optional[str] = None,
        key: Optional[str] = None,
        name_iexact: Optional[str] = None,
        name: Optional[str] = None,
        name_icontains: Optional[str] = None,
        document_key_in: Optional[Iterable[str]] = None,
        document_key_iexact: Optional[str] = None,
        document_key: Optional[str] = None,
        document_gamesystem_key_in: Optional[Iterable[str]] = None,
        document_gamesystem_key_iexact: Optional[str] = None,
        document_gamesystem_key: Optional[str] = None,
        size: Optional[str] = None,
        category: Optional[str] = None,
        category_iexact: Optional[str] = None,
        subcategory: Optional[str] = None,
        subcategory_iexact: Optional[str] = None,
        type_: Optional[str] = None,
        challenge_rating: Optional[float] = None,
        challenge_rating_lt: Optional[float] = None,
        challenge_rating_lte: Optional[float] = None,
        challenge_rating_gt: Optional[float] = None,
        challenge_rating_gte: Optional[float] = None,
        armor_class: Optional[int] = None,
        armor_class_lt: Optional[int] = None,
        armor_class_lte: Optional[int] = None,
        armor_class_gt: Optional[int] = None,
        armor_class_gte: Optional[int] = None,
        ability_score_strength: Optional[int] = None,
        ability_score_strength_lt: Optional[int] = None,
        ability_score_strength_lte: Optional[int] = None,
        ability_score_strength_gt: Optional[int] = None,
        ability_score_strength_gte: Optional[int] = None,
        ability_score_dexterity: Optional[int] = None,
        ability_score_dexterity_lt: Optional[int] = None,
        ability_score_dexterity_lte: Optional[int] = None,
        ability_score_dexterity_gt: Optional[int] = None,
        ability_score_dexterity_gte: Optional[int] = None,
        ability_score_constitution: Optional[int] = None,
        ability_score_constitution_lt: Optional[int] = None,
        ability_score_constitution_lte: Optional[int] = None,
        ability_score_constitution_gt: Optional[int] = None,
        ability_score_constitution_gte: Optional[int] = None,
        ability_score_intelligence: Optional[int] = None,
        ability_score_intelligence_lt: Optional[int] = None,
        ability_score_intelligence_lte: Optional[int] = None,
        ability_score_intelligence_gt: Optional[int] = None,
        ability_score_intelligence_gte: Optional[int] = None,
        ability_score_wisdom: Optional[int] = None,
        ability_score_wisdom_lt: Optional[int] = None,
        ability_score_wisdom_lte: Optional[int] = None,
        ability_score_wisdom_gt: Optional[int] = None,
        ability_score_wisdom_gte: Optional[int] = None,
        ability_score_charisma: Optional[int] = None,
        ability_score_charisma_lt: Optional[int] = None,
        ability_score_charisma_lte: Optional[int] = None,
        ability_score_charisma_gt: Optional[int] = None,
        ability_score_charisma_gte: Optional[int] = None,
        saving_throw_strength_isnull: Optional[bool] = None,
        saving_throw_dexterity_isnull: Optional[bool] = None,
        saving_throw_constitution_isnull: Optional[bool] = None,
        saving_throw_intelligence_isnull: Optional[bool] = None,
        saving_throw_wisdom_isnull: Optional[bool] = None,
        saving_throw_charisma_isnull: Optional[bool] = None,
        skill_bonus_acrobatics_isnull: Optional[bool] = None,
        skill_bonus_animal_handling_isnull: Optional[bool] = None,
        skill_bonus_arcana_isnull: Optional[bool] = None,
        skill_bonus_athletics_isnull: Optional[bool] = None,
        skill_bonus_deception_isnull: Optional[bool] = None,
        skill_bonus_history_isnull: Optional[bool] = None,
        skill_bonus_insight_isnull: Optional[bool] = None,
        skill_bonus_intimidation_isnull: Optional[bool] = None,
        skill_bonus_investigation_isnull: Optional[bool] = None,
        skill_bonus_medicine_isnull: Optional[bool] = None,
        skill_bonus_nature_isnull: Optional[bool] = None,
        skill_bonus_perception_isnull: Optional[bool] = None,
        skill_bonus_performance_isnull: Optional[bool] = None,
        skill_bonus_persuasion_isnull: Optional[bool] = None,
        skill_bonus_religion_isnull: Optional[bool] = None,
        skill_bonus_sleight_of_hand_isnull: Optional[bool] = None,
        skill_bonus_stealth_isnull: Optional[bool] = None,
        skill_bonus_survival_isnull: Optional[bool] = None,
        passive_perception: Optional[int] = None,
        passive_perception_lt: Optional[int] = None,
        passive_perception_lte: Optional[int] = None,
        passive_perception_gt: Optional[int] = None,
        passive_perception_gte: Optional[int] = None,
        ordering: Optional[str] = None,
        search: Optional[str] = None,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PaginatedCreatureList:
        r"""list: API endpoint for returning a list of creatures.
        retrieve: API endpoint for returning a particular creature.

        :param key_in: Multiple values may be separated by commas.
        :param key_iexact:
        :param key:
        :param name_iexact:
        :param name:
        :param name_icontains:
        :param document_key_in: Multiple values may be separated by commas.
        :param document_key_iexact:
        :param document_key:
        :param document_gamesystem_key_in: Multiple values may be separated by commas.
        :param document_gamesystem_key_iexact:
        :param document_gamesystem_key:
        :param size: Unique key for the Item.
        :param category:
        :param category_iexact:
        :param subcategory:
        :param subcategory_iexact:
        :param type: Unique key for the Item.
        :param challenge_rating:
        :param challenge_rating_lt:
        :param challenge_rating_lte:
        :param challenge_rating_gt:
        :param challenge_rating_gte:
        :param armor_class:
        :param armor_class_lt:
        :param armor_class_lte:
        :param armor_class_gt:
        :param armor_class_gte:
        :param ability_score_strength:
        :param ability_score_strength_lt:
        :param ability_score_strength_lte:
        :param ability_score_strength_gt:
        :param ability_score_strength_gte:
        :param ability_score_dexterity:
        :param ability_score_dexterity_lt:
        :param ability_score_dexterity_lte:
        :param ability_score_dexterity_gt:
        :param ability_score_dexterity_gte:
        :param ability_score_constitution:
        :param ability_score_constitution_lt:
        :param ability_score_constitution_lte:
        :param ability_score_constitution_gt:
        :param ability_score_constitution_gte:
        :param ability_score_intelligence:
        :param ability_score_intelligence_lt:
        :param ability_score_intelligence_lte:
        :param ability_score_intelligence_gt:
        :param ability_score_intelligence_gte:
        :param ability_score_wisdom:
        :param ability_score_wisdom_lt:
        :param ability_score_wisdom_lte:
        :param ability_score_wisdom_gt:
        :param ability_score_wisdom_gte:
        :param ability_score_charisma:
        :param ability_score_charisma_lt:
        :param ability_score_charisma_lte:
        :param ability_score_charisma_gt:
        :param ability_score_charisma_gte:
        :param saving_throw_strength_isnull:
        :param saving_throw_dexterity_isnull:
        :param saving_throw_constitution_isnull:
        :param saving_throw_intelligence_isnull:
        :param saving_throw_wisdom_isnull:
        :param saving_throw_charisma_isnull:
        :param skill_bonus_acrobatics_isnull:
        :param skill_bonus_animal_handling_isnull:
        :param skill_bonus_arcana_isnull:
        :param skill_bonus_athletics_isnull:
        :param skill_bonus_deception_isnull:
        :param skill_bonus_history_isnull:
        :param skill_bonus_insight_isnull:
        :param skill_bonus_intimidation_isnull:
        :param skill_bonus_investigation_isnull:
        :param skill_bonus_medicine_isnull:
        :param skill_bonus_nature_isnull:
        :param skill_bonus_perception_isnull:
        :param skill_bonus_performance_isnull:
        :param skill_bonus_persuasion_isnull:
        :param skill_bonus_religion_isnull:
        :param skill_bonus_sleight_of_hand_isnull:
        :param skill_bonus_stealth_isnull:
        :param skill_bonus_survival_isnull:
        :param passive_perception:
        :param passive_perception_lt:
        :param passive_perception_lte:
        :param passive_perception_gt:
        :param passive_perception_gte:
        :param ordering: Which field to use when ordering the results.
        :param search: A search term.
        :param page: A page number within the paginated result set.
        :param limit: Number of results to return per page.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreaturesListRequest(
            key_in=utils.unmarshal(key_in, Optional[List[str]]),
            key_iexact=key_iexact,
            key=key,
            name_iexact=name_iexact,
            name=name,
            name_icontains=name_icontains,
            document_key_in=utils.unmarshal(document_key_in, Optional[List[str]]),
            document_key_iexact=document_key_iexact,
            document_key=document_key,
            document_gamesystem_key_in=utils.unmarshal(
                document_gamesystem_key_in, Optional[List[str]]
            ),
            document_gamesystem_key_iexact=document_gamesystem_key_iexact,
            document_gamesystem_key=document_gamesystem_key,
            size=size,
            category=category,
            category_iexact=category_iexact,
            subcategory=subcategory,
            subcategory_iexact=subcategory_iexact,
            type=type_,
            challenge_rating=challenge_rating,
            challenge_rating_lt=challenge_rating_lt,
            challenge_rating_lte=challenge_rating_lte,
            challenge_rating_gt=challenge_rating_gt,
            challenge_rating_gte=challenge_rating_gte,
            armor_class=armor_class,
            armor_class_lt=armor_class_lt,
            armor_class_lte=armor_class_lte,
            armor_class_gt=armor_class_gt,
            armor_class_gte=armor_class_gte,
            ability_score_strength=ability_score_strength,
            ability_score_strength_lt=ability_score_strength_lt,
            ability_score_strength_lte=ability_score_strength_lte,
            ability_score_strength_gt=ability_score_strength_gt,
            ability_score_strength_gte=ability_score_strength_gte,
            ability_score_dexterity=ability_score_dexterity,
            ability_score_dexterity_lt=ability_score_dexterity_lt,
            ability_score_dexterity_lte=ability_score_dexterity_lte,
            ability_score_dexterity_gt=ability_score_dexterity_gt,
            ability_score_dexterity_gte=ability_score_dexterity_gte,
            ability_score_constitution=ability_score_constitution,
            ability_score_constitution_lt=ability_score_constitution_lt,
            ability_score_constitution_lte=ability_score_constitution_lte,
            ability_score_constitution_gt=ability_score_constitution_gt,
            ability_score_constitution_gte=ability_score_constitution_gte,
            ability_score_intelligence=ability_score_intelligence,
            ability_score_intelligence_lt=ability_score_intelligence_lt,
            ability_score_intelligence_lte=ability_score_intelligence_lte,
            ability_score_intelligence_gt=ability_score_intelligence_gt,
            ability_score_intelligence_gte=ability_score_intelligence_gte,
            ability_score_wisdom=ability_score_wisdom,
            ability_score_wisdom_lt=ability_score_wisdom_lt,
            ability_score_wisdom_lte=ability_score_wisdom_lte,
            ability_score_wisdom_gt=ability_score_wisdom_gt,
            ability_score_wisdom_gte=ability_score_wisdom_gte,
            ability_score_charisma=ability_score_charisma,
            ability_score_charisma_lt=ability_score_charisma_lt,
            ability_score_charisma_lte=ability_score_charisma_lte,
            ability_score_charisma_gt=ability_score_charisma_gt,
            ability_score_charisma_gte=ability_score_charisma_gte,
            saving_throw_strength_isnull=saving_throw_strength_isnull,
            saving_throw_dexterity_isnull=saving_throw_dexterity_isnull,
            saving_throw_constitution_isnull=saving_throw_constitution_isnull,
            saving_throw_intelligence_isnull=saving_throw_intelligence_isnull,
            saving_throw_wisdom_isnull=saving_throw_wisdom_isnull,
            saving_throw_charisma_isnull=saving_throw_charisma_isnull,
            skill_bonus_acrobatics_isnull=skill_bonus_acrobatics_isnull,
            skill_bonus_animal_handling_isnull=skill_bonus_animal_handling_isnull,
            skill_bonus_arcana_isnull=skill_bonus_arcana_isnull,
            skill_bonus_athletics_isnull=skill_bonus_athletics_isnull,
            skill_bonus_deception_isnull=skill_bonus_deception_isnull,
            skill_bonus_history_isnull=skill_bonus_history_isnull,
            skill_bonus_insight_isnull=skill_bonus_insight_isnull,
            skill_bonus_intimidation_isnull=skill_bonus_intimidation_isnull,
            skill_bonus_investigation_isnull=skill_bonus_investigation_isnull,
            skill_bonus_medicine_isnull=skill_bonus_medicine_isnull,
            skill_bonus_nature_isnull=skill_bonus_nature_isnull,
            skill_bonus_perception_isnull=skill_bonus_perception_isnull,
            skill_bonus_performance_isnull=skill_bonus_performance_isnull,
            skill_bonus_persuasion_isnull=skill_bonus_persuasion_isnull,
            skill_bonus_religion_isnull=skill_bonus_religion_isnull,
            skill_bonus_sleight_of_hand_isnull=skill_bonus_sleight_of_hand_isnull,
            skill_bonus_stealth_isnull=skill_bonus_stealth_isnull,
            skill_bonus_survival_isnull=skill_bonus_survival_isnull,
            passive_perception=passive_perception,
            passive_perception_lt=passive_perception_lt,
            passive_perception_lte=passive_perception_lte,
            passive_perception_gt=passive_perception_gt,
            passive_perception_gte=passive_perception_gte,
            ordering=ordering,
            search=search,
            page=page,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/v2/creatures/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="creatures_list",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PaginatedCreatureList, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )

    async def list_async(
        self,
        *,
        key_in: Optional[Iterable[str]] = None,
        key_iexact: Optional[str] = None,
        key: Optional[str] = None,
        name_iexact: Optional[str] = None,
        name: Optional[str] = None,
        name_icontains: Optional[str] = None,
        document_key_in: Optional[Iterable[str]] = None,
        document_key_iexact: Optional[str] = None,
        document_key: Optional[str] = None,
        document_gamesystem_key_in: Optional[Iterable[str]] = None,
        document_gamesystem_key_iexact: Optional[str] = None,
        document_gamesystem_key: Optional[str] = None,
        size: Optional[str] = None,
        category: Optional[str] = None,
        category_iexact: Optional[str] = None,
        subcategory: Optional[str] = None,
        subcategory_iexact: Optional[str] = None,
        type_: Optional[str] = None,
        challenge_rating: Optional[float] = None,
        challenge_rating_lt: Optional[float] = None,
        challenge_rating_lte: Optional[float] = None,
        challenge_rating_gt: Optional[float] = None,
        challenge_rating_gte: Optional[float] = None,
        armor_class: Optional[int] = None,
        armor_class_lt: Optional[int] = None,
        armor_class_lte: Optional[int] = None,
        armor_class_gt: Optional[int] = None,
        armor_class_gte: Optional[int] = None,
        ability_score_strength: Optional[int] = None,
        ability_score_strength_lt: Optional[int] = None,
        ability_score_strength_lte: Optional[int] = None,
        ability_score_strength_gt: Optional[int] = None,
        ability_score_strength_gte: Optional[int] = None,
        ability_score_dexterity: Optional[int] = None,
        ability_score_dexterity_lt: Optional[int] = None,
        ability_score_dexterity_lte: Optional[int] = None,
        ability_score_dexterity_gt: Optional[int] = None,
        ability_score_dexterity_gte: Optional[int] = None,
        ability_score_constitution: Optional[int] = None,
        ability_score_constitution_lt: Optional[int] = None,
        ability_score_constitution_lte: Optional[int] = None,
        ability_score_constitution_gt: Optional[int] = None,
        ability_score_constitution_gte: Optional[int] = None,
        ability_score_intelligence: Optional[int] = None,
        ability_score_intelligence_lt: Optional[int] = None,
        ability_score_intelligence_lte: Optional[int] = None,
        ability_score_intelligence_gt: Optional[int] = None,
        ability_score_intelligence_gte: Optional[int] = None,
        ability_score_wisdom: Optional[int] = None,
        ability_score_wisdom_lt: Optional[int] = None,
        ability_score_wisdom_lte: Optional[int] = None,
        ability_score_wisdom_gt: Optional[int] = None,
        ability_score_wisdom_gte: Optional[int] = None,
        ability_score_charisma: Optional[int] = None,
        ability_score_charisma_lt: Optional[int] = None,
        ability_score_charisma_lte: Optional[int] = None,
        ability_score_charisma_gt: Optional[int] = None,
        ability_score_charisma_gte: Optional[int] = None,
        saving_throw_strength_isnull: Optional[bool] = None,
        saving_throw_dexterity_isnull: Optional[bool] = None,
        saving_throw_constitution_isnull: Optional[bool] = None,
        saving_throw_intelligence_isnull: Optional[bool] = None,
        saving_throw_wisdom_isnull: Optional[bool] = None,
        saving_throw_charisma_isnull: Optional[bool] = None,
        skill_bonus_acrobatics_isnull: Optional[bool] = None,
        skill_bonus_animal_handling_isnull: Optional[bool] = None,
        skill_bonus_arcana_isnull: Optional[bool] = None,
        skill_bonus_athletics_isnull: Optional[bool] = None,
        skill_bonus_deception_isnull: Optional[bool] = None,
        skill_bonus_history_isnull: Optional[bool] = None,
        skill_bonus_insight_isnull: Optional[bool] = None,
        skill_bonus_intimidation_isnull: Optional[bool] = None,
        skill_bonus_investigation_isnull: Optional[bool] = None,
        skill_bonus_medicine_isnull: Optional[bool] = None,
        skill_bonus_nature_isnull: Optional[bool] = None,
        skill_bonus_perception_isnull: Optional[bool] = None,
        skill_bonus_performance_isnull: Optional[bool] = None,
        skill_bonus_persuasion_isnull: Optional[bool] = None,
        skill_bonus_religion_isnull: Optional[bool] = None,
        skill_bonus_sleight_of_hand_isnull: Optional[bool] = None,
        skill_bonus_stealth_isnull: Optional[bool] = None,
        skill_bonus_survival_isnull: Optional[bool] = None,
        passive_perception: Optional[int] = None,
        passive_perception_lt: Optional[int] = None,
        passive_perception_lte: Optional[int] = None,
        passive_perception_gt: Optional[int] = None,
        passive_perception_gte: Optional[int] = None,
        ordering: Optional[str] = None,
        search: Optional[str] = None,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PaginatedCreatureList:
        r"""list: API endpoint for returning a list of creatures.
        retrieve: API endpoint for returning a particular creature.

        :param key_in: Multiple values may be separated by commas.
        :param key_iexact:
        :param key:
        :param name_iexact:
        :param name:
        :param name_icontains:
        :param document_key_in: Multiple values may be separated by commas.
        :param document_key_iexact:
        :param document_key:
        :param document_gamesystem_key_in: Multiple values may be separated by commas.
        :param document_gamesystem_key_iexact:
        :param document_gamesystem_key:
        :param size: Unique key for the Item.
        :param category:
        :param category_iexact:
        :param subcategory:
        :param subcategory_iexact:
        :param type: Unique key for the Item.
        :param challenge_rating:
        :param challenge_rating_lt:
        :param challenge_rating_lte:
        :param challenge_rating_gt:
        :param challenge_rating_gte:
        :param armor_class:
        :param armor_class_lt:
        :param armor_class_lte:
        :param armor_class_gt:
        :param armor_class_gte:
        :param ability_score_strength:
        :param ability_score_strength_lt:
        :param ability_score_strength_lte:
        :param ability_score_strength_gt:
        :param ability_score_strength_gte:
        :param ability_score_dexterity:
        :param ability_score_dexterity_lt:
        :param ability_score_dexterity_lte:
        :param ability_score_dexterity_gt:
        :param ability_score_dexterity_gte:
        :param ability_score_constitution:
        :param ability_score_constitution_lt:
        :param ability_score_constitution_lte:
        :param ability_score_constitution_gt:
        :param ability_score_constitution_gte:
        :param ability_score_intelligence:
        :param ability_score_intelligence_lt:
        :param ability_score_intelligence_lte:
        :param ability_score_intelligence_gt:
        :param ability_score_intelligence_gte:
        :param ability_score_wisdom:
        :param ability_score_wisdom_lt:
        :param ability_score_wisdom_lte:
        :param ability_score_wisdom_gt:
        :param ability_score_wisdom_gte:
        :param ability_score_charisma:
        :param ability_score_charisma_lt:
        :param ability_score_charisma_lte:
        :param ability_score_charisma_gt:
        :param ability_score_charisma_gte:
        :param saving_throw_strength_isnull:
        :param saving_throw_dexterity_isnull:
        :param saving_throw_constitution_isnull:
        :param saving_throw_intelligence_isnull:
        :param saving_throw_wisdom_isnull:
        :param saving_throw_charisma_isnull:
        :param skill_bonus_acrobatics_isnull:
        :param skill_bonus_animal_handling_isnull:
        :param skill_bonus_arcana_isnull:
        :param skill_bonus_athletics_isnull:
        :param skill_bonus_deception_isnull:
        :param skill_bonus_history_isnull:
        :param skill_bonus_insight_isnull:
        :param skill_bonus_intimidation_isnull:
        :param skill_bonus_investigation_isnull:
        :param skill_bonus_medicine_isnull:
        :param skill_bonus_nature_isnull:
        :param skill_bonus_perception_isnull:
        :param skill_bonus_performance_isnull:
        :param skill_bonus_persuasion_isnull:
        :param skill_bonus_religion_isnull:
        :param skill_bonus_sleight_of_hand_isnull:
        :param skill_bonus_stealth_isnull:
        :param skill_bonus_survival_isnull:
        :param passive_perception:
        :param passive_perception_lt:
        :param passive_perception_lte:
        :param passive_perception_gt:
        :param passive_perception_gte:
        :param ordering: Which field to use when ordering the results.
        :param search: A search term.
        :param page: A page number within the paginated result set.
        :param limit: Number of results to return per page.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreaturesListRequest(
            key_in=utils.unmarshal(key_in, Optional[List[str]]),
            key_iexact=key_iexact,
            key=key,
            name_iexact=name_iexact,
            name=name,
            name_icontains=name_icontains,
            document_key_in=utils.unmarshal(document_key_in, Optional[List[str]]),
            document_key_iexact=document_key_iexact,
            document_key=document_key,
            document_gamesystem_key_in=utils.unmarshal(
                document_gamesystem_key_in, Optional[List[str]]
            ),
            document_gamesystem_key_iexact=document_gamesystem_key_iexact,
            document_gamesystem_key=document_gamesystem_key,
            size=size,
            category=category,
            category_iexact=category_iexact,
            subcategory=subcategory,
            subcategory_iexact=subcategory_iexact,
            type=type_,
            challenge_rating=challenge_rating,
            challenge_rating_lt=challenge_rating_lt,
            challenge_rating_lte=challenge_rating_lte,
            challenge_rating_gt=challenge_rating_gt,
            challenge_rating_gte=challenge_rating_gte,
            armor_class=armor_class,
            armor_class_lt=armor_class_lt,
            armor_class_lte=armor_class_lte,
            armor_class_gt=armor_class_gt,
            armor_class_gte=armor_class_gte,
            ability_score_strength=ability_score_strength,
            ability_score_strength_lt=ability_score_strength_lt,
            ability_score_strength_lte=ability_score_strength_lte,
            ability_score_strength_gt=ability_score_strength_gt,
            ability_score_strength_gte=ability_score_strength_gte,
            ability_score_dexterity=ability_score_dexterity,
            ability_score_dexterity_lt=ability_score_dexterity_lt,
            ability_score_dexterity_lte=ability_score_dexterity_lte,
            ability_score_dexterity_gt=ability_score_dexterity_gt,
            ability_score_dexterity_gte=ability_score_dexterity_gte,
            ability_score_constitution=ability_score_constitution,
            ability_score_constitution_lt=ability_score_constitution_lt,
            ability_score_constitution_lte=ability_score_constitution_lte,
            ability_score_constitution_gt=ability_score_constitution_gt,
            ability_score_constitution_gte=ability_score_constitution_gte,
            ability_score_intelligence=ability_score_intelligence,
            ability_score_intelligence_lt=ability_score_intelligence_lt,
            ability_score_intelligence_lte=ability_score_intelligence_lte,
            ability_score_intelligence_gt=ability_score_intelligence_gt,
            ability_score_intelligence_gte=ability_score_intelligence_gte,
            ability_score_wisdom=ability_score_wisdom,
            ability_score_wisdom_lt=ability_score_wisdom_lt,
            ability_score_wisdom_lte=ability_score_wisdom_lte,
            ability_score_wisdom_gt=ability_score_wisdom_gt,
            ability_score_wisdom_gte=ability_score_wisdom_gte,
            ability_score_charisma=ability_score_charisma,
            ability_score_charisma_lt=ability_score_charisma_lt,
            ability_score_charisma_lte=ability_score_charisma_lte,
            ability_score_charisma_gt=ability_score_charisma_gt,
            ability_score_charisma_gte=ability_score_charisma_gte,
            saving_throw_strength_isnull=saving_throw_strength_isnull,
            saving_throw_dexterity_isnull=saving_throw_dexterity_isnull,
            saving_throw_constitution_isnull=saving_throw_constitution_isnull,
            saving_throw_intelligence_isnull=saving_throw_intelligence_isnull,
            saving_throw_wisdom_isnull=saving_throw_wisdom_isnull,
            saving_throw_charisma_isnull=saving_throw_charisma_isnull,
            skill_bonus_acrobatics_isnull=skill_bonus_acrobatics_isnull,
            skill_bonus_animal_handling_isnull=skill_bonus_animal_handling_isnull,
            skill_bonus_arcana_isnull=skill_bonus_arcana_isnull,
            skill_bonus_athletics_isnull=skill_bonus_athletics_isnull,
            skill_bonus_deception_isnull=skill_bonus_deception_isnull,
            skill_bonus_history_isnull=skill_bonus_history_isnull,
            skill_bonus_insight_isnull=skill_bonus_insight_isnull,
            skill_bonus_intimidation_isnull=skill_bonus_intimidation_isnull,
            skill_bonus_investigation_isnull=skill_bonus_investigation_isnull,
            skill_bonus_medicine_isnull=skill_bonus_medicine_isnull,
            skill_bonus_nature_isnull=skill_bonus_nature_isnull,
            skill_bonus_perception_isnull=skill_bonus_perception_isnull,
            skill_bonus_performance_isnull=skill_bonus_performance_isnull,
            skill_bonus_persuasion_isnull=skill_bonus_persuasion_isnull,
            skill_bonus_religion_isnull=skill_bonus_religion_isnull,
            skill_bonus_sleight_of_hand_isnull=skill_bonus_sleight_of_hand_isnull,
            skill_bonus_stealth_isnull=skill_bonus_stealth_isnull,
            skill_bonus_survival_isnull=skill_bonus_survival_isnull,
            passive_perception=passive_perception,
            passive_perception_lt=passive_perception_lt,
            passive_perception_lte=passive_perception_lte,
            passive_perception_gt=passive_perception_gt,
            passive_perception_gte=passive_perception_gte,
            ordering=ordering,
            search=search,
            page=page,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/creatures/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="creatures_list",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PaginatedCreatureList, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )

    def get(
        self,
        *,
        key: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Creature:
        r"""list: API endpoint for returning a list of creatures.
        retrieve: API endpoint for returning a particular creature.

        :param key:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreaturesRetrieveRequest(
            key=key,
        )

        req = self._build_request(
            method="GET",
            path="/v2/creatures/{key}/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="creatures_retrieve",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Creature, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )

    async def get_async(
        self,
        *,
        key: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Creature:
        r"""list: API endpoint for returning a list of creatures.
        retrieve: API endpoint for returning a particular creature.

        :param key:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreaturesRetrieveRequest(
            key=key,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/creatures/{key}/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="creatures_retrieve",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Creature, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )
