"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from open5e import errors, models, utils
from open5e._hooks import HookContext
from open5e.types import OptionalNullable, UNSET
from open5e.utils.unmarshal_json_response import unmarshal_json_response
from typing import Iterable, List, Mapping, Optional


class Spells(BaseSDK):
    def list(
        self,
        *,
        key_in: Optional[Iterable[str]] = None,
        key_iexact: Optional[str] = None,
        key: Optional[str] = None,
        name_iexact: Optional[str] = None,
        name: Optional[str] = None,
        name_contains: Optional[str] = None,
        name_icontains: Optional[str] = None,
        document_key_in: Optional[Iterable[str]] = None,
        document_key_iexact: Optional[str] = None,
        document_key: Optional[str] = None,
        document_gamesystem_key_in: Optional[Iterable[str]] = None,
        document_gamesystem_key_iexact: Optional[str] = None,
        document_gamesystem_key: Optional[str] = None,
        classes_key_in: Optional[Iterable[str]] = None,
        classes_key_iexact: Optional[str] = None,
        classes_key: Optional[str] = None,
        classes_name_in: Optional[Iterable[str]] = None,
        level: Optional[int] = None,
        level_range: Optional[Iterable[int]] = None,
        level_gt: Optional[int] = None,
        level_gte: Optional[int] = None,
        level_lt: Optional[int] = None,
        level_lte: Optional[int] = None,
        range: Optional[int] = None,
        range_range: Optional[Iterable[int]] = None,
        range_gt: Optional[int] = None,
        range_gte: Optional[int] = None,
        range_lt: Optional[int] = None,
        range_lte: Optional[int] = None,
        school_key: Optional[str] = None,
        school_name_in: Optional[Iterable[str]] = None,
        school_name_iexact: Optional[str] = None,
        school_name: Optional[str] = None,
        duration_in: Optional[Iterable[str]] = None,
        duration_iexact: Optional[str] = None,
        duration: Optional[models.SpellsListDuration] = None,
        concentration: Optional[bool] = None,
        verbal: Optional[bool] = None,
        somatic: Optional[bool] = None,
        material: Optional[bool] = None,
        material_consumed: Optional[bool] = None,
        casting_time_in: Optional[Iterable[str]] = None,
        casting_time_iexact: Optional[str] = None,
        casting_time: Optional[models.SpellsListCastingTime] = None,
        ordering: Optional[str] = None,
        search: Optional[str] = None,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PaginatedSpellList:
        r"""list: API endpoint for returning a list of spells.
        retrieve: API endpoint for returning a particular spell.

        :param key_in: Multiple values may be separated by commas.
        :param key_iexact:
        :param key:
        :param name_iexact:
        :param name:
        :param name_contains:
        :param name_icontains:
        :param document_key_in: Multiple values may be separated by commas.
        :param document_key_iexact:
        :param document_key:
        :param document_gamesystem_key_in: Multiple values may be separated by commas.
        :param document_gamesystem_key_iexact:
        :param document_gamesystem_key:
        :param classes_key_in: Multiple values may be separated by commas.
        :param classes_key_iexact:
        :param classes_key:
        :param classes_name_in: Multiple values may be separated by commas.
        :param level:
        :param level_range: Multiple values may be separated by commas.
        :param level_gt:
        :param level_gte:
        :param level_lt:
        :param level_lte:
        :param range:
        :param range_range: Multiple values may be separated by commas.
        :param range_gt:
        :param range_gte:
        :param range_lt:
        :param range_lte:
        :param school_key:
        :param school_name_in: Multiple values may be separated by commas.
        :param school_name_iexact:
        :param school_name:
        :param duration_in: Multiple values may be separated by commas.
        :param duration_iexact:
        :param duration: Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"

            * `instantaneous` - instantaneous
            * `instantaneous or special` - instantaneous or special
            * `1 turn` - 1 turn
            * `1 round` - 1 round
            * `concentration + 1 round` - concentration + 1 round
            * `2 rounds` - 2 rounds
            * `3 rounds` - 3 rounds
            * `4 rounds` - 4 rounds
            * `1d4+2 rounds` - 1d4+2 rounds
            * `5 rounds` - 5 rounds
            * `6 rounds` - 6 rounds
            * `10 rounds` - 10 rounds
            * `up to 1 minute` - up to 1 minute
            * `1 minute` - 1 minute
            * `1 minute, or until expended` - 1 minute, or until expended
            * `1 minute, until expended` - 1 minute, until expended
            * `1 minute` - 1 minute
            * `5 minutes` - 5 minutes
            * `10 minutes` - 10 minutes
            * `1 minute or 1 hour` - 1 minute or 1 hour
            * `up to 1 hour` - up to 1 hour
            * `1 hour` - 1 hour
            * `1 hour or until triggered` - 1 hour or until triggered
            * `2 hours` - 2 hours
            * `3 hours` - 3 hours
            * `1d10 hours` - 1d10 hours
            * `6 hours` - 6 hours
            * `2-12 hours` - 2-12 hours
            * `up to 8 hours` - up to 8 hours
            * `8 hours` - 8 hours
            * `1 hour/caster level` - 1 hour/caster level
            * `10 hours` - 10 hours
            * `12 hours` - 12 hours
            * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw
            * `24 hours` - 24 hours
            * `1 day` - 1 day
            * `3 days` - 3 days
            * `5 days` - 5 days
            * `7 days` - 7 days
            * `10 days` - 10 days
            * `13 days` - 13 days
            * `30 days` - 30 days
            * `1 year` - 1 year
            * `special` - special
            * `until dispelled or destroyed` - until dispelled or destroyed
            * `until destroyed` - until destroyed
            * `until dispelled` - until dispelled
            * `until cured or dispelled` - until cured or dispelled
            * `until dispelled or triggered` - until dispelled or triggered
            * `permanent until discharged` - permanent until discharged
            * `permanent; one generation` - permanent; one generation
            * `permanent` - permanent
        :param concentration:
        :param verbal:
        :param somatic:
        :param material:
        :param material_consumed:
        :param casting_time_in: Multiple values may be separated by commas.
        :param casting_time_iexact:
        :param casting_time: Casting time key, such as 'action'

            * `reaction` - Reaction
            * `bonus-action` - 1 Bonus Action
            * `action` - 1 Action
            * `turn` - 1 Turn
            * `round` - 1 Round
            * `1minute` - 1 Minute
            * `5minutes` - 5 Minutes
            * `10minutes` - 10 Minutes
            * `1hour` - 1 Hour
            * `4hours` - 4 Hours
            * `7hours` - 7 Hours
            * `8hours` - 8 Hours
            * `9hours` - 9 Hours
            * `12hours` - 12 Hours
            * `24hours` - 24 Hours
            * `1week` - 1 Week
        :param ordering: Which field to use when ordering the results.
        :param search: A search term.
        :param page: A page number within the paginated result set.
        :param limit: Number of results to return per page.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SpellsListRequest(
            key_in=utils.unmarshal(key_in, Optional[List[str]]),
            key_iexact=key_iexact,
            key=key,
            name_iexact=name_iexact,
            name=name,
            name_contains=name_contains,
            name_icontains=name_icontains,
            document_key_in=utils.unmarshal(document_key_in, Optional[List[str]]),
            document_key_iexact=document_key_iexact,
            document_key=document_key,
            document_gamesystem_key_in=utils.unmarshal(
                document_gamesystem_key_in, Optional[List[str]]
            ),
            document_gamesystem_key_iexact=document_gamesystem_key_iexact,
            document_gamesystem_key=document_gamesystem_key,
            classes_key_in=utils.unmarshal(classes_key_in, Optional[List[str]]),
            classes_key_iexact=classes_key_iexact,
            classes_key=classes_key,
            classes_name_in=utils.unmarshal(classes_name_in, Optional[List[str]]),
            level=level,
            level_range=utils.unmarshal(level_range, Optional[List[int]]),
            level_gt=level_gt,
            level_gte=level_gte,
            level_lt=level_lt,
            level_lte=level_lte,
            range=range,
            range_range=utils.unmarshal(range_range, Optional[List[int]]),
            range_gt=range_gt,
            range_gte=range_gte,
            range_lt=range_lt,
            range_lte=range_lte,
            school_key=school_key,
            school_name_in=utils.unmarshal(school_name_in, Optional[List[str]]),
            school_name_iexact=school_name_iexact,
            school_name=school_name,
            duration_in=utils.unmarshal(duration_in, Optional[List[str]]),
            duration_iexact=duration_iexact,
            duration=duration,
            concentration=concentration,
            verbal=verbal,
            somatic=somatic,
            material=material,
            material_consumed=material_consumed,
            casting_time_in=utils.unmarshal(casting_time_in, Optional[List[str]]),
            casting_time_iexact=casting_time_iexact,
            casting_time=casting_time,
            ordering=ordering,
            search=search,
            page=page,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/v2/spells/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="spells_list",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PaginatedSpellList, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )

    async def list_async(
        self,
        *,
        key_in: Optional[Iterable[str]] = None,
        key_iexact: Optional[str] = None,
        key: Optional[str] = None,
        name_iexact: Optional[str] = None,
        name: Optional[str] = None,
        name_contains: Optional[str] = None,
        name_icontains: Optional[str] = None,
        document_key_in: Optional[Iterable[str]] = None,
        document_key_iexact: Optional[str] = None,
        document_key: Optional[str] = None,
        document_gamesystem_key_in: Optional[Iterable[str]] = None,
        document_gamesystem_key_iexact: Optional[str] = None,
        document_gamesystem_key: Optional[str] = None,
        classes_key_in: Optional[Iterable[str]] = None,
        classes_key_iexact: Optional[str] = None,
        classes_key: Optional[str] = None,
        classes_name_in: Optional[Iterable[str]] = None,
        level: Optional[int] = None,
        level_range: Optional[Iterable[int]] = None,
        level_gt: Optional[int] = None,
        level_gte: Optional[int] = None,
        level_lt: Optional[int] = None,
        level_lte: Optional[int] = None,
        range: Optional[int] = None,
        range_range: Optional[Iterable[int]] = None,
        range_gt: Optional[int] = None,
        range_gte: Optional[int] = None,
        range_lt: Optional[int] = None,
        range_lte: Optional[int] = None,
        school_key: Optional[str] = None,
        school_name_in: Optional[Iterable[str]] = None,
        school_name_iexact: Optional[str] = None,
        school_name: Optional[str] = None,
        duration_in: Optional[Iterable[str]] = None,
        duration_iexact: Optional[str] = None,
        duration: Optional[models.SpellsListDuration] = None,
        concentration: Optional[bool] = None,
        verbal: Optional[bool] = None,
        somatic: Optional[bool] = None,
        material: Optional[bool] = None,
        material_consumed: Optional[bool] = None,
        casting_time_in: Optional[Iterable[str]] = None,
        casting_time_iexact: Optional[str] = None,
        casting_time: Optional[models.SpellsListCastingTime] = None,
        ordering: Optional[str] = None,
        search: Optional[str] = None,
        page: Optional[int] = None,
        limit: Optional[int] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PaginatedSpellList:
        r"""list: API endpoint for returning a list of spells.
        retrieve: API endpoint for returning a particular spell.

        :param key_in: Multiple values may be separated by commas.
        :param key_iexact:
        :param key:
        :param name_iexact:
        :param name:
        :param name_contains:
        :param name_icontains:
        :param document_key_in: Multiple values may be separated by commas.
        :param document_key_iexact:
        :param document_key:
        :param document_gamesystem_key_in: Multiple values may be separated by commas.
        :param document_gamesystem_key_iexact:
        :param document_gamesystem_key:
        :param classes_key_in: Multiple values may be separated by commas.
        :param classes_key_iexact:
        :param classes_key:
        :param classes_name_in: Multiple values may be separated by commas.
        :param level:
        :param level_range: Multiple values may be separated by commas.
        :param level_gt:
        :param level_gte:
        :param level_lt:
        :param level_lte:
        :param range:
        :param range_range: Multiple values may be separated by commas.
        :param range_gt:
        :param range_gte:
        :param range_lt:
        :param range_lte:
        :param school_key:
        :param school_name_in: Multiple values may be separated by commas.
        :param school_name_iexact:
        :param school_name:
        :param duration_in: Multiple values may be separated by commas.
        :param duration_iexact:
        :param duration: Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"

            * `instantaneous` - instantaneous
            * `instantaneous or special` - instantaneous or special
            * `1 turn` - 1 turn
            * `1 round` - 1 round
            * `concentration + 1 round` - concentration + 1 round
            * `2 rounds` - 2 rounds
            * `3 rounds` - 3 rounds
            * `4 rounds` - 4 rounds
            * `1d4+2 rounds` - 1d4+2 rounds
            * `5 rounds` - 5 rounds
            * `6 rounds` - 6 rounds
            * `10 rounds` - 10 rounds
            * `up to 1 minute` - up to 1 minute
            * `1 minute` - 1 minute
            * `1 minute, or until expended` - 1 minute, or until expended
            * `1 minute, until expended` - 1 minute, until expended
            * `1 minute` - 1 minute
            * `5 minutes` - 5 minutes
            * `10 minutes` - 10 minutes
            * `1 minute or 1 hour` - 1 minute or 1 hour
            * `up to 1 hour` - up to 1 hour
            * `1 hour` - 1 hour
            * `1 hour or until triggered` - 1 hour or until triggered
            * `2 hours` - 2 hours
            * `3 hours` - 3 hours
            * `1d10 hours` - 1d10 hours
            * `6 hours` - 6 hours
            * `2-12 hours` - 2-12 hours
            * `up to 8 hours` - up to 8 hours
            * `8 hours` - 8 hours
            * `1 hour/caster level` - 1 hour/caster level
            * `10 hours` - 10 hours
            * `12 hours` - 12 hours
            * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw
            * `24 hours` - 24 hours
            * `1 day` - 1 day
            * `3 days` - 3 days
            * `5 days` - 5 days
            * `7 days` - 7 days
            * `10 days` - 10 days
            * `13 days` - 13 days
            * `30 days` - 30 days
            * `1 year` - 1 year
            * `special` - special
            * `until dispelled or destroyed` - until dispelled or destroyed
            * `until destroyed` - until destroyed
            * `until dispelled` - until dispelled
            * `until cured or dispelled` - until cured or dispelled
            * `until dispelled or triggered` - until dispelled or triggered
            * `permanent until discharged` - permanent until discharged
            * `permanent; one generation` - permanent; one generation
            * `permanent` - permanent
        :param concentration:
        :param verbal:
        :param somatic:
        :param material:
        :param material_consumed:
        :param casting_time_in: Multiple values may be separated by commas.
        :param casting_time_iexact:
        :param casting_time: Casting time key, such as 'action'

            * `reaction` - Reaction
            * `bonus-action` - 1 Bonus Action
            * `action` - 1 Action
            * `turn` - 1 Turn
            * `round` - 1 Round
            * `1minute` - 1 Minute
            * `5minutes` - 5 Minutes
            * `10minutes` - 10 Minutes
            * `1hour` - 1 Hour
            * `4hours` - 4 Hours
            * `7hours` - 7 Hours
            * `8hours` - 8 Hours
            * `9hours` - 9 Hours
            * `12hours` - 12 Hours
            * `24hours` - 24 Hours
            * `1week` - 1 Week
        :param ordering: Which field to use when ordering the results.
        :param search: A search term.
        :param page: A page number within the paginated result set.
        :param limit: Number of results to return per page.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SpellsListRequest(
            key_in=utils.unmarshal(key_in, Optional[List[str]]),
            key_iexact=key_iexact,
            key=key,
            name_iexact=name_iexact,
            name=name,
            name_contains=name_contains,
            name_icontains=name_icontains,
            document_key_in=utils.unmarshal(document_key_in, Optional[List[str]]),
            document_key_iexact=document_key_iexact,
            document_key=document_key,
            document_gamesystem_key_in=utils.unmarshal(
                document_gamesystem_key_in, Optional[List[str]]
            ),
            document_gamesystem_key_iexact=document_gamesystem_key_iexact,
            document_gamesystem_key=document_gamesystem_key,
            classes_key_in=utils.unmarshal(classes_key_in, Optional[List[str]]),
            classes_key_iexact=classes_key_iexact,
            classes_key=classes_key,
            classes_name_in=utils.unmarshal(classes_name_in, Optional[List[str]]),
            level=level,
            level_range=utils.unmarshal(level_range, Optional[List[int]]),
            level_gt=level_gt,
            level_gte=level_gte,
            level_lt=level_lt,
            level_lte=level_lte,
            range=range,
            range_range=utils.unmarshal(range_range, Optional[List[int]]),
            range_gt=range_gt,
            range_gte=range_gte,
            range_lt=range_lt,
            range_lte=range_lte,
            school_key=school_key,
            school_name_in=utils.unmarshal(school_name_in, Optional[List[str]]),
            school_name_iexact=school_name_iexact,
            school_name=school_name,
            duration_in=utils.unmarshal(duration_in, Optional[List[str]]),
            duration_iexact=duration_iexact,
            duration=duration,
            concentration=concentration,
            verbal=verbal,
            somatic=somatic,
            material=material,
            material_consumed=material_consumed,
            casting_time_in=utils.unmarshal(casting_time_in, Optional[List[str]]),
            casting_time_iexact=casting_time_iexact,
            casting_time=casting_time,
            ordering=ordering,
            search=search,
            page=page,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/spells/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="spells_list",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PaginatedSpellList, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )

    def get(
        self,
        *,
        key: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Spell:
        r"""list: API endpoint for returning a list of spells.
        retrieve: API endpoint for returning a particular spell.

        :param key:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SpellsRetrieveRequest(
            key=key,
        )

        req = self._build_request(
            method="GET",
            path="/v2/spells/{key}/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="spells_retrieve",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Spell, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )

    async def get_async(
        self,
        *,
        key: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Spell:
        r"""list: API endpoint for returning a list of spells.
        retrieve: API endpoint for returning a particular spell.

        :param key:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SpellsRetrieveRequest(
            key=key,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/spells/{key}/",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="spells_retrieve",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Spell, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.AnideasmithDocGenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.AnideasmithDocGenDefaultError(
            "Unexpected response received", http_res
        )
