/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbilityScores
 */
export interface AbilityScores {
    /**
     * 
     * @type {number}
     * @memberof AbilityScores
     */
    strength: number;
    /**
     * 
     * @type {number}
     * @memberof AbilityScores
     */
    dexterity: number;
    /**
     * 
     * @type {number}
     * @memberof AbilityScores
     */
    constitution: number;
    /**
     * 
     * @type {number}
     * @memberof AbilityScores
     */
    intelligence: number;
    /**
     * 
     * @type {number}
     * @memberof AbilityScores
     */
    wisdom: number;
    /**
     * 
     * @type {number}
     * @memberof AbilityScores
     */
    charisma: number;
}

/**
 * Check if a given object implements the AbilityScores interface.
 */
export function instanceOfAbilityScores(value: object): value is AbilityScores {
    if (!('strength' in value) || value['strength'] === undefined) return false;
    if (!('dexterity' in value) || value['dexterity'] === undefined) return false;
    if (!('constitution' in value) || value['constitution'] === undefined) return false;
    if (!('intelligence' in value) || value['intelligence'] === undefined) return false;
    if (!('wisdom' in value) || value['wisdom'] === undefined) return false;
    if (!('charisma' in value) || value['charisma'] === undefined) return false;
    return true;
}

export function AbilityScoresFromJSON(json: any): AbilityScores {
    return AbilityScoresFromJSONTyped(json, false);
}

export function AbilityScoresFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbilityScores {
    if (json == null) {
        return json;
    }
    return {
        
        'strength': json['strength'],
        'dexterity': json['dexterity'],
        'constitution': json['constitution'],
        'intelligence': json['intelligence'],
        'wisdom': json['wisdom'],
        'charisma': json['charisma'],
    };
}

export function AbilityScoresToJSON(json: any): AbilityScores {
    return AbilityScoresToJSONTyped(json, false);
}

export function AbilityScoresToJSONTyped(value?: AbilityScores | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strength': value['strength'],
        'dexterity': value['dexterity'],
        'constitution': value['constitution'],
        'intelligence': value['intelligence'],
        'wisdom': value['wisdom'],
        'charisma': value['charisma'],
    };
}

