/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrossReferences } from './CrossReferences';
import {
    CrossReferencesFromJSON,
    CrossReferencesFromJSONTyped,
    CrossReferencesToJSON,
    CrossReferencesToJSONTyped,
} from './CrossReferences';
import type { ClassFeature } from './ClassFeature';
import {
    ClassFeatureFromJSON,
    ClassFeatureFromJSONTyped,
    ClassFeatureToJSON,
    ClassFeatureToJSONTyped,
} from './ClassFeature';
import type { HitPoints } from './HitPoints';
import {
    HitPointsFromJSON,
    HitPointsFromJSONTyped,
    HitPointsToJSON,
    HitPointsToJSONTyped,
} from './HitPoints';
import type { AbilitySummary } from './AbilitySummary';
import {
    AbilitySummaryFromJSON,
    AbilitySummaryFromJSONTyped,
    AbilitySummaryToJSON,
    AbilitySummaryToJSONTyped,
} from './AbilitySummary';
import type { DocumentSummary } from './DocumentSummary';
import {
    DocumentSummaryFromJSON,
    DocumentSummaryFromJSONTyped,
    DocumentSummaryToJSON,
    DocumentSummaryToJSONTyped,
} from './DocumentSummary';
import type { CharacterClassSummary } from './CharacterClassSummary';
import {
    CharacterClassSummaryFromJSON,
    CharacterClassSummaryFromJSONTyped,
    CharacterClassSummaryToJSON,
    CharacterClassSummaryToJSONTyped,
} from './CharacterClassSummary';

/**
 * Much of the logic included in the GameContentSerializer is intended to
 * support manipulating data returned by the serializer via query parameters.
 * @export
 * @interface CharacterClass
 */
export interface CharacterClass {
    /**
     * Unique key for the Item.
     * @type {string}
     * @memberof CharacterClass
     */
    readonly key: string;
    /**
     * 
     * @type {Array<ClassFeature>}
     * @memberof CharacterClass
     */
    readonly features: Array<ClassFeature>;
    /**
     * 
     * @type {HitPoints}
     * @memberof CharacterClass
     */
    readonly hitPoints: HitPoints;
    /**
     * 
     * @type {DocumentSummary}
     * @memberof CharacterClass
     */
    document: DocumentSummary;
    /**
     * 
     * @type {Array<AbilitySummary>}
     * @memberof CharacterClass
     */
    savingThrows: Array<AbilitySummary>;
    /**
     * 
     * @type {CharacterClassSummary}
     * @memberof CharacterClass
     */
    subclassOf: CharacterClassSummary;
    /**
     * Name of the item.
     * @type {string}
     * @memberof CharacterClass
     */
    name: string;
    /**
     * Description of the game content item. Markdown.
     * @type {string}
     * @memberof CharacterClass
     */
    desc?: string;
    /**
     * Dice notation hit dice option.
     * 
     * * `D3` - d3
     * * `D4` - d4
     * * `D6` - d6
     * * `D8` - d8
     * * `D10` - d10
     * * `D12` - d12
     * * `D20` - d20
     * * `d3` - d3
     * * `d4` - d4
     * * `d6` - d6
     * * `d8` - d8
     * * `d10` - d10
     * * `d12` - d12
     * * `d20` - d20
     * @type {CharacterClassHitDiceEnum}
     * @memberof CharacterClass
     */
    hitDice?: CharacterClassHitDiceEnum | null;
    /**
     * Type of caster. Options are full, half, none.
     * 
     * * `FULL` - Full
     * * `HALF` - Half
     * * `PACT` - Pact
     * * `NONE` - None
     * @type {CharacterClassCasterTypeEnum}
     * @memberof CharacterClass
     */
    casterType?: CharacterClassCasterTypeEnum | null;
    /**
     * Primary abilities for thie class
     * @type {Array<string>}
     * @memberof CharacterClass
     */
    primaryAbilities: Array<string>;
    /**
     * 
     * @type {CrossReferences}
     * @memberof CharacterClass
     */
    readonly crossreferences: CrossReferences;
}


/**
 * @export
 */
export const CharacterClassHitDiceEnum = {
    D3: 'D3',
    D4: 'D4',
    D6: 'D6',
    D8: 'D8',
    D10: 'D10',
    D12: 'D12',
    D20: 'D20',
    D32: 'd3',
    D42: 'd4',
    D62: 'd6',
    D82: 'd8',
    D102: 'd10',
    D122: 'd12',
    D202: 'd20',
    Empty: ''
} as const;
export type CharacterClassHitDiceEnum = typeof CharacterClassHitDiceEnum[keyof typeof CharacterClassHitDiceEnum];

/**
 * @export
 */
export const CharacterClassCasterTypeEnum = {
    Full: 'FULL',
    Half: 'HALF',
    Pact: 'PACT',
    None: 'NONE',
    Empty: ''
} as const;
export type CharacterClassCasterTypeEnum = typeof CharacterClassCasterTypeEnum[keyof typeof CharacterClassCasterTypeEnum];


/**
 * Check if a given object implements the CharacterClass interface.
 */
export function instanceOfCharacterClass(value: object): value is CharacterClass {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    if ((!('hitPoints' in value) && !('hit_points' in value)) || (value['hitPoints'] === undefined && value['hit_points'] === undefined)) return false;
    if (!('document' in value) || value['document'] === undefined) return false;
    if ((!('savingThrows' in value) && !('saving_throws' in value)) || (value['savingThrows'] === undefined && value['saving_throws'] === undefined)) return false;
    if ((!('subclassOf' in value) && !('subclass_of' in value)) || (value['subclassOf'] === undefined && value['subclass_of'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('primaryAbilities' in value) && !('primary_abilities' in value)) || (value['primaryAbilities'] === undefined && value['primary_abilities'] === undefined)) return false;
    if (!('crossreferences' in value) || value['crossreferences'] === undefined) return false;
    return true;
}

export function CharacterClassFromJSON(json: any): CharacterClass {
    return CharacterClassFromJSONTyped(json, false);
}

export function CharacterClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterClass {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'features': ((json['features'] as Array<any>).map(ClassFeatureFromJSON)),
        'hitPoints': HitPointsFromJSON(json['hit_points']),
        'document': DocumentSummaryFromJSON(json['document']),
        'savingThrows': ((json['saving_throws'] as Array<any>).map(AbilitySummaryFromJSON)),
        'subclassOf': CharacterClassSummaryFromJSON(json['subclass_of']),
        'name': json['name'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'hitDice': json['hit_dice'] == null ? undefined : json['hit_dice'],
        'casterType': json['caster_type'] == null ? undefined : json['caster_type'],
        'primaryAbilities': json['primary_abilities'],
        'crossreferences': CrossReferencesFromJSON(json['crossreferences']),
    };
}

export function CharacterClassToJSON(json: any): CharacterClass {
    return CharacterClassToJSONTyped(json, false);
}

export function CharacterClassToJSONTyped(value?: Omit<CharacterClass, 'key'|'features'|'hit_points'|'crossreferences'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document': DocumentSummaryToJSON(value['document']),
        'saving_throws': ((value['savingThrows'] as Array<any>).map(AbilitySummaryToJSON)),
        'subclass_of': CharacterClassSummaryToJSON(value['subclassOf']),
        'name': value['name'],
        'desc': value['desc'],
        'hit_dice': value['hitDice'],
        'caster_type': value['casterType'],
        'primary_abilities': value['primaryAbilities'],
    };
}

