/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Much of the logic included in the GameContentSerializer is intended to
 * support manipulating data returned by the serializer via query parameters.
 * @export
 * @interface ClassFeaturePrefetch
 */
export interface ClassFeaturePrefetch {
    /**
     * 
     * @type {number}
     * @memberof ClassFeaturePrefetch
     */
    level: number;
    /**
     * 
     * @type {string}
     * @memberof ClassFeaturePrefetch
     */
    detail?: string | null;
    /**
     * The value that should be displayed in the table column (where applicable).
     * @type {string}
     * @memberof ClassFeaturePrefetch
     */
    columnValue?: string | null;
}

/**
 * Check if a given object implements the ClassFeaturePrefetch interface.
 */
export function instanceOfClassFeaturePrefetch(value: object): value is ClassFeaturePrefetch {
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function ClassFeaturePrefetchFromJSON(json: any): ClassFeaturePrefetch {
    return ClassFeaturePrefetchFromJSONTyped(json, false);
}

export function ClassFeaturePrefetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassFeaturePrefetch {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'columnValue': json['column_value'] == null ? undefined : json['column_value'],
    };
}

export function ClassFeaturePrefetchToJSON(json: any): ClassFeaturePrefetch {
    return ClassFeaturePrefetchToJSONTyped(json, false);
}

export function ClassFeaturePrefetchToJSONTyped(value?: ClassFeaturePrefetch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'detail': value['detail'],
        'column_value': value['columnValue'],
    };
}

