/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A slimmer CreatureTypeSerializer, designed to serialize CreatureType FKs on
 * other serializers . Not intended to be used directly with in a ModelViewset.
 * @export
 * @interface CreatureTypeSummary
 */
export interface CreatureTypeSummary {
    /**
     * Name of the item.
     * @type {string}
     * @memberof CreatureTypeSummary
     */
    name: string;
    /**
     * Unique key for the Item.
     * @type {string}
     * @memberof CreatureTypeSummary
     */
    key: string;
}

/**
 * Check if a given object implements the CreatureTypeSummary interface.
 */
export function instanceOfCreatureTypeSummary(value: object): value is CreatureTypeSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function CreatureTypeSummaryFromJSON(json: any): CreatureTypeSummary {
    return CreatureTypeSummaryFromJSONTyped(json, false);
}

export function CreatureTypeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatureTypeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'],
    };
}

export function CreatureTypeSummaryToJSON(json: any): CreatureTypeSummary {
    return CreatureTypeSummaryToJSONTyped(json, false);
}

export function CreatureTypeSummaryToJSONTyped(value?: CreatureTypeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
    };
}

