/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DamageTypeSummary } from './DamageTypeSummary';
import {
    DamageTypeSummaryFromJSON,
    DamageTypeSummaryFromJSONTyped,
    DamageTypeSummaryToJSON,
    DamageTypeSummaryToJSONTyped,
} from './DamageTypeSummary';
import type { ConditionSummary } from './ConditionSummary';
import {
    ConditionSummaryFromJSON,
    ConditionSummaryFromJSONTyped,
    ConditionSummaryToJSON,
    ConditionSummaryToJSONTyped,
} from './ConditionSummary';

/**
 * This serializer formats a Creature's damage modifier as a single obj
 * @export
 * @interface CreatureResistancesAndImmunities
 */
export interface CreatureResistancesAndImmunities {
    /**
     * 
     * @type {string}
     * @memberof CreatureResistancesAndImmunities
     */
    damageImmunitiesDisplay: string;
    /**
     * 
     * @type {Array<DamageTypeSummary>}
     * @memberof CreatureResistancesAndImmunities
     */
    damageImmunities: Array<DamageTypeSummary>;
    /**
     * 
     * @type {string}
     * @memberof CreatureResistancesAndImmunities
     */
    damageResistancesDisplay: string;
    /**
     * 
     * @type {Array<DamageTypeSummary>}
     * @memberof CreatureResistancesAndImmunities
     */
    damageResistances: Array<DamageTypeSummary>;
    /**
     * 
     * @type {string}
     * @memberof CreatureResistancesAndImmunities
     */
    damageVulnerabilitiesDisplay: string;
    /**
     * 
     * @type {Array<DamageTypeSummary>}
     * @memberof CreatureResistancesAndImmunities
     */
    damageVulnerabilities: Array<DamageTypeSummary>;
    /**
     * 
     * @type {string}
     * @memberof CreatureResistancesAndImmunities
     */
    conditionImmunitiesDisplay: string;
    /**
     * 
     * @type {Array<ConditionSummary>}
     * @memberof CreatureResistancesAndImmunities
     */
    conditionImmunities: Array<ConditionSummary>;
}

/**
 * Check if a given object implements the CreatureResistancesAndImmunities interface.
 */
export function instanceOfCreatureResistancesAndImmunities(value: object): value is CreatureResistancesAndImmunities {
    if ((!('damageImmunitiesDisplay' in value) && !('damage_immunities_display' in value)) || (value['damageImmunitiesDisplay'] === undefined && value['damage_immunities_display'] === undefined)) return false;
    if ((!('damageImmunities' in value) && !('damage_immunities' in value)) || (value['damageImmunities'] === undefined && value['damage_immunities'] === undefined)) return false;
    if ((!('damageResistancesDisplay' in value) && !('damage_resistances_display' in value)) || (value['damageResistancesDisplay'] === undefined && value['damage_resistances_display'] === undefined)) return false;
    if ((!('damageResistances' in value) && !('damage_resistances' in value)) || (value['damageResistances'] === undefined && value['damage_resistances'] === undefined)) return false;
    if ((!('damageVulnerabilitiesDisplay' in value) && !('damage_vulnerabilities_display' in value)) || (value['damageVulnerabilitiesDisplay'] === undefined && value['damage_vulnerabilities_display'] === undefined)) return false;
    if ((!('damageVulnerabilities' in value) && !('damage_vulnerabilities' in value)) || (value['damageVulnerabilities'] === undefined && value['damage_vulnerabilities'] === undefined)) return false;
    if ((!('conditionImmunitiesDisplay' in value) && !('condition_immunities_display' in value)) || (value['conditionImmunitiesDisplay'] === undefined && value['condition_immunities_display'] === undefined)) return false;
    if ((!('conditionImmunities' in value) && !('condition_immunities' in value)) || (value['conditionImmunities'] === undefined && value['condition_immunities'] === undefined)) return false;
    return true;
}

export function CreatureResistancesAndImmunitiesFromJSON(json: any): CreatureResistancesAndImmunities {
    return CreatureResistancesAndImmunitiesFromJSONTyped(json, false);
}

export function CreatureResistancesAndImmunitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatureResistancesAndImmunities {
    if (json == null) {
        return json;
    }
    return {
        
        'damageImmunitiesDisplay': json['damage_immunities_display'],
        'damageImmunities': ((json['damage_immunities'] as Array<any>).map(DamageTypeSummaryFromJSON)),
        'damageResistancesDisplay': json['damage_resistances_display'],
        'damageResistances': ((json['damage_resistances'] as Array<any>).map(DamageTypeSummaryFromJSON)),
        'damageVulnerabilitiesDisplay': json['damage_vulnerabilities_display'],
        'damageVulnerabilities': ((json['damage_vulnerabilities'] as Array<any>).map(DamageTypeSummaryFromJSON)),
        'conditionImmunitiesDisplay': json['condition_immunities_display'],
        'conditionImmunities': ((json['condition_immunities'] as Array<any>).map(ConditionSummaryFromJSON)),
    };
}

export function CreatureResistancesAndImmunitiesToJSON(json: any): CreatureResistancesAndImmunities {
    return CreatureResistancesAndImmunitiesToJSONTyped(json, false);
}

export function CreatureResistancesAndImmunitiesToJSONTyped(value?: CreatureResistancesAndImmunities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'damage_immunities_display': value['damageImmunitiesDisplay'],
        'damage_immunities': ((value['damageImmunities'] as Array<any>).map(DamageTypeSummaryToJSON)),
        'damage_resistances_display': value['damageResistancesDisplay'],
        'damage_resistances': ((value['damageResistances'] as Array<any>).map(DamageTypeSummaryToJSON)),
        'damage_vulnerabilities_display': value['damageVulnerabilitiesDisplay'],
        'damage_vulnerabilities': ((value['damageVulnerabilities'] as Array<any>).map(DamageTypeSummaryToJSON)),
        'condition_immunities_display': value['conditionImmunitiesDisplay'],
        'condition_immunities': ((value['conditionImmunities'] as Array<any>).map(ConditionSummaryToJSON)),
    };
}

