/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageSummary } from './LanguageSummary';
import {
    LanguageSummaryFromJSON,
    LanguageSummaryFromJSONTyped,
    LanguageSummaryToJSON,
    LanguageSummaryToJSONTyped,
} from './LanguageSummary';

/**
 * Much of the logic included in the GameContentSerializer is intended to
 * support manipulating data returned by the serializer via query parameters.
 * @export
 * @interface CreatureLanguage
 */
export interface CreatureLanguage {
    /**
     * 
     * @type {string}
     * @memberof CreatureLanguage
     */
    asString: string;
    /**
     * 
     * @type {Array<LanguageSummary>}
     * @memberof CreatureLanguage
     */
    data: Array<LanguageSummary>;
}

/**
 * Check if a given object implements the CreatureLanguage interface.
 */
export function instanceOfCreatureLanguage(value: object): value is CreatureLanguage {
    if ((!('asString' in value) && !('as_string' in value)) || (value['asString'] === undefined && value['as_string'] === undefined)) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreatureLanguageFromJSON(json: any): CreatureLanguage {
    return CreatureLanguageFromJSONTyped(json, false);
}

export function CreatureLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatureLanguage {
    if (json == null) {
        return json;
    }
    return {
        
        'asString': json['as_string'],
        'data': ((json['data'] as Array<any>).map(LanguageSummaryFromJSON)),
    };
}

export function CreatureLanguageToJSON(json: any): CreatureLanguage {
    return CreatureLanguageToJSONTyped(json, false);
}

export function CreatureLanguageToJSONTyped(value?: CreatureLanguage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'as_string': value['asString'],
        'data': ((value['data'] as Array<any>).map(LanguageSummaryToJSON)),
    };
}

