/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrossReferenceLink } from './CrossReferenceLink';
import {
    CrossReferenceLinkFromJSON,
    CrossReferenceLinkFromJSONTyped,
    CrossReferenceLinkToJSON,
    CrossReferenceLinkToJSONTyped,
} from './CrossReferenceLink';

/**
 * 
 * @export
 * @interface CrossReferences
 */
export interface CrossReferences {
    /**
     * 
     * @type {Array<CrossReferenceLink>}
     * @memberof CrossReferences
     */
    to: Array<CrossReferenceLink>;
}

/**
 * Check if a given object implements the CrossReferences interface.
 */
export function instanceOfCrossReferences(value: object): value is CrossReferences {
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function CrossReferencesFromJSON(json: any): CrossReferences {
    return CrossReferencesFromJSONTyped(json, false);
}

export function CrossReferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossReferences {
    if (json == null) {
        return json;
    }
    return {
        
        'to': ((json['to'] as Array<any>).map(CrossReferenceLinkFromJSON)),
    };
}

export function CrossReferencesToJSON(json: any): CrossReferences {
    return CrossReferencesToJSONTyped(json, false);
}

export function CrossReferencesToJSONTyped(value?: CrossReferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': ((value['to'] as Array<any>).map(CrossReferenceLinkToJSON)),
    };
}

