/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublisherSummary } from './PublisherSummary';
import {
    PublisherSummaryFromJSON,
    PublisherSummaryFromJSONTyped,
    PublisherSummaryToJSON,
    PublisherSummaryToJSONTyped,
} from './PublisherSummary';
import type { GameSystemSummary } from './GameSystemSummary';
import {
    GameSystemSummaryFromJSON,
    GameSystemSummaryFromJSONTyped,
    GameSystemSummaryToJSON,
    GameSystemSummaryToJSONTyped,
} from './GameSystemSummary';

/**
 * A slimmer DocumentSerializer, designed to serialize Documents FKs on other
 * serializers. Not intended to be used directly with in a ModelViewset.
 * @export
 * @interface DocumentSummary
 */
export interface DocumentSummary {
    /**
     * Name of the item.
     * @type {string}
     * @memberof DocumentSummary
     */
    name: string;
    /**
     * Unique key for the Document.
     * @type {string}
     * @memberof DocumentSummary
     */
    key: string;
    /**
     * Whether this Document is a published data source, or general resources
     * 
     * * `SOURCE` - Source
     * * `MISC` - Miscellaneous
     * @type {DocumentSummaryTypeEnum}
     * @memberof DocumentSummary
     */
    type?: DocumentSummaryTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DocumentSummary
     */
    readonly displayName: string;
    /**
     * 
     * @type {PublisherSummary}
     * @memberof DocumentSummary
     */
    publisher: PublisherSummary;
    /**
     * 
     * @type {GameSystemSummary}
     * @memberof DocumentSummary
     */
    gamesystem: GameSystemSummary;
    /**
     * Link to the document.
     * @type {string}
     * @memberof DocumentSummary
     */
    permalink: string;
}


/**
 * @export
 */
export const DocumentSummaryTypeEnum = {
    Source: 'SOURCE',
    Misc: 'MISC'
} as const;
export type DocumentSummaryTypeEnum = typeof DocumentSummaryTypeEnum[keyof typeof DocumentSummaryTypeEnum];


/**
 * Check if a given object implements the DocumentSummary interface.
 */
export function instanceOfDocumentSummary(value: object): value is DocumentSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if ((!('displayName' in value) && !('display_name' in value)) || (value['displayName'] === undefined && value['display_name'] === undefined)) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if (!('gamesystem' in value) || value['gamesystem'] === undefined) return false;
    if (!('permalink' in value) || value['permalink'] === undefined) return false;
    return true;
}

export function DocumentSummaryFromJSON(json: any): DocumentSummary {
    return DocumentSummaryFromJSONTyped(json, false);
}

export function DocumentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'],
        'type': json['type'] == null ? undefined : json['type'],
        'displayName': json['display_name'],
        'publisher': PublisherSummaryFromJSON(json['publisher']),
        'gamesystem': GameSystemSummaryFromJSON(json['gamesystem']),
        'permalink': json['permalink'],
    };
}

export function DocumentSummaryToJSON(json: any): DocumentSummary {
    return DocumentSummaryToJSONTyped(json, false);
}

export function DocumentSummaryToJSONTyped(value?: Omit<DocumentSummary, 'display_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
        'type': value['type'],
        'publisher': PublisherSummaryToJSON(value['publisher']),
        'gamesystem': GameSystemSummaryToJSON(value['gamesystem']),
        'permalink': value['permalink'],
    };
}

