/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A slimmer EnvironmentSerializer, designed to serialize Enviroment FKs on
 * other serializers. ie. The `environments` field on the CreatureSerializer.
 * Not intended to be used directly in a ModelViewset.
 * @export
 * @interface EnvironmentSummary
 */
export interface EnvironmentSummary {
    /**
     * Name of the item.
     * @type {string}
     * @memberof EnvironmentSummary
     */
    name: string;
    /**
     * Unique key for the Item.
     * @type {string}
     * @memberof EnvironmentSummary
     */
    key: string;
}

/**
 * Check if a given object implements the EnvironmentSummary interface.
 */
export function instanceOfEnvironmentSummary(value: object): value is EnvironmentSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function EnvironmentSummaryFromJSON(json: any): EnvironmentSummary {
    return EnvironmentSummaryFromJSONTyped(json, false);
}

export function EnvironmentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'],
    };
}

export function EnvironmentSummaryToJSON(json: any): EnvironmentSummary {
    return EnvironmentSummaryToJSONTyped(json, false);
}

export function EnvironmentSummaryToJSONTyped(value?: EnvironmentSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
    };
}

