/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A slimmer GameSystemSerializer, designed to serialize GameSystem FKs on
 * other serializers. Not intended to be used directly with in a ModelViewset.
 * @export
 * @interface GameSystemSummary
 */
export interface GameSystemSummary {
    /**
     * Name of the item.
     * @type {string}
     * @memberof GameSystemSummary
     */
    name: string;
    /**
     * Unique key for the gamesystem the document was published for.
     * @type {string}
     * @memberof GameSystemSummary
     */
    key: string;
}

/**
 * Check if a given object implements the GameSystemSummary interface.
 */
export function instanceOfGameSystemSummary(value: object): value is GameSystemSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function GameSystemSummaryFromJSON(json: any): GameSystemSummary {
    return GameSystemSummaryFromJSONTyped(json, false);
}

export function GameSystemSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameSystemSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'],
    };
}

export function GameSystemSummaryToJSON(json: any): GameSystemSummary {
    return GameSystemSummaryToJSONTyped(json, false);
}

export function GameSystemSummaryToJSONTyped(value?: GameSystemSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
    };
}

