/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HitPoints
 */
export interface HitPoints {
    /**
     * 
     * @type {number}
     * @memberof HitPoints
     */
    hitDice: number;
    /**
     * 
     * @type {string}
     * @memberof HitPoints
     */
    readonly hitDiceName: string;
    /**
     * 
     * @type {number}
     * @memberof HitPoints
     */
    hitPointsAt1stLevel: number;
    /**
     * 
     * @type {number}
     * @memberof HitPoints
     */
    hitPointsAtHigherLevels: number;
}

/**
 * Check if a given object implements the HitPoints interface.
 */
export function instanceOfHitPoints(value: object): value is HitPoints {
    if ((!('hitDice' in value) && !('hit_dice' in value)) || (value['hitDice'] === undefined && value['hit_dice'] === undefined)) return false;
    if ((!('hitDiceName' in value) && !('hit_dice_name' in value)) || (value['hitDiceName'] === undefined && value['hit_dice_name'] === undefined)) return false;
    if ((!('hitPointsAt1stLevel' in value) && !('hit_points_at_1st_level' in value)) || (value['hitPointsAt1stLevel'] === undefined && value['hit_points_at_1st_level'] === undefined)) return false;
    if ((!('hitPointsAtHigherLevels' in value) && !('hit_points_at_higher_levels' in value)) || (value['hitPointsAtHigherLevels'] === undefined && value['hit_points_at_higher_levels'] === undefined)) return false;
    return true;
}

export function HitPointsFromJSON(json: any): HitPoints {
    return HitPointsFromJSONTyped(json, false);
}

export function HitPointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HitPoints {
    if (json == null) {
        return json;
    }
    return {
        
        'hitDice': json['hit_dice'],
        'hitDiceName': json['hit_dice_name'],
        'hitPointsAt1stLevel': json['hit_points_at_1st_level'],
        'hitPointsAtHigherLevels': json['hit_points_at_higher_levels'],
    };
}

export function HitPointsToJSON(json: any): HitPoints {
    return HitPointsToJSONTyped(json, false);
}

export function HitPointsToJSONTyped(value?: Omit<HitPoints, 'hit_dice_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hit_dice': value['hitDice'],
        'hit_points_at_1st_level': value['hitPointsAt1stLevel'],
        'hit_points_at_higher_levels': value['hitPointsAtHigherLevels'],
    };
}

