/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * This serializer is used for FKs to the Language model from other
 * serializers. ie. for the languages spoken by creatures on the
 * CreatureSerializer.
 * @export
 * @interface LanguageSummary
 */
export interface LanguageSummary {
    /**
     * Name of the item.
     * @type {string}
     * @memberof LanguageSummary
     */
    name: string;
    /**
     * Unique key for the Item.
     * @type {string}
     * @memberof LanguageSummary
     */
    readonly key: string;
    /**
     * Description of the game content item. Markdown.
     * @type {string}
     * @memberof LanguageSummary
     */
    desc?: string;
}

/**
 * Check if a given object implements the LanguageSummary interface.
 */
export function instanceOfLanguageSummary(value: object): value is LanguageSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function LanguageSummaryFromJSON(json: any): LanguageSummary {
    return LanguageSummaryFromJSONTyped(json, false);
}

export function LanguageSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'],
        'desc': json['desc'] == null ? undefined : json['desc'],
    };
}

export function LanguageSummaryToJSON(json: any): LanguageSummary {
    return LanguageSummaryToJSONTyped(json, false);
}

export function LanguageSummaryToJSONTyped(value?: Omit<LanguageSummary, 'key'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'desc': value['desc'],
    };
}

