/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Creature } from './Creature';
import {
    CreatureFromJSON,
    CreatureFromJSONTyped,
    CreatureToJSON,
    CreatureToJSONTyped,
} from './Creature';

/**
 * 
 * @export
 * @interface PaginatedCreatureList
 */
export interface PaginatedCreatureList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCreatureList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCreatureList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCreatureList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Creature>}
     * @memberof PaginatedCreatureList
     */
    results: Array<Creature>;
}

/**
 * Check if a given object implements the PaginatedCreatureList interface.
 */
export function instanceOfPaginatedCreatureList(value: object): value is PaginatedCreatureList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCreatureListFromJSON(json: any): PaginatedCreatureList {
    return PaginatedCreatureListFromJSONTyped(json, false);
}

export function PaginatedCreatureListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCreatureList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CreatureFromJSON)),
    };
}

export function PaginatedCreatureListToJSON(json: any): PaginatedCreatureList {
    return PaginatedCreatureListToJSONTyped(json, false);
}

export function PaginatedCreatureListToJSONTyped(value?: PaginatedCreatureList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CreatureToJSON)),
    };
}

