/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharacterClass } from './CharacterClass';
import {
    CharacterClassFromJSON,
    CharacterClassFromJSONTyped,
    CharacterClassToJSON,
    CharacterClassToJSONTyped,
} from './CharacterClass';

/**
 * 
 * @export
 * @interface PaginatedCharacterClassList
 */
export interface PaginatedCharacterClassList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCharacterClassList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCharacterClassList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCharacterClassList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CharacterClass>}
     * @memberof PaginatedCharacterClassList
     */
    results: Array<CharacterClass>;
}

/**
 * Check if a given object implements the PaginatedCharacterClassList interface.
 */
export function instanceOfPaginatedCharacterClassList(value: object): value is PaginatedCharacterClassList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCharacterClassListFromJSON(json: any): PaginatedCharacterClassList {
    return PaginatedCharacterClassListFromJSONTyped(json, false);
}

export function PaginatedCharacterClassListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCharacterClassList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CharacterClassFromJSON)),
    };
}

export function PaginatedCharacterClassListToJSON(json: any): PaginatedCharacterClassList {
    return PaginatedCharacterClassListToJSONTyped(json, false);
}

export function PaginatedCharacterClassListToJSONTyped(value?: PaginatedCharacterClassList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CharacterClassToJSON)),
    };
}

