/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Spell } from './Spell';
import {
    SpellFromJSON,
    SpellFromJSONTyped,
    SpellToJSON,
    SpellToJSONTyped,
} from './Spell';

/**
 * 
 * @export
 * @interface PaginatedSpellList
 */
export interface PaginatedSpellList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSpellList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSpellList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSpellList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Spell>}
     * @memberof PaginatedSpellList
     */
    results: Array<Spell>;
}

/**
 * Check if a given object implements the PaginatedSpellList interface.
 */
export function instanceOfPaginatedSpellList(value: object): value is PaginatedSpellList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSpellListFromJSON(json: any): PaginatedSpellList {
    return PaginatedSpellListFromJSONTyped(json, false);
}

export function PaginatedSpellListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSpellList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SpellFromJSON)),
    };
}

export function PaginatedSpellListToJSON(json: any): PaginatedSpellList {
    return PaginatedSpellListToJSONTyped(json, false);
}

export function PaginatedSpellListToJSONTyped(value?: PaginatedSpellList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SpellToJSON)),
    };
}

