/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A slimmer SizeSerializer, designed to serialize Size FKs on other
 * serializers. ie. The `size` field on the CreatureSerializer. Not intended
 * to be used directly in a ModelViewset.
 * @export
 * @interface SizeSummary
 */
export interface SizeSummary {
    /**
     * Name of the item.
     * @type {string}
     * @memberof SizeSummary
     */
    name: string;
    /**
     * Unique key for the Item.
     * @type {string}
     * @memberof SizeSummary
     */
    key: string;
}

/**
 * Check if a given object implements the SizeSummary interface.
 */
export function instanceOfSizeSummary(value: object): value is SizeSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function SizeSummaryFromJSON(json: any): SizeSummary {
    return SizeSummaryFromJSONTyped(json, false);
}

export function SizeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'],
    };
}

export function SizeSummaryToJSON(json: any): SizeSummary {
    return SizeSummaryToJSONTyped(json, false);
}

export function SizeSummaryToJSONTyped(value?: SizeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
    };
}

