/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillBonuses
 */
export interface SkillBonuses {
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    acrobatics: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    animalHandling: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    arcana: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    athletics: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    deception: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    history: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    insight: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    intimidation: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    investigation: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    medicine: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    nature: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    perception: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    performance: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    persuasion: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    religion: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    sleightOfHand: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    stealth: number;
    /**
     * 
     * @type {number}
     * @memberof SkillBonuses
     */
    survival: number;
}

/**
 * Check if a given object implements the SkillBonuses interface.
 */
export function instanceOfSkillBonuses(value: object): value is SkillBonuses {
    if (!('acrobatics' in value) || value['acrobatics'] === undefined) return false;
    if ((!('animalHandling' in value) && !('animal_handling' in value)) || (value['animalHandling'] === undefined && value['animal_handling'] === undefined)) return false;
    if (!('arcana' in value) || value['arcana'] === undefined) return false;
    if (!('athletics' in value) || value['athletics'] === undefined) return false;
    if (!('deception' in value) || value['deception'] === undefined) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    if (!('insight' in value) || value['insight'] === undefined) return false;
    if (!('intimidation' in value) || value['intimidation'] === undefined) return false;
    if (!('investigation' in value) || value['investigation'] === undefined) return false;
    if (!('medicine' in value) || value['medicine'] === undefined) return false;
    if (!('nature' in value) || value['nature'] === undefined) return false;
    if (!('perception' in value) || value['perception'] === undefined) return false;
    if (!('performance' in value) || value['performance'] === undefined) return false;
    if (!('persuasion' in value) || value['persuasion'] === undefined) return false;
    if (!('religion' in value) || value['religion'] === undefined) return false;
    if ((!('sleightOfHand' in value) && !('sleight_of_hand' in value)) || (value['sleightOfHand'] === undefined && value['sleight_of_hand'] === undefined)) return false;
    if (!('stealth' in value) || value['stealth'] === undefined) return false;
    if (!('survival' in value) || value['survival'] === undefined) return false;
    return true;
}

export function SkillBonusesFromJSON(json: any): SkillBonuses {
    return SkillBonusesFromJSONTyped(json, false);
}

export function SkillBonusesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillBonuses {
    if (json == null) {
        return json;
    }
    return {
        
        'acrobatics': json['acrobatics'],
        'animalHandling': json['animal_handling'],
        'arcana': json['arcana'],
        'athletics': json['athletics'],
        'deception': json['deception'],
        'history': json['history'],
        'insight': json['insight'],
        'intimidation': json['intimidation'],
        'investigation': json['investigation'],
        'medicine': json['medicine'],
        'nature': json['nature'],
        'perception': json['perception'],
        'performance': json['performance'],
        'persuasion': json['persuasion'],
        'religion': json['religion'],
        'sleightOfHand': json['sleight_of_hand'],
        'stealth': json['stealth'],
        'survival': json['survival'],
    };
}

export function SkillBonusesToJSON(json: any): SkillBonuses {
    return SkillBonusesToJSONTyped(json, false);
}

export function SkillBonusesToJSONTyped(value?: SkillBonuses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acrobatics': value['acrobatics'],
        'animal_handling': value['animalHandling'],
        'arcana': value['arcana'],
        'athletics': value['athletics'],
        'deception': value['deception'],
        'history': value['history'],
        'insight': value['insight'],
        'intimidation': value['intimidation'],
        'investigation': value['investigation'],
        'medicine': value['medicine'],
        'nature': value['nature'],
        'perception': value['perception'],
        'performance': value['performance'],
        'persuasion': value['persuasion'],
        'religion': value['religion'],
        'sleight_of_hand': value['sleightOfHand'],
        'stealth': value['stealth'],
        'survival': value['survival'],
    };
}

