/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Speed
 */
export interface Speed {
    /**
     * 
     * @type {string}
     * @memberof Speed
     */
    readonly walk: string;
    /**
     * 
     * @type {string}
     * @memberof Speed
     */
    readonly fly: string;
    /**
     * 
     * @type {string}
     * @memberof Speed
     */
    readonly swim: string;
    /**
     * 
     * @type {string}
     * @memberof Speed
     */
    readonly climb: string;
    /**
     * 
     * @type {string}
     * @memberof Speed
     */
    readonly burrow: string;
    /**
     * 
     * @type {boolean}
     * @memberof Speed
     */
    hover: boolean;
}

/**
 * Check if a given object implements the Speed interface.
 */
export function instanceOfSpeed(value: object): value is Speed {
    if (!('walk' in value) || value['walk'] === undefined) return false;
    if (!('fly' in value) || value['fly'] === undefined) return false;
    if (!('swim' in value) || value['swim'] === undefined) return false;
    if (!('climb' in value) || value['climb'] === undefined) return false;
    if (!('burrow' in value) || value['burrow'] === undefined) return false;
    if (!('hover' in value) || value['hover'] === undefined) return false;
    return true;
}

export function SpeedFromJSON(json: any): Speed {
    return SpeedFromJSONTyped(json, false);
}

export function SpeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Speed {
    if (json == null) {
        return json;
    }
    return {
        
        'walk': json['walk'],
        'fly': json['fly'],
        'swim': json['swim'],
        'climb': json['climb'],
        'burrow': json['burrow'],
        'hover': json['hover'],
    };
}

export function SpeedToJSON(json: any): Speed {
    return SpeedToJSONTyped(json, false);
}

export function SpeedToJSONTyped(value?: Omit<Speed, 'walk'|'fly'|'swim'|'climb'|'burrow'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hover': value['hover'],
    };
}

