/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrossReferences } from './CrossReferences';
import {
    CrossReferencesFromJSON,
    CrossReferencesFromJSONTyped,
    CrossReferencesToJSON,
    CrossReferencesToJSONTyped,
} from './CrossReferences';
import type { DocumentSummary } from './DocumentSummary';
import {
    DocumentSummaryFromJSON,
    DocumentSummaryFromJSONTyped,
    DocumentSummaryToJSON,
    DocumentSummaryToJSONTyped,
} from './DocumentSummary';
import type { CharacterClassSummary } from './CharacterClassSummary';
import {
    CharacterClassSummaryFromJSON,
    CharacterClassSummaryFromJSONTyped,
    CharacterClassSummaryToJSON,
    CharacterClassSummaryToJSONTyped,
} from './CharacterClassSummary';
import type { SpellCastingOption } from './SpellCastingOption';
import {
    SpellCastingOptionFromJSON,
    SpellCastingOptionFromJSONTyped,
    SpellCastingOptionToJSON,
    SpellCastingOptionToJSONTyped,
} from './SpellCastingOption';
import type { SpellSchoolSummary } from './SpellSchoolSummary';
import {
    SpellSchoolSummaryFromJSON,
    SpellSchoolSummaryFromJSONTyped,
    SpellSchoolSummaryToJSON,
    SpellSchoolSummaryToJSONTyped,
} from './SpellSchoolSummary';

/**
 * Much of the logic included in the GameContentSerializer is intended to
 * support manipulating data returned by the serializer via query parameters.
 * @export
 * @interface Spell
 */
export interface Spell {
    /**
     * Unique key for the Item.
     * @type {string}
     * @memberof Spell
     */
    readonly key: string;
    /**
     * 
     * @type {DocumentSummary}
     * @memberof Spell
     */
    document: DocumentSummary;
    /**
     * 
     * @type {Array<SpellCastingOption>}
     * @memberof Spell
     */
    castingOptions: Array<SpellCastingOption>;
    /**
     * 
     * @type {SpellSchoolSummary}
     * @memberof Spell
     */
    school: SpellSchoolSummary;
    /**
     * 
     * @type {Array<CharacterClassSummary>}
     * @memberof Spell
     */
    classes: Array<CharacterClassSummary>;
    /**
     * 
     * @type {string}
     * @memberof Spell
     */
    readonly rangeUnit: string;
    /**
     * 
     * @type {string}
     * @memberof Spell
     */
    readonly shapeSizeUnit: string;
    /**
     * Name of the item.
     * @type {string}
     * @memberof Spell
     */
    name: string;
    /**
     * Description of the game content item. Markdown.
     * @type {string}
     * @memberof Spell
     */
    desc?: string;
    /**
     * Integer representing the default slot level required by the spell.
     * @type {number}
     * @memberof Spell
     */
    level: number;
    /**
     * Description of casting the spell at a different level.
     * @type {string}
     * @memberof Spell
     */
    higherLevel?: string;
    /**
     * Spell target type key.
     * 
     * * `creature` - Creature
     * * `object` - Object
     * * `point` - Point
     * * `area` - Area
     * @type {SpellTargetTypeEnum}
     * @memberof Spell
     */
    targetType?: SpellTargetTypeEnum | null;
    /**
     * Spell target range.
     * @type {string}
     * @memberof Spell
     */
    rangeText: string;
    /**
     * Used to measure distance.
     * @type {number}
     * @memberof Spell
     */
    range?: number | null;
    /**
     * Whether or not the spell can be cast as a ritual.
     * @type {boolean}
     * @memberof Spell
     */
    ritual?: boolean;
    /**
     * Casting time key, such as 'action'
     * 
     * * `reaction` - Reaction
     * * `bonus-action` - 1 Bonus Action
     * * `action` - 1 Action
     * * `turn` - 1 Turn
     * * `round` - 1 Round
     * * `1minute` - 1 Minute
     * * `5minutes` - 5 Minutes
     * * `10minutes` - 10 Minutes
     * * `1hour` - 1 Hour
     * * `4hours` - 4 Hours
     * * `7hours` - 7 Hours
     * * `8hours` - 8 Hours
     * * `9hours` - 9 Hours
     * * `12hours` - 12 Hours
     * * `24hours` - 24 Hours
     * * `1week` - 1 Week
     * @type {SpellCastingTimeEnum}
     * @memberof Spell
     */
    castingTime: SpellCastingTimeEnum;
    /**
     * The conditions describing when a reaction spell can be cast
     * @type {string}
     * @memberof Spell
     */
    reactionCondition?: string | null;
    /**
     * Whether or not casting the spell requires a verbal component.
     * @type {boolean}
     * @memberof Spell
     */
    verbal?: boolean;
    /**
     * Whether or not casting the spell requires a verbal component.
     * @type {boolean}
     * @memberof Spell
     */
    somatic?: boolean;
    /**
     * Whether or not casting the spell requires a verbal component.
     * @type {boolean}
     * @memberof Spell
     */
    material?: boolean;
    /**
     * Description of the material specified for the spell.
     * @type {string}
     * @memberof Spell
     */
    materialSpecified?: string;
    /**
     * Number representing the cost of the materials of the spell.
     * @type {string}
     * @memberof Spell
     */
    materialCost?: string | null;
    /**
     * Whether or the material component is consumed during the casting.
     * @type {boolean}
     * @memberof Spell
     */
    materialConsumed?: boolean;
    /**
     * Integer representing the count of targets.
     * @type {number}
     * @memberof Spell
     */
    targetCount?: number | null;
    /**
     * Given the spell requires a saving throw, which ability is targeted. Empty string if no saving throw.
     * @type {string}
     * @memberof Spell
     */
    savingThrowAbility?: string;
    /**
     * Whether or not the spell effect requires an attack roll.
     * @type {boolean}
     * @memberof Spell
     */
    attackRoll?: boolean;
    /**
     * The damage roll for the field in dice notation. Empty string if no roll.
     * @type {string}
     * @memberof Spell
     */
    damageRoll?: string;
    /**
     * The types of damage done by the spell in a list.
     * @type {any}
     * @memberof Spell
     */
    damageTypes?: any | null;
    /**
     * Description of the duration of the effect such as "instantaneous" or "1 minute"
     * 
     * * `instantaneous` - instantaneous
     * * `instantaneous or special` - instantaneous or special
     * * `1 turn` - 1 turn
     * * `1 round` - 1 round
     * * `concentration + 1 round` - concentration + 1 round
     * * `2 rounds` - 2 rounds
     * * `3 rounds` - 3 rounds
     * * `4 rounds` - 4 rounds
     * * `1d4+2 rounds` - 1d4+2 rounds
     * * `5 rounds` - 5 rounds
     * * `6 rounds` - 6 rounds
     * * `10 rounds` - 10 rounds
     * * `up to 1 minute` - up to 1 minute
     * * `1 minute` - 1 minute
     * * `1 minute, or until expended` - 1 minute, or until expended
     * * `1 minute, until expended` - 1 minute, until expended
     * * `5 minutes` - 5 minutes
     * * `10 minutes` - 10 minutes
     * * `1 minute or 1 hour` - 1 minute or 1 hour
     * * `up to 1 hour` - up to 1 hour
     * * `1 hour` - 1 hour
     * * `1 hour or until triggered` - 1 hour or until triggered
     * * `2 hours` - 2 hours
     * * `3 hours` - 3 hours
     * * `1d10 hours` - 1d10 hours
     * * `6 hours` - 6 hours
     * * `2-12 hours` - 2-12 hours
     * * `up to 8 hours` - up to 8 hours
     * * `8 hours` - 8 hours
     * * `1 hour/caster level` - 1 hour/caster level
     * * `10 hours` - 10 hours
     * * `12 hours` - 12 hours
     * * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw
     * * `24 hours` - 24 hours
     * * `1 day` - 1 day
     * * `3 days` - 3 days
     * * `5 days` - 5 days
     * * `7 days` - 7 days
     * * `10 days` - 10 days
     * * `13 days` - 13 days
     * * `30 days` - 30 days
     * * `1 year` - 1 year
     * * `special` - special
     * * `until dispelled or destroyed` - until dispelled or destroyed
     * * `until destroyed` - until destroyed
     * * `until dispelled` - until dispelled
     * * `until cured or dispelled` - until cured or dispelled
     * * `until dispelled or triggered` - until dispelled or triggered
     * * `permanent until discharged` - permanent until discharged
     * * `permanent; one generation` - permanent; one generation
     * * `permanent` - permanent
     * @type {SpellDurationEnum}
     * @memberof Spell
     */
    duration: SpellDurationEnum;
    /**
     * The shape of the area of effect.
     * 
     * * `cone` - Cone
     * * `cube` - Cube
     * * `cylinder` - Cylinder
     * * `line` - Line
     * * `sphere` - sphere
     * @type {SpellShapeTypeEnum}
     * @memberof Spell
     */
    shapeType?: SpellShapeTypeEnum | null;
    /**
     * Used to measure distance.
     * @type {number}
     * @memberof Spell
     */
    shapeSize?: number | null;
    /**
     * Whether the effect requires concentration to be maintained.
     * @type {boolean}
     * @memberof Spell
     */
    concentration?: boolean;
    /**
     * 
     * @type {CrossReferences}
     * @memberof Spell
     */
    readonly crossreferences: CrossReferences;
}


/**
 * @export
 */
export const SpellTargetTypeEnum = {
    Creature: 'creature',
    Object: 'object',
    Point: 'point',
    Area: 'area',
    Empty: ''
} as const;
export type SpellTargetTypeEnum = typeof SpellTargetTypeEnum[keyof typeof SpellTargetTypeEnum];

/**
 * @export
 */
export const SpellCastingTimeEnum = {
    Reaction: 'reaction',
    BonusAction: 'bonus-action',
    Action: 'action',
    Turn: 'turn',
    Round: 'round',
    _1minute: '1minute',
    _5minutes: '5minutes',
    _10minutes: '10minutes',
    _1hour: '1hour',
    _4hours: '4hours',
    _7hours: '7hours',
    _8hours: '8hours',
    _9hours: '9hours',
    _12hours: '12hours',
    _24hours: '24hours',
    _1week: '1week'
} as const;
export type SpellCastingTimeEnum = typeof SpellCastingTimeEnum[keyof typeof SpellCastingTimeEnum];

/**
 * @export
 */
export const SpellDurationEnum = {
    Instantaneous: 'instantaneous',
    InstantaneousOrSpecial: 'instantaneous or special',
    _1Turn: '1 turn',
    _1Round: '1 round',
    Concentration1Round: 'concentration + 1 round',
    _2Rounds: '2 rounds',
    _3Rounds: '3 rounds',
    _4Rounds: '4 rounds',
    _1d42Rounds: '1d4+2 rounds',
    _5Rounds: '5 rounds',
    _6Rounds: '6 rounds',
    _10Rounds: '10 rounds',
    UpTo1Minute: 'up to 1 minute',
    _1Minute: '1 minute',
    _1MinuteOrUntilExpended: '1 minute, or until expended',
    _1MinuteUntilExpended: '1 minute, until expended',
    _5Minutes: '5 minutes',
    _10Minutes: '10 minutes',
    _1MinuteOr1Hour: '1 minute or 1 hour',
    UpTo1Hour: 'up to 1 hour',
    _1Hour: '1 hour',
    _1HourOrUntilTriggered: '1 hour or until triggered',
    _2Hours: '2 hours',
    _3Hours: '3 hours',
    _1d10Hours: '1d10 hours',
    _6Hours: '6 hours',
    _212Hours: '2-12 hours',
    UpTo8Hours: 'up to 8 hours',
    _8Hours: '8 hours',
    _1HourCasterLevel: '1 hour/caster level',
    _10Hours: '10 hours',
    _12Hours: '12 hours',
    _24HoursOrUntilTheTargetAttemptsAThirdDeathSavingThrow: '24 hours or until the target attempts a third death saving throw',
    _24Hours: '24 hours',
    _1Day: '1 day',
    _3Days: '3 days',
    _5Days: '5 days',
    _7Days: '7 days',
    _10Days: '10 days',
    _13Days: '13 days',
    _30Days: '30 days',
    _1Year: '1 year',
    Special: 'special',
    UntilDispelledOrDestroyed: 'until dispelled or destroyed',
    UntilDestroyed: 'until destroyed',
    UntilDispelled: 'until dispelled',
    UntilCuredOrDispelled: 'until cured or dispelled',
    UntilDispelledOrTriggered: 'until dispelled or triggered',
    PermanentUntilDischarged: 'permanent until discharged',
    PermanentOneGeneration: 'permanent; one generation',
    Permanent: 'permanent'
} as const;
export type SpellDurationEnum = typeof SpellDurationEnum[keyof typeof SpellDurationEnum];

/**
 * @export
 */
export const SpellShapeTypeEnum = {
    Cone: 'cone',
    Cube: 'cube',
    Cylinder: 'cylinder',
    Line: 'line',
    Sphere: 'sphere',
    Empty: ''
} as const;
export type SpellShapeTypeEnum = typeof SpellShapeTypeEnum[keyof typeof SpellShapeTypeEnum];


/**
 * Check if a given object implements the Spell interface.
 */
export function instanceOfSpell(value: object): value is Spell {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('document' in value) || value['document'] === undefined) return false;
    if ((!('castingOptions' in value) && !('casting_options' in value)) || (value['castingOptions'] === undefined && value['casting_options'] === undefined)) return false;
    if (!('school' in value) || value['school'] === undefined) return false;
    if (!('classes' in value) || value['classes'] === undefined) return false;
    if ((!('rangeUnit' in value) && !('range_unit' in value)) || (value['rangeUnit'] === undefined && value['range_unit'] === undefined)) return false;
    if ((!('shapeSizeUnit' in value) && !('shape_size_unit' in value)) || (value['shapeSizeUnit'] === undefined && value['shape_size_unit'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if ((!('rangeText' in value) && !('range_text' in value)) || (value['rangeText'] === undefined && value['range_text'] === undefined)) return false;
    if ((!('castingTime' in value) && !('casting_time' in value)) || (value['castingTime'] === undefined && value['casting_time'] === undefined)) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('crossreferences' in value) || value['crossreferences'] === undefined) return false;
    return true;
}

export function SpellFromJSON(json: any): Spell {
    return SpellFromJSONTyped(json, false);
}

export function SpellFromJSONTyped(json: any, ignoreDiscriminator: boolean): Spell {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'document': DocumentSummaryFromJSON(json['document']),
        'castingOptions': ((json['casting_options'] as Array<any>).map(SpellCastingOptionFromJSON)),
        'school': SpellSchoolSummaryFromJSON(json['school']),
        'classes': ((json['classes'] as Array<any>).map(CharacterClassSummaryFromJSON)),
        'rangeUnit': json['range_unit'],
        'shapeSizeUnit': json['shape_size_unit'],
        'name': json['name'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'level': json['level'],
        'higherLevel': json['higher_level'] == null ? undefined : json['higher_level'],
        'targetType': json['target_type'] == null ? undefined : json['target_type'],
        'rangeText': json['range_text'],
        'range': json['range'] == null ? undefined : json['range'],
        'ritual': json['ritual'] == null ? undefined : json['ritual'],
        'castingTime': json['casting_time'],
        'reactionCondition': json['reaction_condition'] == null ? undefined : json['reaction_condition'],
        'verbal': json['verbal'] == null ? undefined : json['verbal'],
        'somatic': json['somatic'] == null ? undefined : json['somatic'],
        'material': json['material'] == null ? undefined : json['material'],
        'materialSpecified': json['material_specified'] == null ? undefined : json['material_specified'],
        'materialCost': json['material_cost'] == null ? undefined : json['material_cost'],
        'materialConsumed': json['material_consumed'] == null ? undefined : json['material_consumed'],
        'targetCount': json['target_count'] == null ? undefined : json['target_count'],
        'savingThrowAbility': json['saving_throw_ability'] == null ? undefined : json['saving_throw_ability'],
        'attackRoll': json['attack_roll'] == null ? undefined : json['attack_roll'],
        'damageRoll': json['damage_roll'] == null ? undefined : json['damage_roll'],
        'damageTypes': json['damage_types'] == null ? undefined : json['damage_types'],
        'duration': json['duration'],
        'shapeType': json['shape_type'] == null ? undefined : json['shape_type'],
        'shapeSize': json['shape_size'] == null ? undefined : json['shape_size'],
        'concentration': json['concentration'] == null ? undefined : json['concentration'],
        'crossreferences': CrossReferencesFromJSON(json['crossreferences']),
    };
}

export function SpellToJSON(json: any): Spell {
    return SpellToJSONTyped(json, false);
}

export function SpellToJSONTyped(value?: Omit<Spell, 'key'|'range_unit'|'shape_size_unit'|'crossreferences'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document': DocumentSummaryToJSON(value['document']),
        'casting_options': ((value['castingOptions'] as Array<any>).map(SpellCastingOptionToJSON)),
        'school': SpellSchoolSummaryToJSON(value['school']),
        'classes': ((value['classes'] as Array<any>).map(CharacterClassSummaryToJSON)),
        'name': value['name'],
        'desc': value['desc'],
        'level': value['level'],
        'higher_level': value['higherLevel'],
        'target_type': value['targetType'],
        'range_text': value['rangeText'],
        'range': value['range'],
        'ritual': value['ritual'],
        'casting_time': value['castingTime'],
        'reaction_condition': value['reactionCondition'],
        'verbal': value['verbal'],
        'somatic': value['somatic'],
        'material': value['material'],
        'material_specified': value['materialSpecified'],
        'material_cost': value['materialCost'],
        'material_consumed': value['materialConsumed'],
        'target_count': value['targetCount'],
        'saving_throw_ability': value['savingThrowAbility'],
        'attack_roll': value['attackRoll'],
        'damage_roll': value['damageRoll'],
        'damage_types': value['damageTypes'],
        'duration': value['duration'],
        'shape_type': value['shapeType'],
        'shape_size': value['shapeSize'],
        'concentration': value['concentration'],
    };
}

