/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpellCastingOption
 */
export interface SpellCastingOption {
    /**
     * * `default` - Default
     * * `ritual` - Ritual
     * * `player_level_1` - Player Level 1
     * * `player_level_2` - Player Level 2
     * * `player_level_3` - Player Level 3
     * * `player_level_4` - Player Level 4
     * * `player_level_5` - Player Level 5
     * * `player_level_6` - Player Level 6
     * * `player_level_7` - Player Level 7
     * * `player_level_8` - Player Level 8
     * * `player_level_9` - Player Level 9
     * * `player_level_10` - Player Level 10
     * * `player_level_11` - Player Level 11
     * * `player_level_12` - Player Level 12
     * * `player_level_13` - Player Level 13
     * * `player_level_14` - Player Level 14
     * * `player_level_15` - Player Level 15
     * * `player_level_16` - Player Level 16
     * * `player_level_17` - Player Level 17
     * * `player_level_18` - Player Level 18
     * * `player_level_19` - Player Level 19
     * * `player_level_20` - Player Level 20
     * * `slot_level_1` - Spell Slot Level 1
     * * `slot_level_2` - Spell SlotLevel 2
     * * `slot_level_3` - Spell Slot Level 3
     * * `slot_level_4` - Spell Slot Level 4
     * * `slot_level_5` - Spell Slot Level 5
     * * `slot_level_6` - Spell Slot Level 6
     * * `slot_level_7` - Spell Slot Level 7
     * * `slot_level_8` - Spell Slot Level 8
     * * `slot_level_9` - Spell Slot Level 9
     * @type {SpellCastingOptionTypeEnum}
     * @memberof SpellCastingOption
     */
    type: SpellCastingOptionTypeEnum;
    /**
     * The damage roll for the field in dice notation. Empty string if no roll.
     * @type {string}
     * @memberof SpellCastingOption
     */
    damageRoll?: string | null;
    /**
     * Integer representing the count of targets.
     * @type {number}
     * @memberof SpellCastingOption
     */
    targetCount?: number | null;
    /**
     * Description of the duration of the effect such as "instantaneous" or "Up to 1 minute"
     * @type {string}
     * @memberof SpellCastingOption
     */
    duration?: string | null;
    /**
     * Description of the range of the spell.
     * @type {string}
     * @memberof SpellCastingOption
     */
    range?: string | null;
    /**
     * Whether the effect requires concentration to be maintained.
     * @type {boolean}
     * @memberof SpellCastingOption
     */
    concentration?: boolean | null;
    /**
     * Used to measure distance.
     * @type {number}
     * @memberof SpellCastingOption
     */
    shapeSize?: number | null;
    /**
     * Description of complex casting option effects that cannot be captured in other fields.
     * @type {string}
     * @memberof SpellCastingOption
     */
    desc?: string | null;
}


/**
 * @export
 */
export const SpellCastingOptionTypeEnum = {
    Default: 'default',
    Ritual: 'ritual',
    PlayerLevel1: 'player_level_1',
    PlayerLevel2: 'player_level_2',
    PlayerLevel3: 'player_level_3',
    PlayerLevel4: 'player_level_4',
    PlayerLevel5: 'player_level_5',
    PlayerLevel6: 'player_level_6',
    PlayerLevel7: 'player_level_7',
    PlayerLevel8: 'player_level_8',
    PlayerLevel9: 'player_level_9',
    PlayerLevel10: 'player_level_10',
    PlayerLevel11: 'player_level_11',
    PlayerLevel12: 'player_level_12',
    PlayerLevel13: 'player_level_13',
    PlayerLevel14: 'player_level_14',
    PlayerLevel15: 'player_level_15',
    PlayerLevel16: 'player_level_16',
    PlayerLevel17: 'player_level_17',
    PlayerLevel18: 'player_level_18',
    PlayerLevel19: 'player_level_19',
    PlayerLevel20: 'player_level_20',
    SlotLevel1: 'slot_level_1',
    SlotLevel2: 'slot_level_2',
    SlotLevel3: 'slot_level_3',
    SlotLevel4: 'slot_level_4',
    SlotLevel5: 'slot_level_5',
    SlotLevel6: 'slot_level_6',
    SlotLevel7: 'slot_level_7',
    SlotLevel8: 'slot_level_8',
    SlotLevel9: 'slot_level_9'
} as const;
export type SpellCastingOptionTypeEnum = typeof SpellCastingOptionTypeEnum[keyof typeof SpellCastingOptionTypeEnum];


/**
 * Check if a given object implements the SpellCastingOption interface.
 */
export function instanceOfSpellCastingOption(value: object): value is SpellCastingOption {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SpellCastingOptionFromJSON(json: any): SpellCastingOption {
    return SpellCastingOptionFromJSONTyped(json, false);
}

export function SpellCastingOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpellCastingOption {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'damageRoll': json['damage_roll'] == null ? undefined : json['damage_roll'],
        'targetCount': json['target_count'] == null ? undefined : json['target_count'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'range': json['range'] == null ? undefined : json['range'],
        'concentration': json['concentration'] == null ? undefined : json['concentration'],
        'shapeSize': json['shape_size'] == null ? undefined : json['shape_size'],
        'desc': json['desc'] == null ? undefined : json['desc'],
    };
}

export function SpellCastingOptionToJSON(json: any): SpellCastingOption {
    return SpellCastingOptionToJSONTyped(json, false);
}

export function SpellCastingOptionToJSONTyped(value?: SpellCastingOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'damage_roll': value['damageRoll'],
        'target_count': value['targetCount'],
        'duration': value['duration'],
        'range': value['range'],
        'concentration': value['concentration'],
        'shape_size': value['shapeSize'],
        'desc': value['desc'],
    };
}

