"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from open5e.models.paginated_spell_list import PaginatedSpellList
from open5e.models.spell import Spell

from open5e.api_client import ApiClient, RequestSerialized
from open5e.api_response import ApiResponse
from open5e.rest import RESTResponseType


class SpellsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def spells_list(
        self,
        key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        key__iexact: Optional[StrictStr] = None,
        key: Optional[StrictStr] = None,
        name__iexact: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        name__contains: Optional[StrictStr] = None,
        name__icontains: Optional[StrictStr] = None,
        document__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        document__key__iexact: Optional[StrictStr] = None,
        document__key: Optional[StrictStr] = None,
        document__gamesystem__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        document__gamesystem__key__iexact: Optional[StrictStr] = None,
        document__gamesystem__key: Optional[StrictStr] = None,
        classes__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        classes__key__iexact: Optional[StrictStr] = None,
        classes__key: Optional[StrictStr] = None,
        classes__name__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        level: Optional[StrictInt] = None,
        level__range: Annotated[Optional[List[StrictInt]], Field(description="Multiple values may be separated by commas.")] = None,
        level__gt: Optional[StrictInt] = None,
        level__gte: Optional[StrictInt] = None,
        level__lt: Optional[StrictInt] = None,
        level__lte: Optional[StrictInt] = None,
        range: Optional[StrictInt] = None,
        range__range: Annotated[Optional[List[StrictInt]], Field(description="Multiple values may be separated by commas.")] = None,
        range__gt: Optional[StrictInt] = None,
        range__gte: Optional[StrictInt] = None,
        range__lt: Optional[StrictInt] = None,
        range__lte: Optional[StrictInt] = None,
        school__key: Optional[StrictStr] = None,
        school__name__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        school__name__iexact: Optional[StrictStr] = None,
        school__name: Optional[StrictStr] = None,
        duration__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        duration__iexact: Optional[StrictStr] = None,
        duration: Annotated[Optional[StrictStr], Field(description="Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"  * `instantaneous` - instantaneous * `instantaneous or special` - instantaneous or special * `1 turn` - 1 turn * `1 round` - 1 round * `concentration + 1 round` - concentration + 1 round * `2 rounds` - 2 rounds * `3 rounds` - 3 rounds * `4 rounds` - 4 rounds * `1d4+2 rounds` - 1d4+2 rounds * `5 rounds` - 5 rounds * `6 rounds` - 6 rounds * `10 rounds` - 10 rounds * `up to 1 minute` - up to 1 minute * `1 minute` - 1 minute * `1 minute, or until expended` - 1 minute, or until expended * `1 minute, until expended` - 1 minute, until expended * `1 minute` - 1 minute * `5 minutes` - 5 minutes * `10 minutes` - 10 minutes * `1 minute or 1 hour` - 1 minute or 1 hour * `up to 1 hour` - up to 1 hour * `1 hour` - 1 hour * `1 hour or until triggered` - 1 hour or until triggered * `2 hours` - 2 hours * `3 hours` - 3 hours * `1d10 hours` - 1d10 hours * `6 hours` - 6 hours * `2-12 hours` - 2-12 hours * `up to 8 hours` - up to 8 hours * `8 hours` - 8 hours * `1 hour/caster level` - 1 hour/caster level * `10 hours` - 10 hours * `12 hours` - 12 hours * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw * `24 hours` - 24 hours * `1 day` - 1 day * `3 days` - 3 days * `5 days` - 5 days * `7 days` - 7 days * `10 days` - 10 days * `13 days` - 13 days * `30 days` - 30 days * `1 year` - 1 year * `special` - special * `until dispelled or destroyed` - until dispelled or destroyed * `until destroyed` - until destroyed * `until dispelled` - until dispelled * `until cured or dispelled` - until cured or dispelled * `until dispelled or triggered` - until dispelled or triggered * `permanent until discharged` - permanent until discharged * `permanent; one generation` - permanent; one generation * `permanent` - permanent")] = None,
        concentration: Optional[StrictBool] = None,
        verbal: Optional[StrictBool] = None,
        somatic: Optional[StrictBool] = None,
        material: Optional[StrictBool] = None,
        material_consumed: Optional[StrictBool] = None,
        casting_time__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        casting_time__iexact: Optional[StrictStr] = None,
        casting_time: Annotated[Optional[StrictStr], Field(description="Casting time key, such as 'action'  * `reaction` - Reaction * `bonus-action` - 1 Bonus Action * `action` - 1 Action * `turn` - 1 Turn * `round` - 1 Round * `1minute` - 1 Minute * `5minutes` - 5 Minutes * `10minutes` - 10 Minutes * `1hour` - 1 Hour * `4hours` - 4 Hours * `7hours` - 7 Hours * `8hours` - 8 Hours * `9hours` - 9 Hours * `12hours` - 12 Hours * `24hours` - 24 Hours * `1week` - 1 Week")] = None,
        ordering: Annotated[Optional[StrictStr], Field(description="Which field to use when ordering the results.")] = None,
        search: Annotated[Optional[StrictStr], Field(description="A search term.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="A page number within the paginated result set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaginatedSpellList:
        """spells_list

        list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.

        :param key__in: Multiple values may be separated by commas.
        :type key__in: List[str]
        :param key__iexact:
        :type key__iexact: str
        :param key:
        :type key: str
        :param name__iexact:
        :type name__iexact: str
        :param name:
        :type name: str
        :param name__contains:
        :type name__contains: str
        :param name__icontains:
        :type name__icontains: str
        :param document__key__in: Multiple values may be separated by commas.
        :type document__key__in: List[str]
        :param document__key__iexact:
        :type document__key__iexact: str
        :param document__key:
        :type document__key: str
        :param document__gamesystem__key__in: Multiple values may be separated by commas.
        :type document__gamesystem__key__in: List[str]
        :param document__gamesystem__key__iexact:
        :type document__gamesystem__key__iexact: str
        :param document__gamesystem__key:
        :type document__gamesystem__key: str
        :param classes__key__in: Multiple values may be separated by commas.
        :type classes__key__in: List[str]
        :param classes__key__iexact:
        :type classes__key__iexact: str
        :param classes__key:
        :type classes__key: str
        :param classes__name__in: Multiple values may be separated by commas.
        :type classes__name__in: List[str]
        :param level:
        :type level: int
        :param level__range: Multiple values may be separated by commas.
        :type level__range: List[int]
        :param level__gt:
        :type level__gt: int
        :param level__gte:
        :type level__gte: int
        :param level__lt:
        :type level__lt: int
        :param level__lte:
        :type level__lte: int
        :param range:
        :type range: int
        :param range__range: Multiple values may be separated by commas.
        :type range__range: List[int]
        :param range__gt:
        :type range__gt: int
        :param range__gte:
        :type range__gte: int
        :param range__lt:
        :type range__lt: int
        :param range__lte:
        :type range__lte: int
        :param school__key:
        :type school__key: str
        :param school__name__in: Multiple values may be separated by commas.
        :type school__name__in: List[str]
        :param school__name__iexact:
        :type school__name__iexact: str
        :param school__name:
        :type school__name: str
        :param duration__in: Multiple values may be separated by commas.
        :type duration__in: List[str]
        :param duration__iexact:
        :type duration__iexact: str
        :param duration: Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"  * `instantaneous` - instantaneous * `instantaneous or special` - instantaneous or special * `1 turn` - 1 turn * `1 round` - 1 round * `concentration + 1 round` - concentration + 1 round * `2 rounds` - 2 rounds * `3 rounds` - 3 rounds * `4 rounds` - 4 rounds * `1d4+2 rounds` - 1d4+2 rounds * `5 rounds` - 5 rounds * `6 rounds` - 6 rounds * `10 rounds` - 10 rounds * `up to 1 minute` - up to 1 minute * `1 minute` - 1 minute * `1 minute, or until expended` - 1 minute, or until expended * `1 minute, until expended` - 1 minute, until expended * `1 minute` - 1 minute * `5 minutes` - 5 minutes * `10 minutes` - 10 minutes * `1 minute or 1 hour` - 1 minute or 1 hour * `up to 1 hour` - up to 1 hour * `1 hour` - 1 hour * `1 hour or until triggered` - 1 hour or until triggered * `2 hours` - 2 hours * `3 hours` - 3 hours * `1d10 hours` - 1d10 hours * `6 hours` - 6 hours * `2-12 hours` - 2-12 hours * `up to 8 hours` - up to 8 hours * `8 hours` - 8 hours * `1 hour/caster level` - 1 hour/caster level * `10 hours` - 10 hours * `12 hours` - 12 hours * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw * `24 hours` - 24 hours * `1 day` - 1 day * `3 days` - 3 days * `5 days` - 5 days * `7 days` - 7 days * `10 days` - 10 days * `13 days` - 13 days * `30 days` - 30 days * `1 year` - 1 year * `special` - special * `until dispelled or destroyed` - until dispelled or destroyed * `until destroyed` - until destroyed * `until dispelled` - until dispelled * `until cured or dispelled` - until cured or dispelled * `until dispelled or triggered` - until dispelled or triggered * `permanent until discharged` - permanent until discharged * `permanent; one generation` - permanent; one generation * `permanent` - permanent
        :type duration: str
        :param concentration:
        :type concentration: bool
        :param verbal:
        :type verbal: bool
        :param somatic:
        :type somatic: bool
        :param material:
        :type material: bool
        :param material_consumed:
        :type material_consumed: bool
        :param casting_time__in: Multiple values may be separated by commas.
        :type casting_time__in: List[str]
        :param casting_time__iexact:
        :type casting_time__iexact: str
        :param casting_time: Casting time key, such as 'action'  * `reaction` - Reaction * `bonus-action` - 1 Bonus Action * `action` - 1 Action * `turn` - 1 Turn * `round` - 1 Round * `1minute` - 1 Minute * `5minutes` - 5 Minutes * `10minutes` - 10 Minutes * `1hour` - 1 Hour * `4hours` - 4 Hours * `7hours` - 7 Hours * `8hours` - 8 Hours * `9hours` - 9 Hours * `12hours` - 12 Hours * `24hours` - 24 Hours * `1week` - 1 Week
        :type casting_time: str
        :param ordering: Which field to use when ordering the results.
        :type ordering: str
        :param search: A search term.
        :type search: str
        :param page: A page number within the paginated result set.
        :type page: int
        :param limit: Number of results to return per page.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._spells_list_serialize(
            key__in=key__in,
            key__iexact=key__iexact,
            key=key,
            name__iexact=name__iexact,
            name=name,
            name__contains=name__contains,
            name__icontains=name__icontains,
            document__key__in=document__key__in,
            document__key__iexact=document__key__iexact,
            document__key=document__key,
            document__gamesystem__key__in=document__gamesystem__key__in,
            document__gamesystem__key__iexact=document__gamesystem__key__iexact,
            document__gamesystem__key=document__gamesystem__key,
            classes__key__in=classes__key__in,
            classes__key__iexact=classes__key__iexact,
            classes__key=classes__key,
            classes__name__in=classes__name__in,
            level=level,
            level__range=level__range,
            level__gt=level__gt,
            level__gte=level__gte,
            level__lt=level__lt,
            level__lte=level__lte,
            range=range,
            range__range=range__range,
            range__gt=range__gt,
            range__gte=range__gte,
            range__lt=range__lt,
            range__lte=range__lte,
            school__key=school__key,
            school__name__in=school__name__in,
            school__name__iexact=school__name__iexact,
            school__name=school__name,
            duration__in=duration__in,
            duration__iexact=duration__iexact,
            duration=duration,
            concentration=concentration,
            verbal=verbal,
            somatic=somatic,
            material=material,
            material_consumed=material_consumed,
            casting_time__in=casting_time__in,
            casting_time__iexact=casting_time__iexact,
            casting_time=casting_time,
            ordering=ordering,
            search=search,
            page=page,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedSpellList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def spells_list_with_http_info(
        self,
        key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        key__iexact: Optional[StrictStr] = None,
        key: Optional[StrictStr] = None,
        name__iexact: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        name__contains: Optional[StrictStr] = None,
        name__icontains: Optional[StrictStr] = None,
        document__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        document__key__iexact: Optional[StrictStr] = None,
        document__key: Optional[StrictStr] = None,
        document__gamesystem__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        document__gamesystem__key__iexact: Optional[StrictStr] = None,
        document__gamesystem__key: Optional[StrictStr] = None,
        classes__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        classes__key__iexact: Optional[StrictStr] = None,
        classes__key: Optional[StrictStr] = None,
        classes__name__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        level: Optional[StrictInt] = None,
        level__range: Annotated[Optional[List[StrictInt]], Field(description="Multiple values may be separated by commas.")] = None,
        level__gt: Optional[StrictInt] = None,
        level__gte: Optional[StrictInt] = None,
        level__lt: Optional[StrictInt] = None,
        level__lte: Optional[StrictInt] = None,
        range: Optional[StrictInt] = None,
        range__range: Annotated[Optional[List[StrictInt]], Field(description="Multiple values may be separated by commas.")] = None,
        range__gt: Optional[StrictInt] = None,
        range__gte: Optional[StrictInt] = None,
        range__lt: Optional[StrictInt] = None,
        range__lte: Optional[StrictInt] = None,
        school__key: Optional[StrictStr] = None,
        school__name__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        school__name__iexact: Optional[StrictStr] = None,
        school__name: Optional[StrictStr] = None,
        duration__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        duration__iexact: Optional[StrictStr] = None,
        duration: Annotated[Optional[StrictStr], Field(description="Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"  * `instantaneous` - instantaneous * `instantaneous or special` - instantaneous or special * `1 turn` - 1 turn * `1 round` - 1 round * `concentration + 1 round` - concentration + 1 round * `2 rounds` - 2 rounds * `3 rounds` - 3 rounds * `4 rounds` - 4 rounds * `1d4+2 rounds` - 1d4+2 rounds * `5 rounds` - 5 rounds * `6 rounds` - 6 rounds * `10 rounds` - 10 rounds * `up to 1 minute` - up to 1 minute * `1 minute` - 1 minute * `1 minute, or until expended` - 1 minute, or until expended * `1 minute, until expended` - 1 minute, until expended * `1 minute` - 1 minute * `5 minutes` - 5 minutes * `10 minutes` - 10 minutes * `1 minute or 1 hour` - 1 minute or 1 hour * `up to 1 hour` - up to 1 hour * `1 hour` - 1 hour * `1 hour or until triggered` - 1 hour or until triggered * `2 hours` - 2 hours * `3 hours` - 3 hours * `1d10 hours` - 1d10 hours * `6 hours` - 6 hours * `2-12 hours` - 2-12 hours * `up to 8 hours` - up to 8 hours * `8 hours` - 8 hours * `1 hour/caster level` - 1 hour/caster level * `10 hours` - 10 hours * `12 hours` - 12 hours * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw * `24 hours` - 24 hours * `1 day` - 1 day * `3 days` - 3 days * `5 days` - 5 days * `7 days` - 7 days * `10 days` - 10 days * `13 days` - 13 days * `30 days` - 30 days * `1 year` - 1 year * `special` - special * `until dispelled or destroyed` - until dispelled or destroyed * `until destroyed` - until destroyed * `until dispelled` - until dispelled * `until cured or dispelled` - until cured or dispelled * `until dispelled or triggered` - until dispelled or triggered * `permanent until discharged` - permanent until discharged * `permanent; one generation` - permanent; one generation * `permanent` - permanent")] = None,
        concentration: Optional[StrictBool] = None,
        verbal: Optional[StrictBool] = None,
        somatic: Optional[StrictBool] = None,
        material: Optional[StrictBool] = None,
        material_consumed: Optional[StrictBool] = None,
        casting_time__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        casting_time__iexact: Optional[StrictStr] = None,
        casting_time: Annotated[Optional[StrictStr], Field(description="Casting time key, such as 'action'  * `reaction` - Reaction * `bonus-action` - 1 Bonus Action * `action` - 1 Action * `turn` - 1 Turn * `round` - 1 Round * `1minute` - 1 Minute * `5minutes` - 5 Minutes * `10minutes` - 10 Minutes * `1hour` - 1 Hour * `4hours` - 4 Hours * `7hours` - 7 Hours * `8hours` - 8 Hours * `9hours` - 9 Hours * `12hours` - 12 Hours * `24hours` - 24 Hours * `1week` - 1 Week")] = None,
        ordering: Annotated[Optional[StrictStr], Field(description="Which field to use when ordering the results.")] = None,
        search: Annotated[Optional[StrictStr], Field(description="A search term.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="A page number within the paginated result set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaginatedSpellList]:
        """spells_list

        list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.

        :param key__in: Multiple values may be separated by commas.
        :type key__in: List[str]
        :param key__iexact:
        :type key__iexact: str
        :param key:
        :type key: str
        :param name__iexact:
        :type name__iexact: str
        :param name:
        :type name: str
        :param name__contains:
        :type name__contains: str
        :param name__icontains:
        :type name__icontains: str
        :param document__key__in: Multiple values may be separated by commas.
        :type document__key__in: List[str]
        :param document__key__iexact:
        :type document__key__iexact: str
        :param document__key:
        :type document__key: str
        :param document__gamesystem__key__in: Multiple values may be separated by commas.
        :type document__gamesystem__key__in: List[str]
        :param document__gamesystem__key__iexact:
        :type document__gamesystem__key__iexact: str
        :param document__gamesystem__key:
        :type document__gamesystem__key: str
        :param classes__key__in: Multiple values may be separated by commas.
        :type classes__key__in: List[str]
        :param classes__key__iexact:
        :type classes__key__iexact: str
        :param classes__key:
        :type classes__key: str
        :param classes__name__in: Multiple values may be separated by commas.
        :type classes__name__in: List[str]
        :param level:
        :type level: int
        :param level__range: Multiple values may be separated by commas.
        :type level__range: List[int]
        :param level__gt:
        :type level__gt: int
        :param level__gte:
        :type level__gte: int
        :param level__lt:
        :type level__lt: int
        :param level__lte:
        :type level__lte: int
        :param range:
        :type range: int
        :param range__range: Multiple values may be separated by commas.
        :type range__range: List[int]
        :param range__gt:
        :type range__gt: int
        :param range__gte:
        :type range__gte: int
        :param range__lt:
        :type range__lt: int
        :param range__lte:
        :type range__lte: int
        :param school__key:
        :type school__key: str
        :param school__name__in: Multiple values may be separated by commas.
        :type school__name__in: List[str]
        :param school__name__iexact:
        :type school__name__iexact: str
        :param school__name:
        :type school__name: str
        :param duration__in: Multiple values may be separated by commas.
        :type duration__in: List[str]
        :param duration__iexact:
        :type duration__iexact: str
        :param duration: Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"  * `instantaneous` - instantaneous * `instantaneous or special` - instantaneous or special * `1 turn` - 1 turn * `1 round` - 1 round * `concentration + 1 round` - concentration + 1 round * `2 rounds` - 2 rounds * `3 rounds` - 3 rounds * `4 rounds` - 4 rounds * `1d4+2 rounds` - 1d4+2 rounds * `5 rounds` - 5 rounds * `6 rounds` - 6 rounds * `10 rounds` - 10 rounds * `up to 1 minute` - up to 1 minute * `1 minute` - 1 minute * `1 minute, or until expended` - 1 minute, or until expended * `1 minute, until expended` - 1 minute, until expended * `1 minute` - 1 minute * `5 minutes` - 5 minutes * `10 minutes` - 10 minutes * `1 minute or 1 hour` - 1 minute or 1 hour * `up to 1 hour` - up to 1 hour * `1 hour` - 1 hour * `1 hour or until triggered` - 1 hour or until triggered * `2 hours` - 2 hours * `3 hours` - 3 hours * `1d10 hours` - 1d10 hours * `6 hours` - 6 hours * `2-12 hours` - 2-12 hours * `up to 8 hours` - up to 8 hours * `8 hours` - 8 hours * `1 hour/caster level` - 1 hour/caster level * `10 hours` - 10 hours * `12 hours` - 12 hours * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw * `24 hours` - 24 hours * `1 day` - 1 day * `3 days` - 3 days * `5 days` - 5 days * `7 days` - 7 days * `10 days` - 10 days * `13 days` - 13 days * `30 days` - 30 days * `1 year` - 1 year * `special` - special * `until dispelled or destroyed` - until dispelled or destroyed * `until destroyed` - until destroyed * `until dispelled` - until dispelled * `until cured or dispelled` - until cured or dispelled * `until dispelled or triggered` - until dispelled or triggered * `permanent until discharged` - permanent until discharged * `permanent; one generation` - permanent; one generation * `permanent` - permanent
        :type duration: str
        :param concentration:
        :type concentration: bool
        :param verbal:
        :type verbal: bool
        :param somatic:
        :type somatic: bool
        :param material:
        :type material: bool
        :param material_consumed:
        :type material_consumed: bool
        :param casting_time__in: Multiple values may be separated by commas.
        :type casting_time__in: List[str]
        :param casting_time__iexact:
        :type casting_time__iexact: str
        :param casting_time: Casting time key, such as 'action'  * `reaction` - Reaction * `bonus-action` - 1 Bonus Action * `action` - 1 Action * `turn` - 1 Turn * `round` - 1 Round * `1minute` - 1 Minute * `5minutes` - 5 Minutes * `10minutes` - 10 Minutes * `1hour` - 1 Hour * `4hours` - 4 Hours * `7hours` - 7 Hours * `8hours` - 8 Hours * `9hours` - 9 Hours * `12hours` - 12 Hours * `24hours` - 24 Hours * `1week` - 1 Week
        :type casting_time: str
        :param ordering: Which field to use when ordering the results.
        :type ordering: str
        :param search: A search term.
        :type search: str
        :param page: A page number within the paginated result set.
        :type page: int
        :param limit: Number of results to return per page.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._spells_list_serialize(
            key__in=key__in,
            key__iexact=key__iexact,
            key=key,
            name__iexact=name__iexact,
            name=name,
            name__contains=name__contains,
            name__icontains=name__icontains,
            document__key__in=document__key__in,
            document__key__iexact=document__key__iexact,
            document__key=document__key,
            document__gamesystem__key__in=document__gamesystem__key__in,
            document__gamesystem__key__iexact=document__gamesystem__key__iexact,
            document__gamesystem__key=document__gamesystem__key,
            classes__key__in=classes__key__in,
            classes__key__iexact=classes__key__iexact,
            classes__key=classes__key,
            classes__name__in=classes__name__in,
            level=level,
            level__range=level__range,
            level__gt=level__gt,
            level__gte=level__gte,
            level__lt=level__lt,
            level__lte=level__lte,
            range=range,
            range__range=range__range,
            range__gt=range__gt,
            range__gte=range__gte,
            range__lt=range__lt,
            range__lte=range__lte,
            school__key=school__key,
            school__name__in=school__name__in,
            school__name__iexact=school__name__iexact,
            school__name=school__name,
            duration__in=duration__in,
            duration__iexact=duration__iexact,
            duration=duration,
            concentration=concentration,
            verbal=verbal,
            somatic=somatic,
            material=material,
            material_consumed=material_consumed,
            casting_time__in=casting_time__in,
            casting_time__iexact=casting_time__iexact,
            casting_time=casting_time,
            ordering=ordering,
            search=search,
            page=page,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedSpellList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def spells_list_without_preload_content(
        self,
        key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        key__iexact: Optional[StrictStr] = None,
        key: Optional[StrictStr] = None,
        name__iexact: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        name__contains: Optional[StrictStr] = None,
        name__icontains: Optional[StrictStr] = None,
        document__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        document__key__iexact: Optional[StrictStr] = None,
        document__key: Optional[StrictStr] = None,
        document__gamesystem__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        document__gamesystem__key__iexact: Optional[StrictStr] = None,
        document__gamesystem__key: Optional[StrictStr] = None,
        classes__key__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        classes__key__iexact: Optional[StrictStr] = None,
        classes__key: Optional[StrictStr] = None,
        classes__name__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        level: Optional[StrictInt] = None,
        level__range: Annotated[Optional[List[StrictInt]], Field(description="Multiple values may be separated by commas.")] = None,
        level__gt: Optional[StrictInt] = None,
        level__gte: Optional[StrictInt] = None,
        level__lt: Optional[StrictInt] = None,
        level__lte: Optional[StrictInt] = None,
        range: Optional[StrictInt] = None,
        range__range: Annotated[Optional[List[StrictInt]], Field(description="Multiple values may be separated by commas.")] = None,
        range__gt: Optional[StrictInt] = None,
        range__gte: Optional[StrictInt] = None,
        range__lt: Optional[StrictInt] = None,
        range__lte: Optional[StrictInt] = None,
        school__key: Optional[StrictStr] = None,
        school__name__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        school__name__iexact: Optional[StrictStr] = None,
        school__name: Optional[StrictStr] = None,
        duration__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        duration__iexact: Optional[StrictStr] = None,
        duration: Annotated[Optional[StrictStr], Field(description="Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"  * `instantaneous` - instantaneous * `instantaneous or special` - instantaneous or special * `1 turn` - 1 turn * `1 round` - 1 round * `concentration + 1 round` - concentration + 1 round * `2 rounds` - 2 rounds * `3 rounds` - 3 rounds * `4 rounds` - 4 rounds * `1d4+2 rounds` - 1d4+2 rounds * `5 rounds` - 5 rounds * `6 rounds` - 6 rounds * `10 rounds` - 10 rounds * `up to 1 minute` - up to 1 minute * `1 minute` - 1 minute * `1 minute, or until expended` - 1 minute, or until expended * `1 minute, until expended` - 1 minute, until expended * `1 minute` - 1 minute * `5 minutes` - 5 minutes * `10 minutes` - 10 minutes * `1 minute or 1 hour` - 1 minute or 1 hour * `up to 1 hour` - up to 1 hour * `1 hour` - 1 hour * `1 hour or until triggered` - 1 hour or until triggered * `2 hours` - 2 hours * `3 hours` - 3 hours * `1d10 hours` - 1d10 hours * `6 hours` - 6 hours * `2-12 hours` - 2-12 hours * `up to 8 hours` - up to 8 hours * `8 hours` - 8 hours * `1 hour/caster level` - 1 hour/caster level * `10 hours` - 10 hours * `12 hours` - 12 hours * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw * `24 hours` - 24 hours * `1 day` - 1 day * `3 days` - 3 days * `5 days` - 5 days * `7 days` - 7 days * `10 days` - 10 days * `13 days` - 13 days * `30 days` - 30 days * `1 year` - 1 year * `special` - special * `until dispelled or destroyed` - until dispelled or destroyed * `until destroyed` - until destroyed * `until dispelled` - until dispelled * `until cured or dispelled` - until cured or dispelled * `until dispelled or triggered` - until dispelled or triggered * `permanent until discharged` - permanent until discharged * `permanent; one generation` - permanent; one generation * `permanent` - permanent")] = None,
        concentration: Optional[StrictBool] = None,
        verbal: Optional[StrictBool] = None,
        somatic: Optional[StrictBool] = None,
        material: Optional[StrictBool] = None,
        material_consumed: Optional[StrictBool] = None,
        casting_time__in: Annotated[Optional[List[StrictStr]], Field(description="Multiple values may be separated by commas.")] = None,
        casting_time__iexact: Optional[StrictStr] = None,
        casting_time: Annotated[Optional[StrictStr], Field(description="Casting time key, such as 'action'  * `reaction` - Reaction * `bonus-action` - 1 Bonus Action * `action` - 1 Action * `turn` - 1 Turn * `round` - 1 Round * `1minute` - 1 Minute * `5minutes` - 5 Minutes * `10minutes` - 10 Minutes * `1hour` - 1 Hour * `4hours` - 4 Hours * `7hours` - 7 Hours * `8hours` - 8 Hours * `9hours` - 9 Hours * `12hours` - 12 Hours * `24hours` - 24 Hours * `1week` - 1 Week")] = None,
        ordering: Annotated[Optional[StrictStr], Field(description="Which field to use when ordering the results.")] = None,
        search: Annotated[Optional[StrictStr], Field(description="A search term.")] = None,
        page: Annotated[Optional[StrictInt], Field(description="A page number within the paginated result set.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """spells_list

        list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.

        :param key__in: Multiple values may be separated by commas.
        :type key__in: List[str]
        :param key__iexact:
        :type key__iexact: str
        :param key:
        :type key: str
        :param name__iexact:
        :type name__iexact: str
        :param name:
        :type name: str
        :param name__contains:
        :type name__contains: str
        :param name__icontains:
        :type name__icontains: str
        :param document__key__in: Multiple values may be separated by commas.
        :type document__key__in: List[str]
        :param document__key__iexact:
        :type document__key__iexact: str
        :param document__key:
        :type document__key: str
        :param document__gamesystem__key__in: Multiple values may be separated by commas.
        :type document__gamesystem__key__in: List[str]
        :param document__gamesystem__key__iexact:
        :type document__gamesystem__key__iexact: str
        :param document__gamesystem__key:
        :type document__gamesystem__key: str
        :param classes__key__in: Multiple values may be separated by commas.
        :type classes__key__in: List[str]
        :param classes__key__iexact:
        :type classes__key__iexact: str
        :param classes__key:
        :type classes__key: str
        :param classes__name__in: Multiple values may be separated by commas.
        :type classes__name__in: List[str]
        :param level:
        :type level: int
        :param level__range: Multiple values may be separated by commas.
        :type level__range: List[int]
        :param level__gt:
        :type level__gt: int
        :param level__gte:
        :type level__gte: int
        :param level__lt:
        :type level__lt: int
        :param level__lte:
        :type level__lte: int
        :param range:
        :type range: int
        :param range__range: Multiple values may be separated by commas.
        :type range__range: List[int]
        :param range__gt:
        :type range__gt: int
        :param range__gte:
        :type range__gte: int
        :param range__lt:
        :type range__lt: int
        :param range__lte:
        :type range__lte: int
        :param school__key:
        :type school__key: str
        :param school__name__in: Multiple values may be separated by commas.
        :type school__name__in: List[str]
        :param school__name__iexact:
        :type school__name__iexact: str
        :param school__name:
        :type school__name: str
        :param duration__in: Multiple values may be separated by commas.
        :type duration__in: List[str]
        :param duration__iexact:
        :type duration__iexact: str
        :param duration: Description of the duration of the effect such as \"instantaneous\" or \"1 minute\"  * `instantaneous` - instantaneous * `instantaneous or special` - instantaneous or special * `1 turn` - 1 turn * `1 round` - 1 round * `concentration + 1 round` - concentration + 1 round * `2 rounds` - 2 rounds * `3 rounds` - 3 rounds * `4 rounds` - 4 rounds * `1d4+2 rounds` - 1d4+2 rounds * `5 rounds` - 5 rounds * `6 rounds` - 6 rounds * `10 rounds` - 10 rounds * `up to 1 minute` - up to 1 minute * `1 minute` - 1 minute * `1 minute, or until expended` - 1 minute, or until expended * `1 minute, until expended` - 1 minute, until expended * `1 minute` - 1 minute * `5 minutes` - 5 minutes * `10 minutes` - 10 minutes * `1 minute or 1 hour` - 1 minute or 1 hour * `up to 1 hour` - up to 1 hour * `1 hour` - 1 hour * `1 hour or until triggered` - 1 hour or until triggered * `2 hours` - 2 hours * `3 hours` - 3 hours * `1d10 hours` - 1d10 hours * `6 hours` - 6 hours * `2-12 hours` - 2-12 hours * `up to 8 hours` - up to 8 hours * `8 hours` - 8 hours * `1 hour/caster level` - 1 hour/caster level * `10 hours` - 10 hours * `12 hours` - 12 hours * `24 hours or until the target attempts a third death saving throw` - 24 hours or until the target attempts a third death saving throw * `24 hours` - 24 hours * `1 day` - 1 day * `3 days` - 3 days * `5 days` - 5 days * `7 days` - 7 days * `10 days` - 10 days * `13 days` - 13 days * `30 days` - 30 days * `1 year` - 1 year * `special` - special * `until dispelled or destroyed` - until dispelled or destroyed * `until destroyed` - until destroyed * `until dispelled` - until dispelled * `until cured or dispelled` - until cured or dispelled * `until dispelled or triggered` - until dispelled or triggered * `permanent until discharged` - permanent until discharged * `permanent; one generation` - permanent; one generation * `permanent` - permanent
        :type duration: str
        :param concentration:
        :type concentration: bool
        :param verbal:
        :type verbal: bool
        :param somatic:
        :type somatic: bool
        :param material:
        :type material: bool
        :param material_consumed:
        :type material_consumed: bool
        :param casting_time__in: Multiple values may be separated by commas.
        :type casting_time__in: List[str]
        :param casting_time__iexact:
        :type casting_time__iexact: str
        :param casting_time: Casting time key, such as 'action'  * `reaction` - Reaction * `bonus-action` - 1 Bonus Action * `action` - 1 Action * `turn` - 1 Turn * `round` - 1 Round * `1minute` - 1 Minute * `5minutes` - 5 Minutes * `10minutes` - 10 Minutes * `1hour` - 1 Hour * `4hours` - 4 Hours * `7hours` - 7 Hours * `8hours` - 8 Hours * `9hours` - 9 Hours * `12hours` - 12 Hours * `24hours` - 24 Hours * `1week` - 1 Week
        :type casting_time: str
        :param ordering: Which field to use when ordering the results.
        :type ordering: str
        :param search: A search term.
        :type search: str
        :param page: A page number within the paginated result set.
        :type page: int
        :param limit: Number of results to return per page.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._spells_list_serialize(
            key__in=key__in,
            key__iexact=key__iexact,
            key=key,
            name__iexact=name__iexact,
            name=name,
            name__contains=name__contains,
            name__icontains=name__icontains,
            document__key__in=document__key__in,
            document__key__iexact=document__key__iexact,
            document__key=document__key,
            document__gamesystem__key__in=document__gamesystem__key__in,
            document__gamesystem__key__iexact=document__gamesystem__key__iexact,
            document__gamesystem__key=document__gamesystem__key,
            classes__key__in=classes__key__in,
            classes__key__iexact=classes__key__iexact,
            classes__key=classes__key,
            classes__name__in=classes__name__in,
            level=level,
            level__range=level__range,
            level__gt=level__gt,
            level__gte=level__gte,
            level__lt=level__lt,
            level__lte=level__lte,
            range=range,
            range__range=range__range,
            range__gt=range__gt,
            range__gte=range__gte,
            range__lt=range__lt,
            range__lte=range__lte,
            school__key=school__key,
            school__name__in=school__name__in,
            school__name__iexact=school__name__iexact,
            school__name=school__name,
            duration__in=duration__in,
            duration__iexact=duration__iexact,
            duration=duration,
            concentration=concentration,
            verbal=verbal,
            somatic=somatic,
            material=material,
            material_consumed=material_consumed,
            casting_time__in=casting_time__in,
            casting_time__iexact=casting_time__iexact,
            casting_time=casting_time,
            ordering=ordering,
            search=search,
            page=page,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedSpellList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _spells_list_serialize(
        self,
        key__in,
        key__iexact,
        key,
        name__iexact,
        name,
        name__contains,
        name__icontains,
        document__key__in,
        document__key__iexact,
        document__key,
        document__gamesystem__key__in,
        document__gamesystem__key__iexact,
        document__gamesystem__key,
        classes__key__in,
        classes__key__iexact,
        classes__key,
        classes__name__in,
        level,
        level__range,
        level__gt,
        level__gte,
        level__lt,
        level__lte,
        range,
        range__range,
        range__gt,
        range__gte,
        range__lt,
        range__lte,
        school__key,
        school__name__in,
        school__name__iexact,
        school__name,
        duration__in,
        duration__iexact,
        duration,
        concentration,
        verbal,
        somatic,
        material,
        material_consumed,
        casting_time__in,
        casting_time__iexact,
        casting_time,
        ordering,
        search,
        page,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'key__in': 'csv',
            'document__key__in': 'csv',
            'document__gamesystem__key__in': 'csv',
            'classes__key__in': 'csv',
            'classes__name__in': 'csv',
            'level__range': 'csv',
            'range__range': 'csv',
            'school__name__in': 'csv',
            'duration__in': 'csv',
            'casting_time__in': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if key__in is not None:
            
            _query_params.append(('key__in', key__in))
            
        if key__iexact is not None:
            
            _query_params.append(('key__iexact', key__iexact))
            
        if key is not None:
            
            _query_params.append(('key', key))
            
        if name__iexact is not None:
            
            _query_params.append(('name__iexact', name__iexact))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if name__contains is not None:
            
            _query_params.append(('name__contains', name__contains))
            
        if name__icontains is not None:
            
            _query_params.append(('name__icontains', name__icontains))
            
        if document__key__in is not None:
            
            _query_params.append(('document__key__in', document__key__in))
            
        if document__key__iexact is not None:
            
            _query_params.append(('document__key__iexact', document__key__iexact))
            
        if document__key is not None:
            
            _query_params.append(('document__key', document__key))
            
        if document__gamesystem__key__in is not None:
            
            _query_params.append(('document__gamesystem__key__in', document__gamesystem__key__in))
            
        if document__gamesystem__key__iexact is not None:
            
            _query_params.append(('document__gamesystem__key__iexact', document__gamesystem__key__iexact))
            
        if document__gamesystem__key is not None:
            
            _query_params.append(('document__gamesystem__key', document__gamesystem__key))
            
        if classes__key__in is not None:
            
            _query_params.append(('classes__key__in', classes__key__in))
            
        if classes__key__iexact is not None:
            
            _query_params.append(('classes__key__iexact', classes__key__iexact))
            
        if classes__key is not None:
            
            _query_params.append(('classes__key', classes__key))
            
        if classes__name__in is not None:
            
            _query_params.append(('classes__name__in', classes__name__in))
            
        if level is not None:
            
            _query_params.append(('level', level))
            
        if level__range is not None:
            
            _query_params.append(('level__range', level__range))
            
        if level__gt is not None:
            
            _query_params.append(('level__gt', level__gt))
            
        if level__gte is not None:
            
            _query_params.append(('level__gte', level__gte))
            
        if level__lt is not None:
            
            _query_params.append(('level__lt', level__lt))
            
        if level__lte is not None:
            
            _query_params.append(('level__lte', level__lte))
            
        if range is not None:
            
            _query_params.append(('range', range))
            
        if range__range is not None:
            
            _query_params.append(('range__range', range__range))
            
        if range__gt is not None:
            
            _query_params.append(('range__gt', range__gt))
            
        if range__gte is not None:
            
            _query_params.append(('range__gte', range__gte))
            
        if range__lt is not None:
            
            _query_params.append(('range__lt', range__lt))
            
        if range__lte is not None:
            
            _query_params.append(('range__lte', range__lte))
            
        if school__key is not None:
            
            _query_params.append(('school__key', school__key))
            
        if school__name__in is not None:
            
            _query_params.append(('school__name__in', school__name__in))
            
        if school__name__iexact is not None:
            
            _query_params.append(('school__name__iexact', school__name__iexact))
            
        if school__name is not None:
            
            _query_params.append(('school__name', school__name))
            
        if duration__in is not None:
            
            _query_params.append(('duration__in', duration__in))
            
        if duration__iexact is not None:
            
            _query_params.append(('duration__iexact', duration__iexact))
            
        if duration is not None:
            
            _query_params.append(('duration', duration))
            
        if concentration is not None:
            
            _query_params.append(('concentration', concentration))
            
        if verbal is not None:
            
            _query_params.append(('verbal', verbal))
            
        if somatic is not None:
            
            _query_params.append(('somatic', somatic))
            
        if material is not None:
            
            _query_params.append(('material', material))
            
        if material_consumed is not None:
            
            _query_params.append(('material_consumed', material_consumed))
            
        if casting_time__in is not None:
            
            _query_params.append(('casting_time__in', casting_time__in))
            
        if casting_time__iexact is not None:
            
            _query_params.append(('casting_time__iexact', casting_time__iexact))
            
        if casting_time is not None:
            
            _query_params.append(('casting_time', casting_time))
            
        if ordering is not None:
            
            _query_params.append(('ordering', ordering))
            
        if search is not None:
            
            _query_params.append(('search', search))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2/spells/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def spells_retrieve(
        self,
        key: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Spell:
        """spells_retrieve

        list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.

        :param key: (required)
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._spells_retrieve_serialize(
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Spell",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def spells_retrieve_with_http_info(
        self,
        key: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Spell]:
        """spells_retrieve

        list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.

        :param key: (required)
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._spells_retrieve_serialize(
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Spell",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def spells_retrieve_without_preload_content(
        self,
        key: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """spells_retrieve

        list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.

        :param key: (required)
        :type key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._spells_retrieve_serialize(
            key=key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Spell",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _spells_retrieve_serialize(
        self,
        key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if key is not None:
            _path_params['key'] = key
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2/spells/{key}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


