/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CharacterClass,
    CharacterClassFromJSON,
    CharacterClassToJSON,
} from '../models/CharacterClass';
import {
    type PaginatedCharacterClassList,
    PaginatedCharacterClassListFromJSON,
    PaginatedCharacterClassListToJSON,
} from '../models/PaginatedCharacterClassList';

export interface ClassesListRequest {
    keyIn?: Array<string>;
    keyIexact?: string;
    key?: string;
    nameIexact?: string;
    name?: string;
    nameContains?: string;
    documentKeyIn?: Array<string>;
    documentKeyIexact?: string;
    documentKey?: string;
    documentGamesystemKeyIn?: Array<string>;
    documentGamesystemKeyIexact?: string;
    documentGamesystemKey?: string;
    subclassOf?: string;
    isSubclass?: boolean;
    ordering?: string;
    search?: string;
    page?: number;
    limit?: number;
}

export interface ClassesRetrieveRequest {
    key: string;
}

/**
 * 
 */
export class ClassesApi extends runtime.BaseAPI {

    /**
     * Creates request options for classesList without sending the request
     */
    async classesListRequestOpts(requestParameters: ClassesListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['keyIn'] != null) {
            queryParameters['key__in'] = requestParameters['keyIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['keyIexact'] != null) {
            queryParameters['key__iexact'] = requestParameters['keyIexact'];
        }

        if (requestParameters['key'] != null) {
            queryParameters['key'] = requestParameters['key'];
        }

        if (requestParameters['nameIexact'] != null) {
            queryParameters['name__iexact'] = requestParameters['nameIexact'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['nameContains'] != null) {
            queryParameters['name__contains'] = requestParameters['nameContains'];
        }

        if (requestParameters['documentKeyIn'] != null) {
            queryParameters['document__key__in'] = requestParameters['documentKeyIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['documentKeyIexact'] != null) {
            queryParameters['document__key__iexact'] = requestParameters['documentKeyIexact'];
        }

        if (requestParameters['documentKey'] != null) {
            queryParameters['document__key'] = requestParameters['documentKey'];
        }

        if (requestParameters['documentGamesystemKeyIn'] != null) {
            queryParameters['document__gamesystem__key__in'] = requestParameters['documentGamesystemKeyIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['documentGamesystemKeyIexact'] != null) {
            queryParameters['document__gamesystem__key__iexact'] = requestParameters['documentGamesystemKeyIexact'];
        }

        if (requestParameters['documentGamesystemKey'] != null) {
            queryParameters['document__gamesystem__key'] = requestParameters['documentGamesystemKey'];
        }

        if (requestParameters['subclassOf'] != null) {
            queryParameters['subclass_of'] = requestParameters['subclassOf'];
        }

        if (requestParameters['isSubclass'] != null) {
            queryParameters['is_subclass'] = requestParameters['isSubclass'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/classes/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list: API endpoint for returning a list of classes. retrieve: API endpoint for returning a particular class.
     */
    async classesListRaw(requestParameters: ClassesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedCharacterClassList>> {
        const requestOptions = await this.classesListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedCharacterClassListFromJSON(jsonValue));
    }

    /**
     * list: API endpoint for returning a list of classes. retrieve: API endpoint for returning a particular class.
     */
    async classesList(requestParameters: ClassesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedCharacterClassList> {
        const response = await this.classesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for classesRetrieve without sending the request
     */
    async classesRetrieveRequestOpts(requestParameters: ClassesRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling classesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/classes/{key}/`;
        urlPath = urlPath.replace('{key}', encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list: API endpoint for returning a list of classes. retrieve: API endpoint for returning a particular class.
     */
    async classesRetrieveRaw(requestParameters: ClassesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharacterClass>> {
        const requestOptions = await this.classesRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CharacterClassFromJSON(jsonValue));
    }

    /**
     * list: API endpoint for returning a list of classes. retrieve: API endpoint for returning a particular class.
     */
    async classesRetrieve(requestParameters: ClassesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CharacterClass> {
        const response = await this.classesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
