/* tslint:disable */
/* eslint-disable */
/**
 * Open5e — demo subset
 * The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.
 *
 * The version of the OpenAPI document: development (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PaginatedSpellList,
    PaginatedSpellListFromJSON,
    PaginatedSpellListToJSON,
} from '../models/PaginatedSpellList';
import {
    type Spell,
    SpellFromJSON,
    SpellToJSON,
} from '../models/Spell';

export interface SpellsListRequest {
    keyIn?: Array<string>;
    keyIexact?: string;
    key?: string;
    nameIexact?: string;
    name?: string;
    nameContains?: string;
    nameIcontains?: string;
    documentKeyIn?: Array<string>;
    documentKeyIexact?: string;
    documentKey?: string;
    documentGamesystemKeyIn?: Array<string>;
    documentGamesystemKeyIexact?: string;
    documentGamesystemKey?: string;
    classesKeyIn?: Array<string>;
    classesKeyIexact?: string;
    classesKey?: string;
    classesNameIn?: Array<string>;
    level?: number;
    levelRange?: Array<number>;
    levelGt?: number;
    levelGte?: number;
    levelLt?: number;
    levelLte?: number;
    range?: number;
    rangeRange?: Array<number>;
    rangeGt?: number;
    rangeGte?: number;
    rangeLt?: number;
    rangeLte?: number;
    schoolKey?: string;
    schoolNameIn?: Array<string>;
    schoolNameIexact?: string;
    schoolName?: string;
    durationIn?: Array<string>;
    durationIexact?: string;
    duration?: SpellsListDurationEnum;
    concentration?: boolean;
    verbal?: boolean;
    somatic?: boolean;
    material?: boolean;
    materialConsumed?: boolean;
    castingTimeIn?: Array<string>;
    castingTimeIexact?: string;
    castingTime?: SpellsListCastingTimeEnum;
    ordering?: string;
    search?: string;
    page?: number;
    limit?: number;
}

export interface SpellsRetrieveRequest {
    key: string;
}

/**
 * 
 */
export class SpellsApi extends runtime.BaseAPI {

    /**
     * Creates request options for spellsList without sending the request
     */
    async spellsListRequestOpts(requestParameters: SpellsListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['keyIn'] != null) {
            queryParameters['key__in'] = requestParameters['keyIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['keyIexact'] != null) {
            queryParameters['key__iexact'] = requestParameters['keyIexact'];
        }

        if (requestParameters['key'] != null) {
            queryParameters['key'] = requestParameters['key'];
        }

        if (requestParameters['nameIexact'] != null) {
            queryParameters['name__iexact'] = requestParameters['nameIexact'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['nameContains'] != null) {
            queryParameters['name__contains'] = requestParameters['nameContains'];
        }

        if (requestParameters['nameIcontains'] != null) {
            queryParameters['name__icontains'] = requestParameters['nameIcontains'];
        }

        if (requestParameters['documentKeyIn'] != null) {
            queryParameters['document__key__in'] = requestParameters['documentKeyIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['documentKeyIexact'] != null) {
            queryParameters['document__key__iexact'] = requestParameters['documentKeyIexact'];
        }

        if (requestParameters['documentKey'] != null) {
            queryParameters['document__key'] = requestParameters['documentKey'];
        }

        if (requestParameters['documentGamesystemKeyIn'] != null) {
            queryParameters['document__gamesystem__key__in'] = requestParameters['documentGamesystemKeyIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['documentGamesystemKeyIexact'] != null) {
            queryParameters['document__gamesystem__key__iexact'] = requestParameters['documentGamesystemKeyIexact'];
        }

        if (requestParameters['documentGamesystemKey'] != null) {
            queryParameters['document__gamesystem__key'] = requestParameters['documentGamesystemKey'];
        }

        if (requestParameters['classesKeyIn'] != null) {
            queryParameters['classes__key__in'] = requestParameters['classesKeyIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['classesKeyIexact'] != null) {
            queryParameters['classes__key__iexact'] = requestParameters['classesKeyIexact'];
        }

        if (requestParameters['classesKey'] != null) {
            queryParameters['classes__key'] = requestParameters['classesKey'];
        }

        if (requestParameters['classesNameIn'] != null) {
            queryParameters['classes__name__in'] = requestParameters['classesNameIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['levelRange'] != null) {
            queryParameters['level__range'] = requestParameters['levelRange']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['levelGt'] != null) {
            queryParameters['level__gt'] = requestParameters['levelGt'];
        }

        if (requestParameters['levelGte'] != null) {
            queryParameters['level__gte'] = requestParameters['levelGte'];
        }

        if (requestParameters['levelLt'] != null) {
            queryParameters['level__lt'] = requestParameters['levelLt'];
        }

        if (requestParameters['levelLte'] != null) {
            queryParameters['level__lte'] = requestParameters['levelLte'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['rangeRange'] != null) {
            queryParameters['range__range'] = requestParameters['rangeRange']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['rangeGt'] != null) {
            queryParameters['range__gt'] = requestParameters['rangeGt'];
        }

        if (requestParameters['rangeGte'] != null) {
            queryParameters['range__gte'] = requestParameters['rangeGte'];
        }

        if (requestParameters['rangeLt'] != null) {
            queryParameters['range__lt'] = requestParameters['rangeLt'];
        }

        if (requestParameters['rangeLte'] != null) {
            queryParameters['range__lte'] = requestParameters['rangeLte'];
        }

        if (requestParameters['schoolKey'] != null) {
            queryParameters['school__key'] = requestParameters['schoolKey'];
        }

        if (requestParameters['schoolNameIn'] != null) {
            queryParameters['school__name__in'] = requestParameters['schoolNameIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['schoolNameIexact'] != null) {
            queryParameters['school__name__iexact'] = requestParameters['schoolNameIexact'];
        }

        if (requestParameters['schoolName'] != null) {
            queryParameters['school__name'] = requestParameters['schoolName'];
        }

        if (requestParameters['durationIn'] != null) {
            queryParameters['duration__in'] = requestParameters['durationIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['durationIexact'] != null) {
            queryParameters['duration__iexact'] = requestParameters['durationIexact'];
        }

        if (requestParameters['duration'] != null) {
            queryParameters['duration'] = requestParameters['duration'];
        }

        if (requestParameters['concentration'] != null) {
            queryParameters['concentration'] = requestParameters['concentration'];
        }

        if (requestParameters['verbal'] != null) {
            queryParameters['verbal'] = requestParameters['verbal'];
        }

        if (requestParameters['somatic'] != null) {
            queryParameters['somatic'] = requestParameters['somatic'];
        }

        if (requestParameters['material'] != null) {
            queryParameters['material'] = requestParameters['material'];
        }

        if (requestParameters['materialConsumed'] != null) {
            queryParameters['material_consumed'] = requestParameters['materialConsumed'];
        }

        if (requestParameters['castingTimeIn'] != null) {
            queryParameters['casting_time__in'] = requestParameters['castingTimeIn']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['castingTimeIexact'] != null) {
            queryParameters['casting_time__iexact'] = requestParameters['castingTimeIexact'];
        }

        if (requestParameters['castingTime'] != null) {
            queryParameters['casting_time'] = requestParameters['castingTime'];
        }

        if (requestParameters['ordering'] != null) {
            queryParameters['ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/spells/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.
     */
    async spellsListRaw(requestParameters: SpellsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSpellList>> {
        const requestOptions = await this.spellsListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSpellListFromJSON(jsonValue));
    }

    /**
     * list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.
     */
    async spellsList(requestParameters: SpellsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSpellList> {
        const response = await this.spellsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for spellsRetrieve without sending the request
     */
    async spellsRetrieveRequestOpts(requestParameters: SpellsRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling spellsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/spells/{key}/`;
        urlPath = urlPath.replace('{key}', encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.
     */
    async spellsRetrieveRaw(requestParameters: SpellsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Spell>> {
        const requestOptions = await this.spellsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SpellFromJSON(jsonValue));
    }

    /**
     * list: API endpoint for returning a list of spells. retrieve: API endpoint for returning a particular spell.
     */
    async spellsRetrieve(requestParameters: SpellsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Spell> {
        const response = await this.spellsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SpellsListDurationEnum = {
    _1Day: '1 day',
    _1Hour: '1 hour',
    _1HourOrUntilTriggered: '1 hour or until triggered',
    _1HourCasterLevel: '1 hour/caster level',
    _1Minute: '1 minute',
    _1Minute2: '1 minute',
    _1MinuteOr1Hour: '1 minute or 1 hour',
    _1MinuteOrUntilExpended: '1 minute, or until expended',
    _1MinuteUntilExpended: '1 minute, until expended',
    _1Round: '1 round',
    _1Turn: '1 turn',
    _1Year: '1 year',
    _10Days: '10 days',
    _10Hours: '10 hours',
    _10Minutes: '10 minutes',
    _10Rounds: '10 rounds',
    _12Hours: '12 hours',
    _13Days: '13 days',
    _1d10Hours: '1d10 hours',
    _1d42Rounds: '1d4+2 rounds',
    _2Hours: '2 hours',
    _2Rounds: '2 rounds',
    _212Hours: '2-12 hours',
    _24Hours: '24 hours',
    _24HoursOrUntilTheTargetAttemptsAThirdDeathSavingThrow: '24 hours or until the target attempts a third death saving throw',
    _3Days: '3 days',
    _3Hours: '3 hours',
    _3Rounds: '3 rounds',
    _30Days: '30 days',
    _4Rounds: '4 rounds',
    _5Days: '5 days',
    _5Minutes: '5 minutes',
    _5Rounds: '5 rounds',
    _6Hours: '6 hours',
    _6Rounds: '6 rounds',
    _7Days: '7 days',
    _8Hours: '8 hours',
    Concentration1Round: 'concentration + 1 round',
    Instantaneous: 'instantaneous',
    InstantaneousOrSpecial: 'instantaneous or special',
    Permanent: 'permanent',
    PermanentUntilDischarged: 'permanent until discharged',
    PermanentOneGeneration: 'permanent; one generation',
    Special: 'special',
    UntilCuredOrDispelled: 'until cured or dispelled',
    UntilDestroyed: 'until destroyed',
    UntilDispelled: 'until dispelled',
    UntilDispelledOrDestroyed: 'until dispelled or destroyed',
    UntilDispelledOrTriggered: 'until dispelled or triggered',
    UpTo1Hour: 'up to 1 hour',
    UpTo1Minute: 'up to 1 minute',
    UpTo8Hours: 'up to 8 hours'
} as const;
export type SpellsListDurationEnum = typeof SpellsListDurationEnum[keyof typeof SpellsListDurationEnum];
/**
 * @export
 */
export const SpellsListCastingTimeEnum = {
    _10minutes: '10minutes',
    _12hours: '12hours',
    _1hour: '1hour',
    _1minute: '1minute',
    _1week: '1week',
    _24hours: '24hours',
    _4hours: '4hours',
    _5minutes: '5minutes',
    _7hours: '7hours',
    _8hours: '8hours',
    _9hours: '9hours',
    Action: 'action',
    BonusAction: 'bonus-action',
    Reaction: 'reaction',
    Round: 'round',
    Turn: 'turn'
} as const;
export type SpellsListCastingTimeEnum = typeof SpellsListCastingTimeEnum[keyof typeof SpellsListCastingTimeEnum];
