# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.paginated_character_class_list import PaginatedCharacterClassList

class TestPaginatedCharacterClassList(unittest.TestCase):
    """PaginatedCharacterClassList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedCharacterClassList:
        """Test PaginatedCharacterClassList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedCharacterClassList`
        """
        model = PaginatedCharacterClassList()
        if include_optional:
            return PaginatedCharacterClassList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    open5e.models.character_class.CharacterClass(
                        key = '', 
                        features = [
                            open5e.models.class_feature.ClassFeature(
                                key = '', 
                                name = '', 
                                desc = '', 
                                feature_type = 'CORE_TRAITS_TABLE', 
                                feature_items = [
                                    open5e.models.class_feature_prefetch.ClassFeaturePrefetch(
                                        level = 0, 
                                        detail = '', 
                                        column_value = '', )
                                    ], )
                            ], 
                        hit_points = null, 
                        document = open5e.models.document_summary.DocumentSummary(
                            name = '', 
                            key = '', 
                            type = 'SOURCE', 
                            display_name = '', 
                            publisher = open5e.models.publisher_summary.PublisherSummary(
                                name = '', 
                                key = '', ), 
                            gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                                name = '', 
                                key = '', ), 
                            permalink = '', ), 
                        saving_throws = [
                            open5e.models.ability_summary.AbilitySummary(
                                name = '', )
                            ], 
                        subclass_of = open5e.models.character_class_summary.CharacterClassSummary(
                            name = '', 
                            key = '', ), 
                        name = '', 
                        desc = '', 
                        hit_dice = 'D3', 
                        caster_type = 'FULL', 
                        primary_abilities = [
                            ''
                            ], 
                        crossreferences = null, )
                    ]
            )
        else:
            return PaginatedCharacterClassList(
                count = 123,
                results = [
                    open5e.models.character_class.CharacterClass(
                        key = '', 
                        features = [
                            open5e.models.class_feature.ClassFeature(
                                key = '', 
                                name = '', 
                                desc = '', 
                                feature_type = 'CORE_TRAITS_TABLE', 
                                feature_items = [
                                    open5e.models.class_feature_prefetch.ClassFeaturePrefetch(
                                        level = 0, 
                                        detail = '', 
                                        column_value = '', )
                                    ], )
                            ], 
                        hit_points = null, 
                        document = open5e.models.document_summary.DocumentSummary(
                            name = '', 
                            key = '', 
                            type = 'SOURCE', 
                            display_name = '', 
                            publisher = open5e.models.publisher_summary.PublisherSummary(
                                name = '', 
                                key = '', ), 
                            gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                                name = '', 
                                key = '', ), 
                            permalink = '', ), 
                        saving_throws = [
                            open5e.models.ability_summary.AbilitySummary(
                                name = '', )
                            ], 
                        subclass_of = open5e.models.character_class_summary.CharacterClassSummary(
                            name = '', 
                            key = '', ), 
                        name = '', 
                        desc = '', 
                        hit_dice = 'D3', 
                        caster_type = 'FULL', 
                        primary_abilities = [
                            ''
                            ], 
                        crossreferences = null, )
                    ],
        )
        """

    def testPaginatedCharacterClassList(self):
        """Test PaginatedCharacterClassList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
