# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.creature import Creature

class TestCreature(unittest.TestCase):
    """Creature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Creature:
        """Test Creature
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Creature`
        """
        model = Creature()
        if include_optional:
            return Creature(
                key = '',
                name = '',
                document = open5e.models.document_summary.DocumentSummary(
                    name = '', 
                    key = '', 
                    type = 'SOURCE', 
                    display_name = '', 
                    publisher = open5e.models.publisher_summary.PublisherSummary(
                        name = '', 
                        key = '', ), 
                    gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                        name = '', 
                        key = '', ), 
                    permalink = '', ),
                type = open5e.models.creature_type_summary.CreatureTypeSummary(
                    name = '', 
                    key = '', ),
                size = open5e.models.size_summary.SizeSummary(
                    name = '', 
                    key = '', ),
                challenge_rating = 0,
                proficiency_bonus = -9223372036854775808,
                speed = open5e.models.speed.speed(
                    walk = '', 
                    fly = '', 
                    swim = '', 
                    climb = '', 
                    burrow = '', 
                    hover = True, ),
                speed_all = open5e.models.speed_all.speed_all(
                    unit = '', 
                    walk = 56, 
                    crawl = 56, 
                    hover = True, 
                    fly = 56, 
                    burrow = 56, 
                    climb = 56, 
                    swim = 56, ),
                category = '',
                subcategory = '',
                alignment = '',
                languages = open5e.models.creature_language.CreatureLanguage(
                    as_string = '', 
                    data = [
                        open5e.models.language_summary.LanguageSummary(
                            name = '', 
                            key = '', 
                            desc = '', )
                        ], ),
                armor_class = 0,
                armor_detail = '',
                hit_points = 0,
                hit_dice = '',
                experience_points = 56,
                ability_scores = open5e.models.ability_scores.ability_scores(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                modifiers = open5e.models.ability_modifiers.ability_modifiers(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                initiative_bonus = 56,
                saving_throws = open5e.models.saving_throws.saving_throws(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                saving_throws_all = open5e.models.saving_throws_all.saving_throws_all(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                skill_bonuses = open5e.models.skill_bonuses.skill_bonuses(
                    acrobatics = 56, 
                    animal_handling = 56, 
                    arcana = 56, 
                    athletics = 56, 
                    deception = 56, 
                    history = 56, 
                    insight = 56, 
                    intimidation = 56, 
                    investigation = 56, 
                    medicine = 56, 
                    nature = 56, 
                    perception = 56, 
                    performance = 56, 
                    persuasion = 56, 
                    religion = 56, 
                    sleight_of_hand = 56, 
                    stealth = 56, 
                    survival = 56, ),
                skill_bonuses_all = open5e.models.skill_bonuses_all.skill_bonuses_all(
                    acrobatics = 56, 
                    animal_handling = 56, 
                    arcana = 56, 
                    athletics = 56, 
                    deception = 56, 
                    history = 56, 
                    insight = 56, 
                    intimidation = 56, 
                    investigation = 56, 
                    medicine = 56, 
                    nature = 56, 
                    perception = 56, 
                    performance = 56, 
                    persuasion = 56, 
                    religion = 56, 
                    sleight_of_hand = 56, 
                    stealth = 56, 
                    survival = 56, ),
                passive_perception = 0,
                resistances_and_immunities = open5e.models.creature_resistances_and_immunities.CreatureResistancesAndImmunities(
                    damage_immunities_display = '', 
                    damage_immunities = [
                        open5e.models.damage_type_summary.DamageTypeSummary(
                            name = '', 
                            key = '', )
                        ], 
                    damage_resistances_display = '', 
                    damage_resistances = [
                        open5e.models.damage_type_summary.DamageTypeSummary(
                            name = '', 
                            key = '', )
                        ], 
                    damage_vulnerabilities_display = '', 
                    damage_vulnerabilities = [
                        
                        ], 
                    condition_immunities_display = '', 
                    condition_immunities = [
                        open5e.models.condition_summary.ConditionSummary(
                            name = '', 
                            key = '', )
                        ], ),
                normal_sight_range = 0,
                darkvision_range = 0,
                blindsight_range = 0,
                tremorsense_range = 0,
                truesight_range = 0,
                actions = [
                    open5e.models.creature_action.CreatureAction(
                        name = '', 
                        desc = '', 
                        attacks = [
                            open5e.models.creature_action_attack.CreatureActionAttack(
                                name = '', 
                                attack_type = 'SPELL', 
                                to_hit_mod = -5, 
                                reach = 0, 
                                range = 0, 
                                long_range = 0, 
                                target_creature_only = True, 
                                damage_die_count = 0, 
                                damage_die_type = 'D3', 
                                damage_bonus = -5, 
                                damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                                    name = '', 
                                    key = '', ), 
                                extra_damage_die_count = 0, 
                                extra_damage_die_type = 'D3', 
                                extra_damage_bonus = -5, 
                                extra_damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                                    name = '', 
                                    key = '', ), 
                                distance_unit = '', )
                            ], 
                        action_type = 'ACTION', 
                        order_in_statblock = -9223372036854775808, 
                        legendary_action_cost = -9223372036854775808, 
                        limited_to_form = '', 
                        usage_limits = {
                            'key' : null
                            }, )
                    ],
                traits = [
                    open5e.models.creature_trait.CreatureTrait(
                        name = '', 
                        desc = '', )
                    ],
                creaturesets = [
                    ''
                    ],
                environments = [
                    open5e.models.environment_summary.EnvironmentSummary(
                        name = '', 
                        key = '', )
                    ],
                illustration = open5e.models.image_summary.ImageSummary(
                    name = '', 
                    key = '', 
                    file_url = '', 
                    alt_text = '', 
                    attribution = '', ),
                crossreferences = open5e.models.cross_references.CrossReferences(
                    to = [
                        open5e.models._cross_reference_link._CrossReferenceLink(
                            anchor = '', 
                            url = '', )
                        ], )
            )
        else:
            return Creature(
                key = '',
                name = '',
                document = open5e.models.document_summary.DocumentSummary(
                    name = '', 
                    key = '', 
                    type = 'SOURCE', 
                    display_name = '', 
                    publisher = open5e.models.publisher_summary.PublisherSummary(
                        name = '', 
                        key = '', ), 
                    gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                        name = '', 
                        key = '', ), 
                    permalink = '', ),
                type = open5e.models.creature_type_summary.CreatureTypeSummary(
                    name = '', 
                    key = '', ),
                size = open5e.models.size_summary.SizeSummary(
                    name = '', 
                    key = '', ),
                challenge_rating = 0,
                speed = open5e.models.speed.speed(
                    walk = '', 
                    fly = '', 
                    swim = '', 
                    climb = '', 
                    burrow = '', 
                    hover = True, ),
                speed_all = open5e.models.speed_all.speed_all(
                    unit = '', 
                    walk = 56, 
                    crawl = 56, 
                    hover = True, 
                    fly = 56, 
                    burrow = 56, 
                    climb = 56, 
                    swim = 56, ),
                category = '',
                alignment = '',
                languages = open5e.models.creature_language.CreatureLanguage(
                    as_string = '', 
                    data = [
                        open5e.models.language_summary.LanguageSummary(
                            name = '', 
                            key = '', 
                            desc = '', )
                        ], ),
                experience_points = 56,
                ability_scores = open5e.models.ability_scores.ability_scores(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                modifiers = open5e.models.ability_modifiers.ability_modifiers(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                initiative_bonus = 56,
                saving_throws = open5e.models.saving_throws.saving_throws(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                saving_throws_all = open5e.models.saving_throws_all.saving_throws_all(
                    strength = 56, 
                    dexterity = 56, 
                    constitution = 56, 
                    intelligence = 56, 
                    wisdom = 56, 
                    charisma = 56, ),
                skill_bonuses = open5e.models.skill_bonuses.skill_bonuses(
                    acrobatics = 56, 
                    animal_handling = 56, 
                    arcana = 56, 
                    athletics = 56, 
                    deception = 56, 
                    history = 56, 
                    insight = 56, 
                    intimidation = 56, 
                    investigation = 56, 
                    medicine = 56, 
                    nature = 56, 
                    perception = 56, 
                    performance = 56, 
                    persuasion = 56, 
                    religion = 56, 
                    sleight_of_hand = 56, 
                    stealth = 56, 
                    survival = 56, ),
                skill_bonuses_all = open5e.models.skill_bonuses_all.skill_bonuses_all(
                    acrobatics = 56, 
                    animal_handling = 56, 
                    arcana = 56, 
                    athletics = 56, 
                    deception = 56, 
                    history = 56, 
                    insight = 56, 
                    intimidation = 56, 
                    investigation = 56, 
                    medicine = 56, 
                    nature = 56, 
                    perception = 56, 
                    performance = 56, 
                    persuasion = 56, 
                    religion = 56, 
                    sleight_of_hand = 56, 
                    stealth = 56, 
                    survival = 56, ),
                resistances_and_immunities = open5e.models.creature_resistances_and_immunities.CreatureResistancesAndImmunities(
                    damage_immunities_display = '', 
                    damage_immunities = [
                        open5e.models.damage_type_summary.DamageTypeSummary(
                            name = '', 
                            key = '', )
                        ], 
                    damage_resistances_display = '', 
                    damage_resistances = [
                        open5e.models.damage_type_summary.DamageTypeSummary(
                            name = '', 
                            key = '', )
                        ], 
                    damage_vulnerabilities_display = '', 
                    damage_vulnerabilities = [
                        
                        ], 
                    condition_immunities_display = '', 
                    condition_immunities = [
                        open5e.models.condition_summary.ConditionSummary(
                            name = '', 
                            key = '', )
                        ], ),
                actions = [
                    open5e.models.creature_action.CreatureAction(
                        name = '', 
                        desc = '', 
                        attacks = [
                            open5e.models.creature_action_attack.CreatureActionAttack(
                                name = '', 
                                attack_type = 'SPELL', 
                                to_hit_mod = -5, 
                                reach = 0, 
                                range = 0, 
                                long_range = 0, 
                                target_creature_only = True, 
                                damage_die_count = 0, 
                                damage_die_type = 'D3', 
                                damage_bonus = -5, 
                                damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                                    name = '', 
                                    key = '', ), 
                                extra_damage_die_count = 0, 
                                extra_damage_die_type = 'D3', 
                                extra_damage_bonus = -5, 
                                extra_damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                                    name = '', 
                                    key = '', ), 
                                distance_unit = '', )
                            ], 
                        action_type = 'ACTION', 
                        order_in_statblock = -9223372036854775808, 
                        legendary_action_cost = -9223372036854775808, 
                        limited_to_form = '', 
                        usage_limits = {
                            'key' : null
                            }, )
                    ],
                traits = [
                    open5e.models.creature_trait.CreatureTrait(
                        name = '', 
                        desc = '', )
                    ],
                creaturesets = [
                    ''
                    ],
                environments = [
                    open5e.models.environment_summary.EnvironmentSummary(
                        name = '', 
                        key = '', )
                    ],
                illustration = open5e.models.image_summary.ImageSummary(
                    name = '', 
                    key = '', 
                    file_url = '', 
                    alt_text = '', 
                    attribution = '', ),
                crossreferences = open5e.models.cross_references.CrossReferences(
                    to = [
                        open5e.models._cross_reference_link._CrossReferenceLink(
                            anchor = '', 
                            url = '', )
                        ], ),
        )
        """

    def testCreature(self):
        """Test Creature"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
