# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.document_summary import DocumentSummary

class TestDocumentSummary(unittest.TestCase):
    """DocumentSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentSummary:
        """Test DocumentSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentSummary`
        """
        model = DocumentSummary()
        if include_optional:
            return DocumentSummary(
                name = '',
                key = '',
                type = 'SOURCE',
                display_name = '',
                publisher = open5e.models.publisher_summary.PublisherSummary(
                    name = '', 
                    key = '', ),
                gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                    name = '', 
                    key = '', ),
                permalink = ''
            )
        else:
            return DocumentSummary(
                name = '',
                key = '',
                display_name = '',
                publisher = open5e.models.publisher_summary.PublisherSummary(
                    name = '', 
                    key = '', ),
                gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                    name = '', 
                    key = '', ),
                permalink = '',
        )
        """

    def testDocumentSummary(self):
        """Test DocumentSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
