# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.ability_modifiers import AbilityModifiers

class TestAbilityModifiers(unittest.TestCase):
    """AbilityModifiers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbilityModifiers:
        """Test AbilityModifiers
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbilityModifiers`
        """
        model = AbilityModifiers()
        if include_optional:
            return AbilityModifiers(
                strength = 56,
                dexterity = 56,
                constitution = 56,
                intelligence = 56,
                wisdom = 56,
                charisma = 56
            )
        else:
            return AbilityModifiers(
                strength = 56,
                dexterity = 56,
                constitution = 56,
                intelligence = 56,
                wisdom = 56,
                charisma = 56,
        )
        """

    def testAbilityModifiers(self):
        """Test AbilityModifiers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
