# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.class_feature_prefetch import ClassFeaturePrefetch

class TestClassFeaturePrefetch(unittest.TestCase):
    """ClassFeaturePrefetch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClassFeaturePrefetch:
        """Test ClassFeaturePrefetch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClassFeaturePrefetch`
        """
        model = ClassFeaturePrefetch()
        if include_optional:
            return ClassFeaturePrefetch(
                level = 0,
                detail = '',
                column_value = ''
            )
        else:
            return ClassFeaturePrefetch(
                level = 0,
        )
        """

    def testClassFeaturePrefetch(self):
        """Test ClassFeaturePrefetch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
