# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.spell import Spell

class TestSpell(unittest.TestCase):
    """Spell unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Spell:
        """Test Spell
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Spell`
        """
        model = Spell()
        if include_optional:
            return Spell(
                key = '',
                document = open5e.models.document_summary.DocumentSummary(
                    name = '', 
                    key = '', 
                    type = 'SOURCE', 
                    display_name = '', 
                    publisher = open5e.models.publisher_summary.PublisherSummary(
                        name = '', 
                        key = '', ), 
                    gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                        name = '', 
                        key = '', ), 
                    permalink = '', ),
                casting_options = [
                    open5e.models.spell_casting_option.SpellCastingOption(
                        type = 'default', 
                        damage_roll = '', 
                        target_count = 0, 
                        duration = '', 
                        range = '', 
                        concentration = True, 
                        shape_size = 0, 
                        desc = '', )
                    ],
                school = open5e.models.spell_school_summary.SpellSchoolSummary(
                    name = '', 
                    key = '', ),
                classes = [
                    open5e.models.character_class_summary.CharacterClassSummary(
                        name = '', 
                        key = '', )
                    ],
                range_unit = '',
                shape_size_unit = '',
                name = '',
                desc = '',
                level = 0,
                higher_level = '',
                target_type = 'creature',
                range_text = '',
                range = 0,
                ritual = True,
                casting_time = 'reaction',
                reaction_condition = '',
                verbal = True,
                somatic = True,
                material = True,
                material_specified = '',
                material_cost = '-80728880',
                material_consumed = True,
                target_count = 0,
                saving_throw_ability = '',
                attack_roll = True,
                damage_roll = '',
                damage_types = None,
                duration = 'instantaneous',
                shape_type = 'cone',
                shape_size = 0,
                concentration = True,
                crossreferences = open5e.models.cross_references.CrossReferences(
                    to = [
                        open5e.models._cross_reference_link._CrossReferenceLink(
                            anchor = '', 
                            url = '', )
                        ], )
            )
        else:
            return Spell(
                key = '',
                document = open5e.models.document_summary.DocumentSummary(
                    name = '', 
                    key = '', 
                    type = 'SOURCE', 
                    display_name = '', 
                    publisher = open5e.models.publisher_summary.PublisherSummary(
                        name = '', 
                        key = '', ), 
                    gamesystem = open5e.models.game_system_summary.GameSystemSummary(
                        name = '', 
                        key = '', ), 
                    permalink = '', ),
                casting_options = [
                    open5e.models.spell_casting_option.SpellCastingOption(
                        type = 'default', 
                        damage_roll = '', 
                        target_count = 0, 
                        duration = '', 
                        range = '', 
                        concentration = True, 
                        shape_size = 0, 
                        desc = '', )
                    ],
                school = open5e.models.spell_school_summary.SpellSchoolSummary(
                    name = '', 
                    key = '', ),
                classes = [
                    open5e.models.character_class_summary.CharacterClassSummary(
                        name = '', 
                        key = '', )
                    ],
                range_unit = '',
                shape_size_unit = '',
                name = '',
                level = 0,
                range_text = '',
                casting_time = 'reaction',
                duration = 'instantaneous',
                crossreferences = open5e.models.cross_references.CrossReferences(
                    to = [
                        open5e.models._cross_reference_link._CrossReferenceLink(
                            anchor = '', 
                            url = '', )
                        ], ),
        )
        """

    def testSpell(self):
        """Test Spell"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
