# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.skill_bonuses_all import SkillBonusesAll

class TestSkillBonusesAll(unittest.TestCase):
    """SkillBonusesAll unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkillBonusesAll:
        """Test SkillBonusesAll
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkillBonusesAll`
        """
        model = SkillBonusesAll()
        if include_optional:
            return SkillBonusesAll(
                acrobatics = 56,
                animal_handling = 56,
                arcana = 56,
                athletics = 56,
                deception = 56,
                history = 56,
                insight = 56,
                intimidation = 56,
                investigation = 56,
                medicine = 56,
                nature = 56,
                perception = 56,
                performance = 56,
                persuasion = 56,
                religion = 56,
                sleight_of_hand = 56,
                stealth = 56,
                survival = 56
            )
        else:
            return SkillBonusesAll(
                acrobatics = 56,
                animal_handling = 56,
                arcana = 56,
                athletics = 56,
                deception = 56,
                history = 56,
                insight = 56,
                intimidation = 56,
                investigation = 56,
                medicine = 56,
                nature = 56,
                perception = 56,
                performance = 56,
                persuasion = 56,
                religion = 56,
                sleight_of_hand = 56,
                stealth = 56,
                survival = 56,
        )
        """

    def testSkillBonusesAll(self):
        """Test SkillBonusesAll"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
