# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.api.spells_api import SpellsApi


class TestSpellsApi(unittest.TestCase):
    """SpellsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpellsApi()

    def tearDown(self) -> None:
        pass

    def test_spells_list(self) -> None:
        """Test case for spells_list

        """
        pass

    def test_spells_retrieve(self) -> None:
        """Test case for spells_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
