# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.cross_references import CrossReferences

class TestCrossReferences(unittest.TestCase):
    """CrossReferences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CrossReferences:
        """Test CrossReferences
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CrossReferences`
        """
        model = CrossReferences()
        if include_optional:
            return CrossReferences(
                to = [
                    open5e.models._cross_reference_link._CrossReferenceLink(
                        anchor = '', 
                        url = '', )
                    ]
            )
        else:
            return CrossReferences(
                to = [
                    open5e.models._cross_reference_link._CrossReferenceLink(
                        anchor = '', 
                        url = '', )
                    ],
        )
        """

    def testCrossReferences(self):
        """Test CrossReferences"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
