# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.creature_resistances_and_immunities import CreatureResistancesAndImmunities

class TestCreatureResistancesAndImmunities(unittest.TestCase):
    """CreatureResistancesAndImmunities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatureResistancesAndImmunities:
        """Test CreatureResistancesAndImmunities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatureResistancesAndImmunities`
        """
        model = CreatureResistancesAndImmunities()
        if include_optional:
            return CreatureResistancesAndImmunities(
                damage_immunities_display = '',
                damage_immunities = [
                    open5e.models.damage_type_summary.DamageTypeSummary(
                        name = '', 
                        key = '', )
                    ],
                damage_resistances_display = '',
                damage_resistances = [
                    open5e.models.damage_type_summary.DamageTypeSummary(
                        name = '', 
                        key = '', )
                    ],
                damage_vulnerabilities_display = '',
                damage_vulnerabilities = [
                    open5e.models.damage_type_summary.DamageTypeSummary(
                        name = '', 
                        key = '', )
                    ],
                condition_immunities_display = '',
                condition_immunities = [
                    open5e.models.condition_summary.ConditionSummary(
                        name = '', 
                        key = '', )
                    ]
            )
        else:
            return CreatureResistancesAndImmunities(
                damage_immunities_display = '',
                damage_immunities = [
                    open5e.models.damage_type_summary.DamageTypeSummary(
                        name = '', 
                        key = '', )
                    ],
                damage_resistances_display = '',
                damage_resistances = [
                    open5e.models.damage_type_summary.DamageTypeSummary(
                        name = '', 
                        key = '', )
                    ],
                damage_vulnerabilities_display = '',
                damage_vulnerabilities = [
                    open5e.models.damage_type_summary.DamageTypeSummary(
                        name = '', 
                        key = '', )
                    ],
                condition_immunities_display = '',
                condition_immunities = [
                    open5e.models.condition_summary.ConditionSummary(
                        name = '', 
                        key = '', )
                    ],
        )
        """

    def testCreatureResistancesAndImmunities(self):
        """Test CreatureResistancesAndImmunities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
