# coding: utf-8

"""
    Open5e — demo subset

    The Open5e API. See [https://github.com/open5e/open5e-api] for more information.  DEMO SUBSET: trimmed to spells, creatures, and classes to keep the docs-tooling comparison clean and within free-tier limits. The full spec is shared/openapi.json.

    The version of the OpenAPI document: development (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from open5e.models.creature_action_attack import CreatureActionAttack

class TestCreatureActionAttack(unittest.TestCase):
    """CreatureActionAttack unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatureActionAttack:
        """Test CreatureActionAttack
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatureActionAttack`
        """
        model = CreatureActionAttack()
        if include_optional:
            return CreatureActionAttack(
                name = '',
                attack_type = 'SPELL',
                to_hit_mod = -5,
                reach = 0,
                range = 0,
                long_range = 0,
                target_creature_only = True,
                damage_die_count = 0,
                damage_die_type = 'D3',
                damage_bonus = -5,
                damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                    name = '', 
                    key = '', ),
                extra_damage_die_count = 0,
                extra_damage_die_type = 'D3',
                extra_damage_bonus = -5,
                extra_damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                    name = '', 
                    key = '', ),
                distance_unit = ''
            )
        else:
            return CreatureActionAttack(
                name = '',
                attack_type = 'SPELL',
                to_hit_mod = -5,
                target_creature_only = True,
                damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                    name = '', 
                    key = '', ),
                extra_damage_type = open5e.models.damage_type_summary.DamageTypeSummary(
                    name = '', 
                    key = '', ),
                distance_unit = '',
        )
        """

    def testCreatureActionAttack(self):
        """Test CreatureActionAttack"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
